### ISSUE TITLE
SVPFlow Latest Version Requires SVPManager

### ISSUE THREAD

**Issue by AlperMertI** [staxrip/staxrip#1013]
**Describe the bug**
Lately SVPFlow updated to the latest version and that version requires SVPManager to work. If it doesn't found instance of SVPManager, filter adds red borders to the video and do not interpolate.

**Expected behavior**
SVPFlow to work without the requirement of SVPManager.

**How to reproduce the issue**

You can try with any source file.

- Used StaxRip version
v2.19.0

**Additional context**
The version v4.2.0.142 ( latest version to work without the requirement of SVPManager ) works without problem but it is not the latest version.

**Comment by Dendraspis** [comment]
Thanks a lot for the report.

Sadly I could find an older version, especially your mentioned v4.2.0.142, so I switch back to the one from v2.17.0, which should be SVPFlow v4.2.0.133.

I'll close this for now, but if you can tell me where to find that version, I can update it for StaxRip.

**Comment by AlperMertI** [comment]
> Thanks a lot for the report.
> 
> Sadly I could find an older version, especially your mentioned v4.2.0.142, so I switch back to the one from v2.17.0, which should be SVPFlow v4.2.0.133.
> 
> I'll close this for now, but if you can tell me where to find that version, I can update it for StaxRip.

Hey, check it out:
Source: http://avisynth.nl/index.php/SVPflow#Downloads
v4.2.0.133: https://web.archive.org/web/20190322064557/http://www.svp-team.com/files/gpl/svpflow-4.2.0.142.zip

**Comment by nero-0** [comment]
A few years ago a guy named Nuihc88 shared the "last good versions" (no SVP Manager required) known on the doom9 forum: https://forum.doom9.org/showthread.php?p=1914245#post1914245

Apparently the server where the files were stored has shut down its services, but it's still possible to get the files through an archived snapshot: https://web.archive.org/web/20220821200144/http://k007.kiwi6.com/hotlink/6k2losau0b/SVPflow_LastGoodVersions.7z

I used it a few times a while ago and didn't find any problems, but you can try it for yourself if you like.
Only posting because they are newer dlls than the ones mentioned above. 🙂
