### ISSUE TITLE
x265 encoder update with all new feature available

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1014]
Hi,

there is new x265 with Patman mods (AVS, AQ-MODE 5, ...) version available with new feature... 
Please update Staxrip to be able to use them... 

https://github.com/jpsdr/x265/releases/tag/r3.50.103

**Comment by Dendraspis** [comment]
Hi,
I was recently told about this one and that "it works". I'm going to update x265 in the next weeks.

Btw:  You know, that you can update it by yourself for your local copy?

**Comment by madey83** [comment]
hi,

Yes, i know that, but Staxrip interface is not showing all new features - i think so... or am i wrong.

**Comment by Dendraspis** [comment]
Yes, you're right. 
Just thought you could use also the Custon field to set up missing params, because you requested the new version. As far as I remember x265 is kind of finished and only minor changes are made, so it should not be that important to update.

Nevertheless it's coming, probably with the next release. (no warrenty)

**Comment by Dendraspis** [comment]
The next release will include the newest build from Patman86:
https://github.com/Patman86/x265-Mod-by-Patman/releases/tag/3.5%2B104%2B11

Feel free to update x265 by hand if you can't wait.  😅
