### ISSUE TITLE
Dogway's Avisynth-Scripts

### ISSUE THREAD

**Issue by madey83** [staxrip/staxrip#1015]
Could please include in next release all Dogway's Avisynth-Scripts with all dependancies? 

https://github.com/Dogway/Avisynth-Scripts

**Comment by madey83** [comment]
this is not an issue, but feature requesst, i know that i can import/load plugin insite app, but having them already in the app is more usefull.

**Comment by Dendraspis** [comment]
I know.  😅 
Nevertheless it's a lot of work..

Btw, next time you can add it here (probably a bit splitted):
https://github.com/staxrip/staxrip/wiki/Tool-Update-Requests

**Comment by Ding-adong** [comment]
Just do what everyone else done. DL any scripts you want and put them in your avisynth folders ie.
C:\Program Files (x86)\AviSynth\plugins+ 32 bits
C:\Program Files (x86)\AviSynth\plugins64+ 64 bits.

Staxrip will look into their own folders and if it isn't there then look into avisynth folders above and use them.

You don't have to DL and put them into staxrip app etc.

This way users can update the scripts immediately instead of waiting for the next staxrip release. After all Dogway's scripts are being updated weekly with more options and refinement.
