### ISSUE TITLE
SVT-AV1 1.6 incorrect frame amount

### ISSUE THREAD

**Issue by sjples** [staxrip/staxrip#1034]
**Describe the bug**

The version 1.6 of the SVT-AV1 encoder included has more frames on the encoded file than the original file. This leads to an issue with VFR files since the timecodes will not match, resulting in audio sync issues.

**Expected behavior**

Frame amount must be the same as the original file.

**How to reproduce the issue**

Just encode any files using the SVT-AV1 1.6 included with the program. Note number of original frames and the av1 encode, they will be different with the av1 encode having significantly more frames. I used mpc-hc to check by playing/seeking to the last frame and using the "Go to..." function to see the frame number. Also shows slightly higher fps 30.303 instead of 29.970.

**Provide information**

StaxRip version 2.21

**Additional context**

Copying the new encoder to Staxrip 2.20 resulted in the same problem.
SVT-AV1 1.5 does not have this problem
If opened with LWlibavVideoSource in Avisynth, the encoded file shows the correct number of frames, but media players seems to read the files wrong and have audio sync issues. Tested with different players (MPC-HC, VLC and Windows Media player), all have the same problem.

**Comment by sjples** [comment]
My workflow is processing from DVD using Avisynth, then upscaling with chaiNNer with an FFV1 encode, then using Staxrip for a 10-bit AV1 encode, and finally using mkvtoolnix to add the timecodes and audio. Attached is a small sample clip, i did not add the FFV1 encode because the file is too big.
Audio desync is not noticeable with such a short clip.
Staxrip filter is only ConvertBits(10)
[sample clip.zip](https://github.com/staxrip/staxrip/files/11952918/sample.clip.zip)
[SVT-AV1 1.6 bug.zip](https://github.com/staxrip/staxrip/files/11952921/SVT-AV1.1.6.bug.zip)

**Comment by Dendraspis** [comment]
As you already mentioned, I truly can't recognize any mismatches. But interestingly the media info of source and encoded file tells us a bit about the problem:

**Source:**
```
Frame rate mode                          : VFR
Frame rate mode                          : Variable
Frame rate                               : 8659.854
Frame rate                               : 8 659.854 FPS
Original frame rate                      : 29.970
Original frame rate                      : 29.970 (30000/1001) FPS
FrameRate_Original_Num                   : 30000
FrameRate_Original_Den                   : 1001
Frame count                              : 177120
```

**`SVT-AV1 v1.5.0` and `SVT-AV1 v1.6.0` - with and without `AssumeFPS`:**
```
Frame rate mode                          : VFR
Frame rate mode                          : Variable
Frame rate                               : 30.069
Frame rate                               : 30.069 FPS
Frame count                              : 615
```

**Here I used `x265` with piping through `ffmpeg` (like it is with `SVT-AV1, even the parameters are a bit different)`:**
```
Frame rate mode                          : VFR
Frame rate mode                          : Variable
Frame rate                               : 30.069
Frame rate                               : 30.069 FPS
Frame count                              : 615
```

**...same `x265` test also using `AssumeFPS`:**
```
Frame rate mode                          : VFR
Frame rate mode                          : Variable
Frame rate                               : 30.069
Frame rate                               : 30.069 FPS
Original frame rate                      : 29.970
Original frame rate                      : 29.970 (30000/1001) FPS
FrameRate_Original_Num                   : 30000
FrameRate_Original_Den                   : 1001
Frame count                              : 615
```

...that **could** be the problem.
I guess, that the frame rate is not taken into account correctly by `SVT-AV1`, even both versions produce the same media info related to the frame rate and all durations are the same. Because the command line looks good, the only thing I could do is to downgrade `SVT-AV1` to `v1.5.0`, but `v1.6.0` was highly requested.  😕 

I suggest you stick to `v1.5.0`, at least for VFR files. Maybe it's just a bug that will be fixed with the next release. Of course you could also open an issue [here](https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues) for that. Due to the fact that ffmpeg is used along with this very short script, there is a high chance someone is going to look at it and tell you more about your problem.

**Comment by sjples** [comment]
I think I found a workaround, just need more testing. In the Container Configuration's Options tab, Staxrip adds a timestamp file automatically. When I remove that entry, it encodes the right amount of frames. So maybe adding an option to not add the timestamps automatically, can be a good temporary fix. The speed difference between 1.5 and 1.6 is massive. I even have 1.6 using a higher quality preset.

**Comment by sjples** [comment]
I tinkered with the settings to find something that will stop staxrip from adding timestamps, and I think I found it. In the Preprocessing tab, unchecking mkvextract disables the adding of timestamps to the encode.

**Comment by Dendraspis** [comment]
Of course removing the timestamps could help, but you don't change the frame rate intentionally, so they must fit the original and encoded file. Pretty annoying, that it worked with `SVT-AV1 v1.5.0` like you mentioned. But why not...

Timestamp extraction can easily be set via Options:  😉 
![image](https://github.com/staxrip/staxrip/assets/50659978/d3873feb-33e7-45d1-9a92-9cdfad55ce63)

**Comment by sjples** [comment]
I had an issue with that setting not saving when I exit. Then I tried just now saving as template, and it saved. Staxrip not being clear that it is part of the template and not the settings, and will be reset. I have checked both options and the timestamps are no longer being added even with mkvextract enabled. Maybe also having both options checked as default next version, if it will not impact the normal encodes. CFR has no need for timestamps right?

**Comment by Dendraspis** [comment]
Not sure if I understand you...

> Staxrip not being clear that it is part of the template and not the settings, and will be reset.

???

> I have checked both options and the timestamps are no longer being added even with mkvextract enabled.

Do you mean `checked` or `unchecked`? Because `checked` would mean, that timestamps are extracted/created.

> Maybe also having both options checked as default next version, if it will not impact the normal encodes.

Both checkboxes **checked** is the default setting since `Staxrip v2.18.0 (2023-05-22)`. So I guess you use or even copy old settings with a new StaxRip version? I highly recommend to start with fresh settings every time to avoid such issues.

> CFR has no need for timestamps right?

That's correct.

**Comment by sjples** [comment]
That just might be the case, since I only copied my old template.

**Comment by sjples** [comment]
Thanks for the time and effort. Bug will not be present with fresh default settings.
