### ISSUE TITLE
Differential release

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#1038]
Staxrip is a huge amount of plugins and executable and not always the included tools are on par with the current releases. Sometimes it's needed to manually update them before the newer Staxrip release alignes with last ones.

Every time a new release of Staxrip is out, we have to painfully and carefully copy just the new versions of files, otherwise we could overwrite with older ones.

Could you release a "differential" archive of just the files that are different/updated from the previous version?

**Comment by Discograp** [comment]
if I use v.2.22.0 then fixes from v.2.21.0 will work?

**Comment by Dendraspis** [comment]
@Discograp  Of course. Each release includes all changes from previous releases.

**Comment by tormento** [comment]
@Dendraspis thanks for accepting my request. Beside that, for the long term, what about an update system like MeGui?

**Comment by Dendraspis** [comment]
I have marked it as a feature request (because it is), that doesn't mean it's accepted yet.  😬 
To be honest I don't think I would put even more time into updates and additionally I don't think it is even possible without making a new app, script or so for that, because there are not just files to be added or replaced, sometimes you also have to delete or rename files.

I guess the painfully way to check and compare with the Changelog will be the only way.

**Comment by tormento** [comment]
So, perhaps, the smart answer would be to release updates just for the Staxrip program part and just let the user to provide himself the other parts ;)

**Comment by Dendraspis** [comment]
The base part is the `exe` file. Everything else in the `Apps` folder is just an add-on, that is replaceable.
Side note: I don't recommend to mix up with the `Settings` folder, because this can have annoying side effects.

In my opinion you should look at the Changelog and decide, if you are willed to update or not. You don't have to update, for example if there are just minor changes that don't affect your workflow. The Changelog also tells you exactly which tools and filters were replaced, so
- either you start with a clean instance and replace the tools/filters you want
- or you delete the Settings folder and replace the `exe` file only. In that case you have to be aware, that some tools/filters have been added or renamed, so you have to take care of it when StaxRip gives you a warning. Or you disable versioning checks and tool status verification in the settings
- or you can also use two different versions in parallel for different needs.

There are many ways, you just have to choose the best one that fits your needs.

**Comment by Dendraspis** [comment]
Sorry, but after re-thinking multiple times about a proper solution, it turned out to be too time consuming, which would prevent other features being realized. I already gave you a few possible solutions, maybe you'll find an even better one that fits your needs.

Apart from that, StaxRip will always have problems with shared settings files, so in case of an update, you would still have to re-make everything internal to prevent wrong behavior. So keeping that in mind, it won't make much sense making a differential release.
