### ISSUE TITLE
Event command Criteria Section doesn't have a scroll bar with lots of filters

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#1048]
![image](https://github.com/staxrip/staxrip/assets/48299282/4cf629e1-f74c-4660-9559-e00b97389510)

Would like a scroll bar to appear if there is lots of options.

**Comment by Dendraspis** [comment]
Ok, I've spent multiple hours and can't fix it the right way. The old UI and the way criteria are implemented don't work together.

But I've managed to add a vertical scrollbar, that is always visible. For a specific amount of criteria (~22) it does work well, but if you add too much, it starts glitching again and adds them on the right with a horizontal scrollbar.

At least I used the *chance* to fix a few other bugs including one that crashes StaxRip.  😬 

Nevertheless I close this one, because I can't see to make it better. If there is something I forget, please reopen this issue.
If you need more vertical space for the criteria, please tell me and I will adjust it.

![image](https://github.com/staxrip/staxrip/assets/50659978/0fde0b4e-a369-4110-a170-1e9b62980460)

**Comment by jlw4049** [comment]
This shouls very adequate thanks again!
