### ISSUE TITLE
temporaldegrain2 not working

### ISSUE THREAD

**Issue by craposoup** [staxrip/staxrip#1056]
temporaldegrain2 is still not working:

![image](https://github.com/staxrip/staxrip/assets/49623148/e9b2c7d7-73a8-49d6-9a46-095296e96b81)

Script Error

System exception - Illegal Instruction
(C:\StaxRip-v2.24.0-x64\Apps\Plugins\AVS\TemporalDegrain2\TemporalDegrain2.avsi, line 424)
(C:\Temp\20.ht90s_temp\20.ht90s.avs, line 43)

**20.ht90s.avs**
![image](https://github.com/staxrip/staxrip/assets/49623148/adc87c02-3ed3-4f0f-a177-4b3162c45579)

**Comment by Dendraspis** [comment]
Should already be fixed for the next release. Was a pretty mess with the dependencies to make them work with AVS and VS and multiple filters.

If the next release doesn't fix it for you, please reopen this issue and try providing a sample file, because the settings should be the same (except the `Source`).

![image](https://github.com/staxrip/staxrip/assets/50659978/13d47470-c72b-4587-82f4-c9fba72e07cc)
