### ISSUE TITLE
Dialog for demuxing audio tracks does not work for multiple files.

### ISSUE THREAD

**Issue by Piscator74** [staxrip/staxrip#1057]
**Describe the bug**
The audio project option for "Demux Audio" set to "Show Dialog" does only work for the first file when selecting "Multiple Files" (when opening video sources). For the remainder of the files, all audio tracks are demuxed (so the first 2 tracks are selected in the UI)

**Expected behavior**
A dialog that shows the audio tracks for each file opened.

**How to reproduce the issue**
1. Go to: Options / Audio / Demux Audio and set to "Show Dialog"
2. Go to: File / Open Video Source File and select "Multiple Files"

Also when saving the option in a project template, the dialog only works on the first file.

**Comment by Dendraspis** [comment]
We have to split it in half:
1. When you open multiple files, the first one is opened by the current instance. The next files are opened in new instances, that use the startup template.
2. The In `v2.24` (and prior) there is an issue when you save a template and set it to be used as startup template. It will be set, but the settings are not saved instantly. So you have to open and close the settings or restart StaxRip so the next instances know that the startup template changed. This behavior will be fixed in the next release.

So starting with the next release you have to setup the right startup template and then open the files you want.
So I close this issue for now...

**Comment by Piscator74** [comment]
And also thanks for the described workaround; that works nicely for now.
