### ISSUE TITLE
Auto Cropping when encoding

### ISSUE THREAD

**Issue by JohnCale47** [staxrip/staxrip#1063]
Its pretty simple idea, load a source file check Auto Crop option and start the job. 
what it does is staxrip uses the **Auto Crop** feature available in **Crop Menu**  

![image](https://github.com/staxrip/staxrip/assets/37181988/12342fd6-eea8-4042-b910-6bed6ec15aa2)
--------------------------------------------------------------
![image](https://github.com/staxrip/staxrip/assets/37181988/b0a2722b-803e-4103-b1aa-95b6e8147f1c)

which removes the black bars automatically, and then add job like normal and start encoding, when the job is started Staxrip can analyzes and auto crop like the feature which is in the current version and start encoding.
it ll be cool if u can save the settings in template too so that u can just import different source file without having to set auto crop each time.

**Comment by Dendraspis** [comment]
🤔   I have re-read your request and I'm not sure anymore that we have the same idea in mind.

So you want to be able to enable Auto-Crop, that is automatically started when the job is started? Is that what you meant?

**Comment by Dendraspis** [comment]
Okay, so in case you want an auto-crop directly after loading a source file, this is the way to go:
`Tools » Advanced » Event Command` and then:
![image](https://github.com/staxrip/staxrip/assets/50659978/9a097b07-a9fe-446a-a2bb-f901477dac4b)

Unfortunately in `StaxRip v2.25` (and prior) there is a bug, that the auto-crop will be calculated, but the `Crop`-filter is not enabled. That has to be done manually or by opening and closing the Crop window. This will be fixed in `StaxRip v2.26` that is coming next.

So I close this one for now...

**Comment by Dendraspis** [comment]
💡   Sorry, totally forgot to mention the most obvious solution:
Enable the Crop-filter before you open a file will auto-crop it after loading.
