### ISSUE TITLE
Denoise TemporalDegrain2 crashes on StaxRip-v2.25.0-x64

### ISSUE THREAD

**Issue by craposoup** [staxrip/staxrip#1066]
StaxRip-v2.25.0-x64 still hangs and trows and error after selecting Noise > TemporalDegrain2

![image](https://github.com/staxrip/staxrip/assets/49623148/ae1a5587-e1e5-4547-a09e-8f9478ddb740)

**Comment by Dendraspis** [comment]
Duplicate: #1056 

Is it possible you don't use fresh/clean settings? Do you use old settings, templates or whatsoever from a previous version? Because there is no issue anymore with `TerporalDegrain2`:

![image](https://github.com/staxrip/staxrip/assets/50659978/2e9848df-8361-4426-a585-c46d65393695)

Use a clean extracted copy of StaxRip with a new settings folder and it will work:

**Comment by craposoup** [comment]
I do not use any templates or saved settings, I always extract and launch from a new folder, this I do for all versions.

I'm suspecting some compatibility again, but this never worked for me in any versions that was installed clean.

**Comment by Dendraspis** [comment]
What CPU are you using?

**Comment by craposoup** [comment]
![image](https://github.com/staxrip/staxrip/assets/49623148/2e81f0dc-3a9d-44ab-9de3-94bf65108008)

**Comment by Dendraspis** [comment]
Ah, of course, you've already mentioned it here:  https://github.com/staxrip/staxrip/issues/1035#issuecomment-1648311680

So the reason is the same as it was last time:
`TemporanDegrain2` calls, depending on source file and chosen parameters different dependencies. And here this is the same issue like with **Plugins_JPSDR.dll** and your CPU - one of them doesn't support AVX2.
Maybe you can play with the `postFFT` parameter, as it changes a lot internally, but from the script you get the dependencies:

```
# Required plugins:                                                                #
# neo_fft3d: https://github.com/HomeOfAviSynthPlusEvolution/neo_FFT3D/releases     #
# MaskTools2: https://github.com/pinterf/masktools/releases                        #
# MVtools2 (mt_*): https://github.com/pinterf/mvtools/releases                     #
# rgTools (RemoveGrain,Repair): https://github.com/pinterf/RgTools/releases        #
```

...and then you have to try to get the non-AVX2 dll's - if available.

I don't think we can add something here, so I close that for now...
