### ISSUE TITLE
Version for Arch Linux / Manjaro Linux

### ISSUE THREAD

**Issue by Helg1980** [staxrip/staxrip#107]
Good afternoon! 
Please make a StaxRip package for ArchLinux / Manjaro Linux. 
I use Manjaro Linux KDE, a very modern and promising operating system.
Thank you in advance!

**Comment by Patman86** [comment]
Hi Helg,
staxrip is designed for windows and i think there will be staxrip package for linux.

**Comment by Helg1980** [comment]
ArchLinux (and in particular Manjaro Linux) is a very serious platform, with many powerful programs, such as Davinci Resolve and others. I think it makes sense to have StaxRip support in this system.

**Comment by Revan654** [comment]
Not possible due to lack of support for certain Visual support from .NetFramework. Already tried to bring it over it's just can't be done with the existing code and allot of changes would have to happen. It also can't run in Wine.

Also tried to Build it through Mono, That also didn't work hit a roadblock since mono doesn't contain everything VisualStudio has.

Then of course there the biggest issue, Linux does not have Avisynth Which the core of StaxRip is built off of. Only VapourSynth would have Support but not sure how much. Then there the issues of GPU Encoders.

Linux lacks certain dll files which are only found on Windows OS. Due to there architecture they will not run on other platforms.

**Comment by Helg1980** [comment]
> Not possible due to lack of support for certain Visual support from .NetFramework. Already tried to bring it over it's just can't be done with the existing code and allot of changes would have to happen. It also can't run in Wine.
> 
> Also tried to Build it through Mono, That also didn't work hit a roadblock since mono doesn't contain everything VisualStudio has.
> 
> Then of course there the biggest issue, Linux does not have Avisynth Which the core of StaxRip is built off of. Only VapourSynth would have Support but not sure how much. Then there the issues of GPU Encoders.
> 
> Linux lacks certain dll files which are only found on Windows OS. Due to there architecture they will not run on other platforms.


Now there is a discussion of errors in Wine:

https://bugs.winehq.org/show_bug.cgi?id=48521
https://bugs.winehq.org/show_bug.cgi?id=48503

**Comment by Revan654** [comment]
It's a bit pointless since Avisynth is required to use StaxRip and does not exist on Linux. Someone did start it but there to much work needed to port everything over, It's why I guess he stopped The bulk of it is written in C++ I believe. Which is whole different beast compared to C# and VB. C++ is used to write C#.
