### ISSUE TITLE
Settings compatibility

### ISSUE THREAD

**Issue by Globefishp** [staxrip/staxrip#1080]
Hi! I'm updating to Staxrip 2.25 from 2.15. But I noticed that the encoder settings from older version is missing in the new version. I try to update the settings folder by copying them and running intermediate version (that is, stepwisely, from 2.15 to 2.20, then 2.21, 2.22, 2.23). Now I find the older settings would not work since 2.23 (which mentioned that in this release some MACRO changed).

Are there any tools or method to make my old settings work? I create many preset (mainly x264 lol) and it's not easy to replicate them in GUI.
Thanks!

**Comment by Dendraspis** [comment]
Hello. This is a big issue for sure. StaxRip supports shared settings from older versions, but due to the implementation, how things work and are saved, it is never recommended. It comes with some very nice advantages, but it also causes issues with missing features or wrong executions and I already think about disabling that behavior. Sadly all settings *have to* be re-made every time you update then.  😕 

So the save way is to open the new and old version simulaniously and copy all needed settings by hand. Sometimes it might be a pain in the ass, but at the same time better not finding out, that something doesn't work as expected.

In case of encoder profiles you can use the `Import Command Line` feature to transfer/set the options before saving them as presets:
![image](https://github.com/staxrip/staxrip/assets/50659978/bd192ab7-8559-4760-82e5-c682c8113f49)

**Comment by Globefishp** [comment]
Thanks for your contribution! Now I am migrating to 2.28.
I hope the new setting files can keep good compatibility longer😁.
