### ISSUE TITLE
A question for the dev

### ISSUE THREAD

**Issue by Adramelramalech** [staxrip/staxrip#109]
First, why did you design this application to use crappy settings? Why is it 1pass at 7k bitrate default and why is it even there? Just to annoy people?
Second, how hard is this? I open stax, make settings, click source, choose source, press next then start. Why would that not apply to this? Why do I have to make templates and why do I have to setup my encodes backwards?
I have two people who claim to use this tell me to select source. For them after they hit source it asks for a template. Mine does not do this. After I hit source I am looking at a job window. How do I get out of that? I click x it asks to save. Save what? I click load and it gets rid of my settings.
I add my settings, then hit source and it does not use my settings.
I hit source and I get no option of settings.
Next version of stax open stax, add settings, add source, next start. Boom, done. Not that hard. But this, this what ever it is is just backwards. Totally backwards.

**Comment by Patman86** [comment]
Hello Adramelramalech,

please remain friendly with your problem description / error analysis. It is known that the documentation for StaxRip is not the best and many important / crucial things are missing. StaxRip was designed as a user interface for a lot of applications that are usually based on pure console input. This GUI is intended to simplify handling with these applications. Therefore, some previous knowledge was required to use SaxRip. The popup for the selection of the template is a matter of setting. Select the tab Tools -> Settings -> General and there you can set your conditions. Check "Show template selection ... or set a" Startup Template ". Documentation is one of the important points that will be worked on next.

**Comment by 44vince44** [comment]
Dear Patman, this user is being very unfriendly and rude, please see number #101 . I have tried to help him out, but he is not making it easy. I couldn't even understand at what level the problem was because he was not making the effort to explain. So I suggest you don't waste your time... I'm sorry to see that people are behaving this way.

**Comment by Adramelramalech** [comment]
behave this way? we are talking about an application that does not work at all and is designed very poorly and backwards. And how did you help? seriously? By telling me to check the obvious? Of course my apps are working and of course AVS is working. I will say it one more time. Nonstop errors. I don't think there's one thing in stax I touch that does not give error. I give stax settings, it does away with my settings and uses it's own crap settings. And how was my post rude? It is not that hard at all what so ever to create an application that you simply just add settings to and simply add a source and simply press start and encode with out jumping through hoops or have it not work.

**Comment by Adramelramalech** [comment]
he's sorry people behave this way, well I am sorry devs don't have a clue

**Comment by Patman86** [comment]
If you want developers and possibly experienced users to help you, some snapshots of your settings or a full log file are helpful. You describe your problems, but not so that they are understandable. There are so many users who use StaxRip and notice some bugs, but none of them use StaxRip, although it is practically unusable like you say. Is it possible to upload your settings file? Have you tested the use of StaxRip with administrator rights? Did you describe your problem in the doom9 forum? I 'm using StaxRip since 2015 with my tempaltes and without any problems.
And if you think: 

> It's not that difficult to build an application by simply adding settings and adding a source and just pressing start and encoding without jumping through frames or getting them to work. 

create your own GUI ...
