### ISSUE TITLE
Issue with avs_libplacebo.dll

### ISSUE THREAD

**Issue by HDCLovers** [staxrip/staxrip#1130]
Script Error

Cannot load file 'C:/Users/Administrator/Documents/StaxRip-v2.29.0-x64/Apps/Plugins/AVS/AVS_LibPlacebo/avs_libplacebo.dll'. Platform returned code 126:
The specified module could not be found.

This error giving when tonemapping a HDR file into SDR with Hable

**Comment by Dendraspis** [comment]
I suggest we wait for the next release that comes with a new version of `avs_libplacebo`.
If you don't want to wait, update it manually from [here](https://github.com/Asd-g/avslibplacebo/releases/tag/1.5.2) and see if the issue is gone.

I guess you've already checked, that you meet the requirements fr that filter, especially the Vulkan GPU?
