### ISSUE TITLE
FFMPEG hardware AV1 support

### ISSUE THREAD

**Issue by Randomblock1** [staxrip/staxrip#1145]
The latest FFmpeg supports fast hardware encoding via AMD AMF (compile with --enable-amf) with certain encoders. So under FFmpeg profiles, there should be an AMD submenu, like VP, Intel, and Nvidia, using h264_amf, hevc_amf, and av1_amf. Additionally, Intel and Nvidia now have hardware AV1 encoders, av1_qsv and av1_nvenc respectively.

Anyway, for now, I'm just using the command line scripting.
`%app:ffmpeg% -i "%source_file%" -c:v av1_amf -c:a copy -quality quality -rc 4 -map_metadata 0 "%encoder_out_file%"`

**Comment by scweeny** [comment]
This is something I have already requested.
The producer responded that it will be added in version 2.30.0. The problem is, I don't know when it will be distributed.

https://github.com/staxrip/staxrip/issues/1117

**Comment by Dendraspis** [comment]
I'll try to implement it for the next release that should be released before Christmas, depending how easy or time consuming it is.

**Comment by Dendraspis** [comment]
Because I don't have an AMD graphics card, I get the error:
`[av1_amf @ 00000202bb85dd40] DLL amfrt64.dll failed to open`

But it looks like it works up to this point. If there are still issues, please report the problem by re-opening this issue.

![image](https://github.com/staxrip/staxrip/assets/50659978/32eed3cc-bc68-46fe-b4b2-e902378fc7fb)
