### ISSUE TITLE
Request for Audio Volume Change

### ISSUE THREAD

**Issue by VEGAX265** [staxrip/staxrip#119]
Been using Staxrip for years and loving it.  I recently found a few files that required me to raise the input volume on the audio tracks.  I searched the online documents for Staxrip and that lead me to the  ffmpeg app.  I used the volume multiplier option in ffmpeg to get the job done.
I had to extract and then merge the fixed audio back in before I could run Staxrip.  If possible I would love to see a volume option added to Staxrips audio menu settings page.  So it could run automatically before any normalization is done.

Please correct me if its already in Staxrip and Im just missing it.  I alway use the normalization to get rid of high and low volumes, so I dont have to keep fideling with the tvs remote.  I also tried adjusting the gain in Staxrip but that just made horrible noise.  

Either way Thanks.

**Comment by Patman86** [comment]
Hi VEGA,

look here:

![grafik](https://user-images.githubusercontent.com/54327252/75814267-c1209300-5d91-11ea-9431-c3d54ebb67b4.png)

click on more

![grafik](https://user-images.githubusercontent.com/54327252/75814442-0ba20f80-5d92-11ea-8134-22c949c5b94a.png)

here you can select between 3 normalization modes. I hope that's what you are looking for.

**Comment by VEGAX265** [comment]
Hi Patman,

I have always used the defualts and volumedetect.
Im not really sure what any of these setting do as I thought normalization only dropped peaks and raised valleys.
Is that a wrong assumption?

Do you know if the dynaudnorm screens settings apply to the other two methods?

**Comment by 44vince44** [comment]
Hi Vega, I'll try to help, so first here is some general knowledge about audio dynamics:

1) traditional normalization does NOT drop peaks and raise valleys. It sets the peak to maximum of the dynamic range, meaning that if the recording's higher peak is not at the maximum, it raises it to the max, and it raises the valleys by the exact same factor. So it will not give you what you want. Let's say, if you have one single EXTREMELY LOUD moment in the whole film, and the rest is VERY QUIET, you won't be able to correct the difference by using traditional normalization.
 
2) traditional dynamic compression is the feature that makes peaks lower and valleys highers. There are many techniques used for achieving that, and it is used very much in audio mastering of songs, so you get a loud sound. But it is not used in films and not in classical music, because traditional dynamic compression gives more loudness, but reduces dynamics which are much required in films and classical music. Usually, when applying dynamic compression, you talk about threshold, max, and ratio, or threshold, gain and range.

Now AC3 encoding with ffmpeg gives you two options of dynamic compression, but they are different from traditional dynamic compression. The default "volumedetect" does not apply dynamic compression, so you need to choose one of the following two methods.

A) Loudnorm:
Select ffmpeg for compression, select method "loudnorm".
Integrated = -24 -> keep or set to -18
True peak - -2, leave as is
LRA = 7, leave as is

You can read more at [ffmpegs's loudnorm documentation](http://ffmpeg.org/ffmpeg-filters.html#loudnorm)

B) Dynaudnorm:
Select ffmpeg for compression, select method "dynaudio" then go in the dynaudio settings.
Try this :
Frame length = 500
Gauss filter win = 31
Target peak = 0.95
Max gain factor = 10 -> change to 20 for very low volume recordings
Target RMS = 0
Compress factor = 0
Enable channel coupling => YES (if you don't set yes, the channels will be out of balance)

If you get good results, or almost good results, tweak the "max gain factor"  by steps of 3 (because those are decibels, you won't hear a difference for a step of 1).

If you still don't get any results, you can try to change the value of "compress factor", which will activate traditional dynamic compression, They say smaller parameters result in stronger compression. Meaning you have to try a value of 24 to begin (values are between o and 30). If compression is not enough, set to 18. 

You can read more at [ffmpeg's doc of dynaudnorm](http://ffmpeg.org/ffmpeg-filters.html#dynaudnorm)

-----------------
Now, I personally never tamper with the 5.1 or more channel audio streams. I prefer to activate the "Night mode" on my amplifier, it doesn't doesn't solve the problem, but helps.

**Comment by Patman86** [comment]
Hello vince,

Thanks for your explanation. So far I haven't had time to explain ffmpeg's methods, but the ffmpeg documentation is good on this.

**Comment by 44vince44** [comment]
Yes I agree with you Patman, dynaudionorm seems to be the best choice. 
To Vega, if my explanation is a bit confusing, here are some straight forward instructions you can try:

1) set the encoder to ffmpeg, codec AC3
2) do not forget to check "Normalize"
3) after pressing the More button, in ffmpeg select Normalize Method button = "Dynaudionorm"
4) in the droplist below ffmpeg, click on dynaudionorm, check "Enable Channels Coupling" !!!
5) If after a test encode, the loudness is not enough, try with setting "Max Gain Factor" = 20
6) If not enough, but better, increase "Max Gain factor" to 23 or 26 and so on
7) If really far from enough, Set "Max Gain Factor" to 20 and "Compress Factor" to 20

I'd like to know what results you got with that!

**Comment by VEGAX265** [comment]
Thanks for the advice,
I will play with the settings suggested and get back to you.
I just got bogged with work so I dont have time to work on my encodes right now.  may be a few days before I can test.  

I will report back asap.

**Comment by VEGAX265** [comment]
I tried increasing Max Gain to 20 and that did the trick for me.  Thank you.

I will also try the "loudnorm" audio settings when I get some more time to see if I can see any differences.

Does it matter if I process a file that I already ran volume detect normalization on?

**Comment by 44vince44** [comment]
Ah nice to see that it worked !

> Does it matter if I process a file that I already ran volume detect normalization on?

I think the is no problem at all.

**Comment by VEGAX265** [comment]
I had some time so I did some more playing with the max gain level.  I bumped it up to 32 but nothing changed when I ran the volume detect on the out put file.  Is that normal?
Also I wanted to know what the Integrated value is on the second picture in this post.  Does it apply to Dynaudionorm or just Loudnorm?   Is volumedetect a valid way to get the decibel value for an audio file?

**Comment by 44vince44** [comment]
@VEGAX265 
- "Volumedetect" is only the name of the basic normalizing method, that detects maximum peak and shifts the whole waveforms by the same factor so the maximum peak is set to maximum allowed amplitude. Volumedetect has no parameters at all (so it does not use any of the params you se below it). Volumedetect does NOT detect a peak and store the value somewhere. It detects the peak and, at the end of the pass, shifts the whole waveforms according to the peak detected. "Max Gain Factor" does not work with the Volumedetect method because it is a parameter of DynAudioNorm method.
- "Integrated", "True Peak" and "LRA" apply ONLY to "loudnorm"

**Comment by 44vince44** [comment]
@VEGAX265 @stax76 please close this thread since it can be considered not an issue, and action has been taken in 2.0.8.11

**Comment by VEGAX265** [comment]
Thanks for the great program and the help.
