### ISSUE TITLE
How to convert a MKV to h264 MP4?

### ISSUE THREAD

**Issue by soulfulkhani** [staxrip/staxrip#1193]
can someone please guide me here i am new to staxrip. everytime i open file it start the demux

**Comment by Dendraspis** [comment]
Please visit our [Discord server](https://discord.gg/uz8pVR79Bd) (preferred), the *Discussions* section here on GitHub or another place for such basic questions.

Here a quote from the Readme:
***StaxRip is no One-Click Encoder!***  
StaxRip is capable of performing a wide variety of jobs for video/audio processing. To unleash its full power, users are required to know what they want to achieve and how to set up StaxRip to meet their needs.
If you are a first-time user, it is especially strongly recommended that you learn the basics referring to the documents and do some tests to understand how StaxRip works and what you can achieve with it. However, StaxRip also provides an 'Assistant' feature that will guide you through your jobs step by step so that you can start more easily and prevent mistakes.

Just very short answer:
- *Demuxing* is a basic part of opening a source file. You can adjust it in the Options.
- Click on the red circled labels to change the encoder and container.



![image](https://github.com/staxrip/staxrip/assets/50659978/4206bed8-1e3e-4075-88ad-9cd1ff7f38fe)

**Comment by soulfulkhani** [comment]
thanksss
