### ISSUE TITLE
File name parsing is broken.

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#1220]
Parsing file names are completely broken now.

For example having a subtitle named
movie.[French]{France}.srt
is not parsed correctly for the language and the track name. It takes it as English and no name. It worked before.

I'm very frustrated. It's ok to have new features and if they are broken. But more and more old working features are broken.
These all worked before. Now I'm truly scared to install any new version of staxrip.

This is the second feature I find broken that worked before.
2.35

**Comment by Dendraspis** [comment]
That can sadly happen with such complex procedures and (almost) no testers. When I have tested the subtitle name and language parsing it worked, at least for the language names I used.

Not sure why `French` is not accepted, but using
`movie.[fr-FR]{France}.srt`
should work. Maybe there are too many *French* languages....

**Comment by Dendraspis** [comment]
Okay, so it would have worked for `movie_{French]{France}` as this is what StaxRip would extract, but I improved it a bit so it will also check for the part without `_`.

Should be available in the next version....

**Comment by Zodler** [comment]
Ok I did several tests and maybe I didn't follow the convention naming correctly. I didn't know you should use [fr] to get French.

However {} still doesn't work. Anything you put in the accolade should go into the track name.
movie.[fr]{France}
should set the track language to French and track name to France.

Right now it is not reading what is inside {}.

Unless you use another symbol to set the track name.

**Comment by Dendraspis** [comment]
Here we run into another settlement - and yes, totally forget to take care of the track name part of my example while focusing on the language.  🙄 

I think it has always been that way, that there must be a *space* before `{`, probably to avoid issues with `{` being part of the file name, so that's way it doesn't work for you. With a *space* it looks like this:
![image](https://github.com/staxrip/staxrip/assets/50659978/49d0cb16-cd06-4348-bbd7-70ba5f90dca1)

The problem with extracting names from file names is, that there will always be situations, where the given solution does not work unless we choose patterns, that have almost no chance to become a regular part of a file name, for example:
`movie.[fr-FR]{{%$(France)$%}}`

Nevertheless I have modified it a bit and it will start parsing the track name from the first `{` in the file name without requiring a leading *space*.

**Comment by Zodler** [comment]
Thank you. It all works now. I now put a space before {

**Comment by Zodler** [comment]
staxrip 2.35.8

movie_[fr-CA]{Canada}.srt
only fr-CA is parsed not Canada name
movie_[fr-CA] {Canada}.srt  (with space works)

----------------------------------------------------

movie_[fr-CA]{Canada}_DELAY 1000ms.aac
[fr-CA] is **not** parsed (unlike subtitle) but Canada name is set (unlike subtitle again)

so the parsing for subtitles and audio do not match! Are they 2 different functions?!

**Comment by Dendraspis** [comment]
`v2.35.8` is a hotfix for the *_DELAY-DoVi* issue, that does **not** include any other changes.

> so the parsing for subtitles and audio do not match! Are they 2 different functions?!

Up to `v2.35.8` they were indeed different.

**Comment by Zodler** [comment]
They will be the same in the future releases?

**Comment by Dendraspis** [comment]
The extraction part itself yes, but there are still differences when it comes to metadata, so the read out language could be used instead - depending on the audio or subtitle file.

**Comment by Zodler** [comment]
Just a question. Can we currently pass the Gain level in an audio file name?

**Comment by Dendraspis** [comment]
As far as I remember no, because `GAIN` is not a property that is or can be extracted. 
But we should stick to the topic.  😅

**Comment by Zodler** [comment]
It's still about parsing! 😄
