### ISSUE TITLE
VapourSynth fails to initialize : it's due to python/vapoursynth installed over older versions

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#127]
I got Fail to Initialize Vapoursynth message, but StaxRip apps seem all OK (no errors in apps manager). Any idea what it can be?
-updated to VC Runtimes
-VapourSynth is v48

StaxRip says all is OK!

With any file, and defaults of 2.0.7.7 i have the message VapourSynth fails to initialize.
On previous versions of Staxrip, it crashes!

When I opened Windows Settings/Apps I saw many versions of Python!

**SOLUTION : uninstall all versions of Python, and Vapoursynth, then reinstall Python 3.7.6 and VapourSynth 48.** The problem was fixed.

@stax76 : maybe a note or warning in Runtimes/Python saying that it's better to uninstall all (previous) versions of python, because they sometimes remain.

**Comment by stax76** [comment]
I don't want to add something like this to the code because it degrades performance in both the developer experience and the user runtime, the general policy for the app description is to have a description as short as possible. I hope that I can write a good documentation this or next year but I don't know if people can be warned from everything. It's a good general rule to always deinstall an old version before installing a new version of any kind of software, many programmers don't think about such things or mess things up accidentally or are simply too lazy, me belonging to the last.
