### ISSUE TITLE
Batch Job Processing asking to SAVE PROJECT before starting the next Job

### ISSUE THREAD

**Issue by noblemd00** [staxrip/staxrip#1287]
**Describe the bug**
Batch Job Processing asking to SAVE PROJECT before starting the next Job interrupting completion of the batch.

**Expected behavior**
Asking to SAVE PROJECT should not interrupt Batch Processing. Batch Processing should complete without interruption.

**How to reproduce the issue**

Add multiple File Batch Source files - process (adding multiple Jobs to the queue does not cause the same issue).

<img width="298" alt="240328 110623" src="https://github.com/staxrip/staxrip/assets/16325865/0e3fd43d-abda-4d6b-97e2-03849d44ea40">

<img width="62" alt="240328 110748" src="https://github.com/staxrip/staxrip/assets/16325865/1e40edde-fc01-4bab-972c-53875f766a37">

**Comment by Dendraspis** [comment]
It seems I need a more detailed explanation, because I can't reproduce this issue.

I started StaxRip, chose `File Batch` and `Add Files` to add two files. Both were added to the `Jobs List` and I hit `Start`. The first one proceeded and when it finished, the second one started without and questions.

Can you check if that also happens to you with fresh settings?
For testing I recommend closing StaxRip and rename the `Settings` folder you've chosen, so your entire settings and jobs list are saved. A new `Settings` folder will be created with new settings. Choose fast encoder settings like `CRF40` and `UltraFast` profile for fast processing to verify this issue persists.
Afterwards you can delete the new `Settings` folder and rename the old one back if you want.

**Comment by noblemd00** [comment]
I have an Event Command to add the reencode resolution (960p, 720p etc.) to the target name which always worked properly before. When I disable the Event Command the asking to SAVE PROJECT no longer occurs so, it must be related to the event command.

**Comment by Dendraspis** [comment]
Some details about the event please.
When does it add that and how?

**Comment by Dendraspis** [comment]
Could be improved with `v2.37.5`, but still not reproducible. 
And because of no answer, I'll close it for now...
