### ISSUE TITLE
Add hardcoded subtitle option and ctrl+h doesn't work

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [staxrip/staxrip#1309]
**Describe the bug**
pressing ctrl+h or going to tools --> advanced --> Add hardcoded subtitle doesn't do any thing
![image](https://github.com/staxrip/staxrip/assets/7858946/8b13ba1d-89da-4483-ac6d-6502bc99f7ee)

**Expected behavior**
it should open a dialog to allow me to select a subtitle file

**How to reproduce the issue**
download latest version v2.37.6 (i started noticing it in the lastest 2 or 3 updates)
start the app and choose "Roaming" to store your settings
add any video
try to add subtitle to it

**Comment by Dendraspis** [comment]
Please have a look at #1281.

**Comment by ahmed-abdelrazek** [comment]
> Please have a look at #1281.

removed everything in Roaming\StaxRip except for Templates and it works now 
thanks

**Comment by Dendraspis** [comment]
Because of that I recommend using the first setting option to store the settings in the `.\Settings` subfolder instead of using the other options.

The way settings are stored has it advantages and disadvantages, sadly this is one of them. Please be careful when you upgrade the main version, meaning for example `v2.37.x` » `v2.38.x`, because some settings could break when you use old ones.
