### ISSUE TITLE
Cropped Video but uncropped DV

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1321]
Hi,

I've got a question. I hope it's not duplicated or anything.

I have a 4K video, that is cropped 3840x1600
I dropped the video into Staxrip and to my surprise, it says that the encode needs 280x280 cropping. Which it doesn't.

I used dovi_tool to create DV rpu with and without the -c switch and the results are different. The L5 data has 280x280 crop in it.

So I understood that the video is cropped but the DV is not. Somehow they work well.

Now my questions is how is the proper way to encode this video?

1- Go as normal in Staxrip, just uncheck the cropping filter
2- use dovi_tool with -c switch to create a cropped DV, uncheck the cropping filter and modify the L5 data to 0x0 cropping. 

Thank you

**Comment by Dendraspis** [comment]
Hi,

so for my understanding:
The source file is `3840x1600` and the metadata in it has 280/280px crop. Is that correct?

**Comment by LazyNCoder** [comment]
That's right. As if the DV is made for 3840x2160 but 280x280px of it being ignored.

**Comment by Dendraspis** [comment]
In that case you should extract it with `dovi_tool` using the `--crop` paramater, then StaxRip also won't crop the video anymore.
You can name it like the source file and place it next to it, so StaxRip should be able to take it directly when opening the source file.

Editing the `_L5.json` file only won't work properly, because you don't crop the video.

**Comment by Dendraspis** [comment]
StaxRip needs it for calculations and it will be created automatically.
