### ISSUE TITLE
Crop after Resize

### ISSUE THREAD

**Issue by Zodler** [staxrip/staxrip#1332]
We need a better mechanism for cropping. Right now it's impossible to put crop after resize.

Even if you enter it manually and as a fixed value, it is not going to work correctly.

Sometimes you want to resize 4K to 2K and crop after. Depending on your device like Amlogic you might need mod 8 images and need to leave black bars. Cropping after resize would be the right thing to do.

**Comment by Zodler** [comment]
I already explained. Because of Amlogic devices, I need to have mod 8 videos.

It is easier to crop 8 after resize but I have not thought about calculating how to crop before resize.

Maybe the original 1080p should be cropped to mod 16? After resize to 720p it will be mod 8 already?

**Comment by Dendraspis** [comment]
Cropping and then resizing is the proper way.

To achieve Mod8 results, just choose a Mod16 crop and when you resize 4K to 2K, meaning to 50%, you get a Mod8 video.
Otherwise you can crop manually with hard coded values which will work as long as you take care of some limitations, for example Mod2 cropping.
