### ISSUE TITLE
Add SVT-AV1-PSY Support

### ISSUE THREAD

**Issue by gianni-rosato** [staxrip/staxrip#1353]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem.

**Describe the solution you'd like**
Staxrip already supports the SVT-AV1 encoder, which is fast & parallelizable. Recently, there has been an effort to meaningfully improve SVT-AV1 for perceptual fidelity with [SVT-AV1-PSY](https://github.com/gianni-rosato). SVT-AV1-PSY is a fork of SVT-AV1 with a plethora of meaningful feature additions, and it is a superset of SVT-AV1 so any pre-existing commands & workflows for the mainline encoder work with PSY.

**Describe alternatives you've considered**
There aren't any compelling alternatives to SVT-AV1-PSY except for mainline SVT-AV1. An alternative to adding SVT-AV1-PSY as its own encoding option would be to replace mainline SVT-AV1 with PSY, as it is a superset of SVT-AV1's encoding capabilities & users would not face any regressions.

**Explain why the feature matters to you**
Mainline SVT-AV1 development is aligned with improving average metric stores on metrics like PSNR, SSIM, & VMAF. This doesn't always align with what our eyes want, and even more advanced metrics like SSIMULACRA2 have a tough time trying to articulate our visual preferences. SVT-AV1-PSY is rigorously tested and improved for perceptual fidelity, and provides consistently better-looking encodes than SVT-AV1.

**Additional context**
I am the maintainer of the SVT-AV1-PSY project, so if you have any questions about the project not covered in its README please ask me. I have rolled it out in my Aviator encoding GUI for Linux with zero issues, and I received positive feedback following this effort. Staxrip is a really cool project, and I'd love to be able to combine our efforts to bring maximum AV1 encoding fidelity to everyone; I would be committed to addressing any needs or concerns Staxrip has when it comes to adopting our encoder given this feature request is seriously considered. I hope we can work something out here!

**Comment by pat-e** [comment]
It is already included since v.2.38.
For the Exe itself: I suggest using the EXE - version from https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases because this version includes the "dovi-support" and either replace the included "svtav1encapp.exe" with the one from 
SVT-AV1-PSY-EncApp-v2.0.0-6+4-2f76e9a8-.Mod-by-Patman.-x64-msvc1939.7z or go to the "apps-settings" and change the path of the svtav1encapp - exe to your own version.

Be aware, that implementation does not include the newest v2.0.0-A, only the v2.0.0 without the A

Best regards,

**Comment by Dendraspis** [comment]
As you might already found out, `SVT-AV1-PSY` is already supported since `v2.38.0`.  😉 

It was also considered to be delivered with StaxRip, but we were unfortunately not able to get a proper build. Meanwhile your releases include the builds as well, which is pretty nice, but they still lack the advertised Dolby Vision support. 

Fortunately @Patman86  is now able to build a proper build with all features, so `SVT-AV1-PSY v2.0.0` is already included and will be delivered with `StaxRip v2.39.0` in a couple of days, but I'm not sure if the latest changes will be included.

Regardless what is delivered with StaxRip, you can always replace the encoders with a version of your choice. New or changed parameters can mostly be added via the `Custom` section.

**Comment by gianni-rosato** [comment]
Gotcha. I did discover it was already supported, and I was hoping for first-class support, and it looks like that's where we're headed! Very exciting!

**Comment by Dendraspis** [comment]
I guess I can close this one....

Hope I have implemented everything right. Have fun.
