### ISSUE TITLE
Error during GPU encoding

### ISSUE THREAD

**Issue by thegrunge36** [staxrip/staxrip#1368]
**Describe the bug**
I'm trying to encode a movie using GPU and I have an error after the first pass.

**Expected behavior**
I don't know if it's related to the encoding parameters used.

**Provide information**

- Used StaxRip version v2.39.1

[Tron Legacy (2010) Open Matte INTERNAL MULTi 2160p 10bit HDR DV HDR10+ DTS-HD MA 7.1_new_staxrip.log](https://github.com/staxrip/staxrip/files/15448444/Tron.Legacy.2010.Open.Matte.INTERNAL.MULTi.2160p.10bit.HDR.DV.HDR10%2B.DTS-HD.MA.7.1_new_staxrip.log)

**Comment by thegrunge36** [comment]
I tried with another film, and it seems to work

**Comment by Dendraspis** [comment]
To be precise:  The encoding ended without a problem.

Due to the fact, that the first of two attachments had no file extension, this caused `mkvmerge` to not know what it is.

So in your case you have to remove that attachment or rename it to for example `cover2.jpg` and re-add it to the container.

**Comment by thegrunge36** [comment]
I'm not sure I understand what you mean basically the movie is alone, it's Staxrip who created the cover etc.

**Comment by Dendraspis** [comment]
> basically the movie is alone

Definitely not. It includes `1` video track, `4` audio tracks, `7` subtitles, `2` attachments and chapters.

> it's Staxrip who created the cover

Not really, it demuxed the attachments as you set it up, and when you look into the log file you will see, that there are two attachments included in that file:

```
Attachment ID 1: type 'image/jpeg', size 212206 bytes, file name 'cover'
Attachment ID 2: type 'image/jpeg', size 131687 bytes, file name 'cover.jpg'
```

Whoever put the first file in forgot to set the extension - or did it on purpose?!

In my previous post I explained how you can solve it without re-encoding the video...

**Comment by thegrunge36** [comment]
It's strange, in the folder I only have 1 cover file named cover.jpeg. How do we replay the mix once the file is renamed without having to re-encode?

**Comment by Dendraspis** [comment]
Basically you can load the project, check the `Container Options » Attachments` and then add the job - when asked because of the existing encode, choose `Re-use` and it should work.

You can also open `CMD` and enter the command that is listed in the log file in the `Muxing to MKV` section, but without the last part:
`--ui-language en --attachment-name  --attach-file "C:\Users\Jonathan\Videos\Tron Legacy (2010) Open Matte INTERNAL MULTi 2160p 10bit HDR DV HDR10+ DTS-HD MA 7.1_temp\Tron Legacy (2010) Open Matte INTERNAL MULTi 2160p 10bit HDR DV HDR10+ DTS-HD MA 7.1_attachment_"`
You could also rename that file to `cover2.jpg` and then change the file path to add it as well.
