### ISSUE TITLE
Not able to open deinterlaced avi files, getting error

### ISSUE THREAD

**Issue by craposoup** [staxrip/staxrip#1425]
Not able to open .avi files deinterlaced from source .vob or .mpeg files, getting the below error, this never happened in previous versions.

Able to open the .avi with VLC media player, but not Windows media player

![image](https://github.com/staxrip/staxrip/assets/49623148/1e480adb-b095-4949-bc93-44a4664e4504)

**Comment by Dendraspis** [comment]
Without providing any information about the encode, I can't say much except that it should be OS related. Maybe you should update your codecs.

**Comment by craposoup** [comment]
QTGMC deinterlaced

Source: .mpeg (Dvd)
output: .avi

![image](https://github.com/staxrip/staxrip/assets/49623148/38d70985-7bc1-4229-a27c-ed7423a5879b)

**Comment by Dendraspis** [comment]
Can't reproduce it, especially with that information.
The only reason should be the updated and used `ffmpeg` version since `v2.41`. I guess they have updated some related libraries so Windows has to be updated as well. Not 100% sure about that, but definitely tool related.

You can try to replace `ffmpeg.exe` with the one from an older StaxRip version and check if that makes a difference for you.
