### ISSUE TITLE
AssumeFPS() doesn't affect audios (nor subtitles?)

### ISSUE THREAD

**Issue by Pierrounator** [staxrip/staxrip#1430]
**Describe the bug**
Hi, I used `AssumeFPS()` to change FPS of a file from 25fps to 24000/1001. I specifically not used `Copy/Mux` to be sure the audio would be encoded too.
When I opened the new encoded audio in Audacity, I realized it was not affected by `AssumeFPS()`, so it's still in 25fps.

**Expected behavior**
I thought audios and subtitles would be affected by `AssumeFPS()` which would make sense to me.

**Comment by Andrasolin** [comment]
try this - avisynth - ChangeFPS

**Comment by Dendraspis** [comment]
`AssumeFPS` does what the names means: It overrides the FPS to be whatever you choose. In order to change the frame rate, you have to use `ChangeFPS`, `ConvertFPS` or so.

**Comment by Pierrounator** [comment]
I think you don't get the point… I wanted to use `AssumeFPS()` to make my video longer.
But the audio isn't longer when it should be affected too.

**Comment by Andrasolin** [comment]
if I remember correctly, then AssumeFPS can only do 2xFPS or Original-FPS as 'progressive' (de/interlace)

**Comment by Dendraspis** [comment]
Ah, now I get it.

The stretching or shrinking of audio and subtitle tracks is not supported. It's also something, that should be avoided as it can create issues.

In order to make it work, you could also try out loading the audio sources into the frame server and let it handle the stretching/shrinking, but I would recommend using an audio editing app, that have better possibilities to create a proper outcome.

In your case the difference is pretty small, so you could `eac3to` on the audio file and use the `-23.976` or `-changeTo23.976` parameters to adjust/fix the length. But currently there is nothing out of the box for your issue.

**Comment by Pierrounator** [comment]
Oh ok
Yeah I used ffmpeg to stretch the audio because I don't really care about the original audio. I just wanted to let you know that in case it was a bug or not.
Thank you for the answer
