### ISSUE TITLE
Some minor bugs / v2.42

### ISSUE THREAD

**Issue by LazyNCoder** [staxrip/staxrip#1470]
Hi,

These bugs are so minor I didn't even want to report. But I did any way.
I know this is not professional but I just couldn't open different topics for these things.

1- Time feature in crop window doesn't work any more. Shows nothing. it's just blank.

2- I applied "system colors" theme but nevertheless, the title bar of the window is always black(other themes are like this as well).

3- crop settings sometimes act funny. Like in my case, I set the luminance to 2% or below and the crop doesn't work(using crop window). (using frame range: complete and fixed 600 frames. it also doesn't work below 5% with time interval: 15) 

4- if you try to close crop window while it's working(or press esc), it just doesn't care and continue to do what it does. The frame gets frozen of course. 

Is there any documents about new crop features? Like how this luminance threshold actually works? Also, is manual threshold is based on frame numbers right? it's not time based. 

Sorry i've written all this in hurry. I'll update this thread if I find anything new. I'm still trying to recreate my preset.

Thank you @Dendraspis very much for all you do. You're doing a noble job.
Please update Staxrip more often 🥲

**Comment by Dendraspis** [comment]
Hi,

ok, so I agree that it would be a bit overkill to open one ticket per issue or question, that are soooo minor and belong together.

1. Confirmed.
2. Confirmed. *Reminder to myself: Delete "System Colors" and punish users who use them!*  
3. This is because the black bars are most often gray-ish. I would keep it at default 10% as even 8% is sometimes to low. 
4. You mean when AutoCrop is running?

Addition to (3):
The idea for this feature came up when AutoCrop did not crop the entire black bar. As it turned out sometimes colors from the actual image fade into the black bars.

> Is there any documents about new crop features?

Nope.  😬   But it should be self-explaining...

> Like how this luminance threshold actually works?

Very simple:  Every line, that is not brighter than this luminance threshold is considered to be a line, that can be cropped. 

> Also, is manual threshold is based on frame numbers right?

Yes. Unless you don't have a good reason to set it manually I would recommend leaving it on *Automatic*.

**Comment by LazyNCoder** [comment]
> 4\. You mean when AutoCrop is running?

Not autocrop, but the crop window/tool. when it is working, pressing esc or trying to close the window won't help.
You still have to sit through the process.

**Comment by Dendraspis** [comment]
So what do you mean by "working"?
I do not experience any delay or "working" when I don't use (and wait for) AutoCrop.  😕

**Comment by LazyNCoder** [comment]
> So what do you mean by "working"? I do not experience any delay or "working" when I don't use (and wait for) AutoCrop. 😕

I'm sorry if my writings are not clear enough.

When you're on crop window and you press A to "auto crop" and the slider moves to different frames, if you chose like 1000 frames and you want to cancel the process, you can't do that with pressing esc or closing the window. 
It would throw an exception on previous versions but this time the slider just going on. and you have to wait. 

If needed I can upload a video or something.

**Comment by Dendraspis** [comment]
No problem, but it was what I meant:  Auto Crop - not the app/tool/process, but the feature. 😅 

And yes, this sort of feature request would be worth an extra issue.  😁  Can you please open a new issue for that? You don't have to write a lot, it's just about canceling the Auto Crop feature at the Crop window.

**Comment by Dendraspis** [comment]
Issues (1) and (2) should be solved. If you want you can test `v2.42.1-RC1`:
https://ufile.io/njcxbirz

Like mentioned above it would be nice if you could open an new issue for (4).
