### ISSUE TITLE
change style font

### ISSUE THREAD

**Issue by tuktukcima** [staxrip/staxrip#1499]
StaxRip usage questions can be asked here in the Issues section or in the [Discussions section](https://github.com/staxrip/staxrip/discussions).
how change style font with sub srt
![photo_٢٠٢٤-٠٩-٢٩_١٣-١٠-٤٦](https://github.com/user-attachments/assets/0fbd95a4-a860-4a8f-b828-3bface49bc69)

**Comment by Dendraspis** [comment]
You have to check the parameters of the filter/plugin you are using to specify a specific font.

**Comment by AhmedFarag511** [comment]
I can't understand that can you explain?

**Comment by Dendraspis** [comment]
Check the documentation of the filter, that you use for the subtitle.

🤔   I hope you're talking about burning subtitles in....  Otherwise use some external software like `Subtitle Edit` for graphical subtitles or the media player in case of `.srt` subtitles - both has nothing to do with StaxRip (directly).
