### ISSUE TITLE
Hierarchical levels option in SVT-AV1-PSY shipped with StaxRip doesn't work as expected.

### ISSUE THREAD

**Issue by igorbaryshev** [staxrip/staxrip#1546]
**Describe the bug**
Manually set `--hierarchical-levels 4` produces different result from having it left at default when using SVT-AV1-PSY encoder that is shipped with StaxRip v2.42.2. As a matter of a fact, it seems something is either broken whenever it's set to manual or it's broken when left at default, because with any level set manually in options or level 4 set in custom options, the encode runs slower than with default.
The resulting file with default is larger and has a subjectively worse quality result.
![image](https://github.com/user-attachments/assets/90c914bf-2b9f-4c6c-94d7-c74cb2e7bec6)
The file size on this screenshot is not related to the later encode screenshots, but the point still stands.

**Expected behavior**
Expected the default hierarchical levels default and 4 to produce the same result.

**How to reproduce the issue**

1. Use default SvtAv1EncApp profile and compare with same profile but with `--hierarchical-levels 4` in Custom tab of the profile.

**Provide information**
StaxRip v2.42.2

I even updated the encoder to the latest version [SVT-AV1-EncApp-v2.3.0-[Mod-by-Patman]](https://github.com/Patman86/SVT-AV1-Mod-by-Patman/releases/tag/v2.3.0), and it still happens there. 

With custom compiled SVT-AV1-PSY 2.3.0 built using [media-autobuild_suite](https://github.com/m-ab-s/media-autobuild_suite) this does not happen; level 4 produces identical results to default.

If the encoding process screenshots help anything, here they are.
Note: Processor scheduling is set to prioritize background services, so the foreground encoder doesn't take precedence. And both SVT-AV1 jobs were set to Above Normal priority.
![image](https://github.com/user-attachments/assets/37ee2b39-1f08-4893-9648-d0fe04e98c23)

Default encoder v2.2.1 mod by Patman
![image](https://github.com/user-attachments/assets/a6315904-1ff5-491d-8022-262c95bc6ba2)

VS

Custom compiled v2.3.0
![image](https://github.com/user-attachments/assets/4ac9467b-c889-4d88-bbab-ce3146ff105b)

I'm not sure what modifications Patman did to the encoder, but something is wrong.

**Comment by Dendraspis** [comment]
Thanks for the report!  👍 

> Expected the default hierarchical levels default and 4 to produce the same result.

The point is, that it is not the same...

I may have missed it a while ago, but the default value for most presets is `--hierarchical-levels 5` instead of `4`. So when you select the default one in StaxRip it won't pass the parameter to the encoder, means it will use its default value. So the only problem here is that StaxRip shows the wrong value which makes it impossible to select `--hierarchical-levels 4` except via the Custom field.

I will fix that for the next release along with some other issues I have discovered while investigating...

> With custom compiled SVT-AV1-PSY 2.3.0 built using [media-autobuild_suite](https://github.com/m-ab-s/media-autobuild_suite) this does not happen; level 4 produces identical results to default.

Then something might have gone wrong as that should not happen.

**Comment by igorbaryshev** [comment]
Ah, I was almost sure that even at Level 5 it was different, and from test encode it is indeed Level 5 by default on this encoder. 👌

**Comment by igorbaryshev** [comment]
Another issue I've noticed, maybe that's what threw me off when tinkering around.
Priority doesn't seem to be applied, for SvtAv1EncApp and avs2pipemod64 it stays below normal in Task Manager despite having it set to anything else in the encode process window.

**Comment by Dendraspis** [comment]
This is a "normal" behavior as StaxRip can/will only modify the priority of the processes it has started, but in case of a pipe command `cmd.exe` had to be launched to start the pipe, so the `cmd.exe` process including the pipe executable is the only one StaxRip can access, because the encoder is launched by Windows. So in order to change the priority on the fly you have to use the Task Manager or the StaxRip Settings if you want to change it generally.

**Comment by igorbaryshev** [comment]
Understood!
On the note of changing it in StaxRip settings, I noticed priority selection menu order is wrong.
![image](https://github.com/user-attachments/assets/c9057014-17ae-4c97-92a0-24b5a1ca0bc7)

**Comment by Dendraspis** [comment]
😅   It's not "wrong", it's just not in alphabetic order. By default the order represents the values these entries have. As the data type is from the framework it would be possible to find a solution for that, but it will also increase the workload and the potential for bugs. So I don't think it's worth it, especially this setting is set most set max one time with it's recommended setting at `Below Normal`.

**Comment by igorbaryshev** [comment]
Ok, gotcha!
It's indeed not a big deal; I'm just noticing things 🤪

Another thing about priority, I set it to AboveNormal in settings, and SvtAv1EncApp and avs2pipemod64 went up in priority, but only to Normal instead of Above Normal 🤔

**Comment by Dendraspis** [comment]
> It's indeed not a big deal; I'm just noticing things 🤪

And I appreciate it.  😅 

Very interesting. Seems like the priority is somehow capped to `Normal`. Sadly I can't tell how it was a few years ago, because I don't remember using a setting above `Normal`. I think I will check it soon, but I don't think I can do anything about it as StaxRip uses system provided values and the passing definitely works. So it really seems to be capped...

Under normal conditions setting the priority above `Normal` should make absolutely no difference. It just can become useful if you have another encode running or something that needs a lot of CPU power. But in that case the question would be: Why starting the encode at that point or why don't kill/wait for the other process?

**Comment by igorbaryshev** [comment]
> Seems like the priority is somehow capped to `Normal`
Hmm, it looks like it doesn't affect ffmpeg and opusenc audio processes, they are set to the whatever is set in settings and also successfully change on the fly through menu during processing.

**Comment by Dendraspis** [comment]
Depends on how you (have to) launch them.  😅

**Comment by Dendraspis** [comment]
Will be adjusted in `v2.44.0`...
