### ISSUE TITLE
Creating a Flatpak package

### ISSUE THREAD

**Issue by Helg1980** [staxrip/staxrip#155]
Hi Stax,
Is it even possible to start creating a Flatpak?
In previous topics about creating a package for Linux, I realized that certain libraries are missing. I could make requests to developers to add the necessary libraries.
The program is excellent, and as time shows, the trend towards Linux is happening.

**Comment by stax76** [comment]
Linux is not interest of mine, I'm not saying it's bad, it's just nothing for me, I really like many Microsoft products, in fact I'm fascinated by some of them like PowerShell and Windows Terminal, I know PowerShell runs on Linux but Linux folks have their own culture...

**Comment by Helg1980** [comment]
I don't know much about licenses, is it possible to get permission to convert this program to Linux?

**Comment by stax76** [comment]
MIT license is very liberal, somebody asked to clone it and I said it's fine but the name should be different to avoid confusion.

**Comment by megapro17** [comment]
> the trend towards Linux is happening.
What a joke. Linux is made to be run only on servers and virtual machines. It's unusable on desktop.

**Comment by stax76** [comment]
FWIW, my opinion:

powershell is significantly better than any other command language, it's MIT licensed like staxrip and runs on Linux but I assume the Linux community rejects MS products because of historical and ideological reasons. OK there is python but still it's weird they don't have their own decent command language, so even on the command line and the terminal Microsoft is now significantly better.

For me as somebody who spends hours watching YouTube with chrome on 4K screen Linux is probably not usable as I don't think it has stable hardware acceleration. Workaround would be using mpv instead of chrome to watch YouTube videos.

Very high DPI like 288 is broken everywhere except maybe not in Ubuntu, tried it last year.

Portable GUI development is still very difficult, there is Electron and QT and various other solutions but it's not completely simple and there are trade-offs.

For an experienced programmer I guess it's fine and I should probably learn it but for normal users I have doubts.

**Comment by Helg1980** [comment]
Very dissatisfied with Windows, everything works with a delay, despite the fact that powerful hardware is installed. On Linux instant response.

**Comment by megapro17** [comment]
this is absolutely nonsense, windows is much faster than any linux, especially in gui

**Comment by Helg1980** [comment]
> this is absolutely nonsense, windows is much faster than any linux, especially in gui

I don't know what you're talking about. I have two Windows 10 and Manjaro Linux systems installed. On Manjaro, I have a much faster response and performance.

**Comment by megapro17** [comment]
what else do you say, I also installed this ditro, and many others, in all cases windows is much smoother

**Comment by Helg1980** [comment]
> what else do you say, I also installed this ditro, and many others, in all cases windows is much smoother

I don't know where you saw the smoothness in Windows. My personal opinion is that Windows is initially a stillborn system.

**Comment by megapro17** [comment]
> I don't know where you saw the smoothness in Windows. My personal opinion is that Windows is initially a stillborn system.

stillborn system with 80% market share, yeah

**Comment by Helg1980** [comment]
> stillborn system with 80% market share, yeah

everything changes ...

**Comment by Helg1980** [comment]
I have installed Davinci Resolve 16 on Manjaro, everything is flying. The main thing is to enable initially proprietary video card drivers.

**Comment by Helg1980** [comment]
Hi!
Recently, a new version of FFmpeg 4.3 was released, where support for the Vulkan graphical API was implemented for Linux, as well as the transition from AvxSynth to the current fork of AviSynth+.
Is it possible to make a full version for Linux based on these changes?

**Comment by stax76** [comment]
> Is it possible to make a full version of StaxRip for Linux based on these changes? (from a programming point of view).

It does not help.
