### ISSUE TITLE
Files encoded with SVT-AV1-PSY and DoVi support are somewhat broken

### ISSUE THREAD

**Issue by igorbaryshev** [staxrip/staxrip#1553]
When I encode a file that has Dolby Vision support with SVT-AV1, the resulting encoded file gives an error when I try to import it in StaxRip, and also adding that encoded file to HandBrake results in a video that doesn't have Dolby Vision, while Dolby Vision encodes produced by HandBrake itself don't have that problem.
![image](https://github.com/user-attachments/assets/9f93cd10-019f-47f1-beb4-f19b02ee7471)

Also, seems like any mp4 file with DoVi gives an error like this when you try to import it⬇️
![image](https://github.com/user-attachments/assets/0bc9a493-3216-4b88-af44-c62f5daab223)

Though, the encoded file still seems to be having DoVi, as colormatrix reported by mpv is `dolbyvision`

StaxRip 2.42.2
Windows 11 24H2
Ryzen 7 5700X

**Comment by Dendraspis** [comment]
The problem is, that `dovi_tool` is just meant to deal with HEVC and also `ffmpeg` is not able to format the output for `dovi_tool`, just AVC and HEVC are supported.


> while Dolby Vision encodes produced by HandBrake itself don't have that problem.

If your settings are the same, the only reason why this would happen is because `MediaInfo` does not report Dolby Vision data for that source file.

**Comment by Dendraspis** [comment]
The problem is that `dovi_tool` doesn't support AV1 currently, so I don't see a possibility to extract the metadata needed.

But I will check if I can exclude non-HEVC codecs...


> while Dolby Vision encodes produced by HandBrake itself don't have that problem.

The only reason this can happen is when `MediaInfo` tells, that there is no Dolby Vision metadata included.  😕

**Comment by Dendraspis** [comment]
Yeah, StaxRip tries to extract the Dolby Vision metadata which is obviously wrong and it should ignore the Dolby Vision metadata extraction, because it's not supported/possible yet. That's what I have meant by *"I will check if I can exclude non-HEVC codecs"*.

To avoid that error message you have to turn of the extraction manually before loading the source file.

I don't know what other tools do, but `dovi_tool` does not support the extraction from AV1 videos, so there is nothing I can do about it.

**Comment by Dendraspis** [comment]
Non-HEVC files will be ignored with the next release....
