### ISSUE TITLE
StaxRip v2.44.0 - SVT-AV1-PSY v2.3.0 parameters

### ISSUE THREAD

**Issue by BillyBob1354** [staxrip/staxrip#1556]
### == Noise Norm Strength (`--noise-norm-strength`) ==
"noise-norm-strength" default changes to 3 when "tune" is set to 3
https://github.com/gianni-rosato/svt-av1-psy/blob/v2.3.0/Source/Lib/Codec/full_loop.c#L1487-L1490

"noise-norm-strength" can't be set to 0 (disabled) when "tune" is set to 3
https://github.com/gianni-rosato/svt-av1-psy/issues/108
https://github.com/gianni-rosato/svt-av1-psy/issues/108#issuecomment-2555851441
https://github.com/gianni-rosato/svt-av1-psy/blob/v2.3.0/Source/Lib/Codec/full_loop.c#L1487-L1490

### == Debug Presets (`--preset`) ==
Not critical but StaxRip is missing SVT-AV1-PSY's debug presets -2 and -3 (GUI has debug preset -1).

### == Thread Management Parameters ==
**Level Of Parallelism (`--lp`):**
The "Level Of Parallelism" (previously called "Logical Processors") parameter does nothing when I set it (Am I missing something?).
I checked many versions between v2.44.0 and v2.37.5 (version it was first added I believe) and it never seemed to work.
![Screenshot 2024-12-20 161305](https://github.com/user-attachments/assets/0d9726ee-fd91-47e4-baca-83569e4de288)
**Pinned Execution (`--pin`):**
"Pinned Execution" is no longer "0,1" it is now "0-core count of the machine"
https://github.com/gianni-rosato/svt-av1-psy/blob/v2.3.0/Docs/Parameters.md?plain=1#L78

**Target Socket (`--ss`):**
You have the other "thread management parameters" but are missing the "Target Socket" parameter.
https://github.com/gianni-rosato/svt-av1-psy/blob/v2.3.0/Docs/Parameters.md?plain=1#L79
(--ss 0) https://github.com/gianni-rosato/svt-av1-psy/blob/v2.3.0/Docs/Parameters.md?plain=1#L408-L410

**Comment by BillyBob1354** [comment]
**Thread Management Parameters**
There are conflicts on what these parameters do with Parameters.md,  the CLI "--help", and some other places.
I did a few tests and it matched Parameters.md. (manually added `--lp` parameter to the "Custom" field to bypass bug)
![Screenshot 2024-12-20 194056](https://github.com/user-attachments/assets/883ded7b-63d7-4abc-bdd9-a153954cf14a)

**Comment by Dendraspis** [comment]
Thanks for the very detailed report.  👍 

#### `--noise-norm-strength`:
Basicially you are right with what the encoder does internally, but this is internal handling of values. Additionally it doesn't make a difference if you set the value `0` or `3` as they won't make any difference for `--tune 3`. So I won't make any changes to that, even it would look nicer and reflect the internal handling of values, because it might change with every commit and would increase workload on my side.

#### `--preset`:
I have thought about that when making the other changes/fixes for `v2.44`, but at the end they will be only used in very special cases, almost never. So to nicht bloat up the code I decided to keep the default setup, starting from `-1`. In case anybody would like to use `-2` or `-3` it is possible to set the default value (`10`) and add `--preset -3` via the `Custom` field.

#### `--lp`:
Sadly and gladly this is not part of StaxRips implementation. StaxRip can only set the values the user enters and pass them correctly to the encoder. After that the encoder is responsible for what happens next. As far as I know the SVT-AV1-PSY project did not alter that, so it might be related to the original SVT-AV1 project. So if there are issues, you have to contact them.  😕 

#### `--pin`:
Oh, I missed that one. I will change it into a NumEdit with a range of `0`-`24` for the next release.

#### `--ss`:
To be honest when overhauling `SvtAv1EncApp` I thought it would be not necessary. Do you run StaxRip on a system with 2 sockets?

**Comment by BillyBob1354** [comment]
#### `--lp`:
Regarding the `--lp` parameter when set via the GUI, StaxRip is not passing the `--lp` parameter at all.

![Screenshot 2024-12-21 134059](https://github.com/user-attachments/assets/4135f3be-23f5-49be-960f-05cf1d75a6ea)

(works correctly if set via the `custom` field)
![Screenshot 2024-12-21 134309](https://github.com/user-attachments/assets/50295ffb-539d-4b02-8fc2-dcb54232ae9e)


#### `--ss`:
I was just mentioning the `--ss` parameter, I only have a single socket PC.

**Comment by Dendraspis** [comment]
#### `--lp`:
Oh, you're absolutely right, stupid mistake ... will be fixed in the next release as well.  🤦‍♂️ 

#### `--ss`:
It seems the doc mention that there is a difference between specifying it or not. Nevertheless I will add a NumEdit for it as well, so the parameters are complete and you happy.  😅

**Comment by Dendraspis** [comment]
#### `--pin`:
According the the source code this is not to set cores but threads. So I will change it one more time to achieve a range of `0` - *`number of threads`*.
