### ISSUE TITLE
x265 playback issues

### ISSUE THREAD

**Issue by stickz** [staxrip/staxrip#158]
**Describe the bug**
Whenever I try to encode an x265 video with Staxrip it experiences playblack issues in Windows Media Player and Movies and TV. The video freezes for a long burst of time when clicking on the timeline. Other encoders such as Handbrake do not have this same issue. VLC media player works normally. Nvidia H265 does not have this problem. It's specific to the default x265 settings.

**How to reproduce the issue**
My only encoding parameters are  --crf 18 and --range limited. Turning off 10 bit does nothing. I kept everything at default settings for x265, expect turning off 10 bit to test this problem.

Version: StaxRip 2.0.8.0 Stable

**Computer Specifications**
OS: Windows 10 64 bit
CPU: Intel Core i5-8600
GPU: GeForce GTX 1660 Ti 6GB
Ram: DDR4 2400 4x8GB

**Comment by stax76** [comment]
Maybe use a better player, VLC, MPC-BE or mpv.net, it's probably not a bug in staxrip but rather in the windows player and not experienced by other users because most use mpc-be or vlc. I leave this open a while just in case but I don't think anything will happen here. I recommend creating a thread in the videohelp forum.

**Comment by stickz** [comment]
Here's a couple sample video files. The first one was made using staxrip. The second using handbrake. The staxrip one stutters significantly when jumping to different points on the timeline using the Movies and TV App on Windows. My GPU usage spikes to 90%+. The handbrake sample doesn't have this issue. Both were encoded using x265 CRF 18 with the fast preset.

http://85.10.201.195/junk/sample1.mp4
http://85.10.201.195/junk/sample2.mp4

**Comment by Patman86** [comment]
Which x265 do you use? Exchange these with some version from [here](https://www.mediafire.com/folder/arv5xmdqyiczc/x265_by_Patman) or the 3.3+10 version from here. Please test again then.

**Comment by stickz** [comment]
Handbrake builds their own version of x265 into the program. I tried switching the x265 binary in staxrip with the ones you provided. The issue persists regardless of which version is used.

**Comment by Patman86** [comment]
It's not an x265 problem, it's a container problem caused by mp4box. Use ffmpeg to create an MP4 file and everything is fine. I will look for the problem with mp4box.

**Comment by Patman86** [comment]
I have now performed some tests with MP4Box and run through various merge scenarios (different options). Unfortunately, all with the same result ... This case only occurs with the films and TV app from Microsoft and the Windows Media Player, with no other tested player (VLC, MPC-HC, MPC-BE,). Perhaps it is due to the Microsoft CodecPack used or the way in which the files are processed.

**Comment by stickz** [comment]
There is anther similar issue on Nvidia H265 with the ffmpeg mp4 container. It causes sync issues during normal playback on the Movies and TV App. MP4Box doesn't have this problem.

I think these issues are related to how the files are processed. Handbrake is persistent in not experiencing these problems, regardless which video codec is used.

**Comment by Patman86** [comment]
Thanks for the info. I will be testing and reporting. Maybe there is a solution for that 😉

**Comment by stickz** [comment]
Sample 3 is encoded in Nvidia H265 using the ffmpeg mp4 container.
Sample 4 is encoded in Nvidia H265 using the mp4box mp4 container.

http://85.10.201.195/junk/sample3.mp4
http://85.10.201.195/junk/sample4.mp4

This sample is harder to notice. Watch closely in sample 3 from 2:00 to 2:30. Compare to sample 4.

**Comment by Patman86** [comment]
Staxrip usees the following command to mux with ffmpeg:
`$:\StaxRip\Apps\Encoders\ffmpeg\ffmpeg.exe -i videosourcefolder\sample3.h265 -i "audiosourcefolder\sample3 ID1.m4a" -map 0:v -map 1 -c:v copy -c:a copy -y -hide_banner outputfolder\sample3_1.mp4`

I did the same thing from the command line with this command:
`$:\StaxRip\Apps\Encoders\ffmpeg\ffmpeg.exe -i videosourcefolder\sample3.h265 -i "audiosourcefolder\sample3 ID1.m4a" -map 0:v -map 1 -c:v copy -c:a copy -vsync 0 -y -hide_banner outputfolder\sample3_1.mp4` - [Link to file](http://www.mediafire.com/file/0dor7xbkvw4sofi/sample3_1.mp4/file)

and this command:
`$:\StaxRip\Apps\Encoders\ffmpeg\ffmpeg.exe -i videosourcefolder\sample3.h265 -i "audiosourcefolder\sample3 ID1.m4a" -map 0:v -map 1 -c:v copy -c:a copy -async 1 -y -hide_banner outputfolder\sample3_2.mp4` - [Link to file](http://www.mediafire.com/file/9k25lzz352yvq50/sample3_2.mp4/file)

Have a look and give a feedback, because it is really hard to notice the sync issue.

**Comment by stickz** [comment]
Nope, that did nothing. Re-encoding the media just made the problem worse.

**Comment by Patman86** [comment]
Hmm. Maybe someone in doom9 forum can help. I think it is something with the ffmpeg mux method.

**Comment by stickz** [comment]
Could you send me your least build of ffmpeg? I upgraded to 4.2.2 and it resolved this problem.

**Comment by Patman86** [comment]
[StaxRip_Tools](https://www.mediafire.com/folder/vkt2ckzjvt0qf/StaxRip_Tools)

**Comment by stickz** [comment]
Nope, no change between your builds and the default 4.2.2 build.

**Comment by Patman86** [comment]
I did a last test to feel my way. If the result is similar (bad), I ask in the forum. Here are the files:
[sample3_3.mp4](http://www.mediafire.com/file/yrol6x0kfij4a25/sample3_3.mp4/file)
[sample3_4.mp4](http://www.mediafire.com/file/zk5lb5j7fnjcpwj/sample3_4.mp4/file)

**Comment by Patman86** [comment]
stickz have you looked at the last samples?

**Comment by stickz** [comment]
Yeah they didn't change anything.

**Comment by Patman86** [comment]
Thanks for the info. I will ask for a reason/solution and give you a feedback.
