### ISSUE TITLE
AutoAdjust causes sporadically a splitscreen output

### ISSUE THREAD

**Issue by OnbekendHH** [staxrip/staxrip#164]
Wenn Using the AutoAdjust AVSynth+ Plugin, I'm sporadically getting a splitscreen output, especially / for example if I don't use gamma_limit=1.0. Split Screen means: Left Half is unchanged, right half shows the effect that I wish for. I am already using debug_view=false. 

Sample AVS Code (works, but if I remove gamma_limit or set it something other than 1.0, then I get a split screen effect):

```
LoadPlugin("C:\Other Apps\StaxRip\StaxRip-x64-2.1.8.0-beta-merge\Apps\Plugins\AVS\AutoAdjust\AutoAdjust.dll")
LoadPlugin("C:\Other Apps\DGDecNV\DGDecNV_2053.0.0.205\DGDecodeNV.dll")
LoadPlugin("C:\Other Apps\StaxRip\StaxRip-x64-2.1.8.0-beta-merge\Apps\Plugins\AVS\FFT3DFilter\fft3dfilter.dll")
DGSource("D:\StaxRip_Temp\xxx\xxx.dgi", i420 = true)
SetFilterMTMode("DEFAULT_MT_MODE", 2)
ConvertBits(16)
Crop(0, 140, -0, -140)
FFT3DFilter(sigma=1.37135, bt=5, sharpen=0.21135, interlaced=false, ncpu=16)
AutoAdjust(gamma_limit=1.0, scd_threshold=16, gain_mode=1, auto_gain=true, auto_balance=false, Input_tv=true, output_tv=true, use_dither=true, high_quality=true, high_bitdepth=false, asm_opt=3, temporal_radius=48, debug_view=false)
ConvertBits(10, Dither = 1)
Prefetch(16)
```
It would be great if AutoAdjust consistently produced the desired output. 

![2020-04-21 15_33_33-Window](https://user-images.githubusercontent.com/7472445/79872347-fa669e00-83e5-11ea-9dac-d33281cc17c7.png)

**Comment by OnbekendHH** [comment]
Hello Everyone...
I tried posting this issue here (https://forum.doom9.org/showthread.php?t=167573), but it says I do not have rights to do this (even though I have a forum user)... Any ideas where I can post this issue somewhere else?

**Comment by 44vince44** [comment]
@OnbekendHH, 
Hi there, sorry I didn't read you post until now. This is typically a problem of bad handling of high bit video. The problem is with Autoadjust. You have to use stack16 to have it work properly.
Here is the code:

SetFilterMTMode("DEFAULT_MT_MODE", 2)
ConvertBits(16)
Crop(0, 140, -0, -140)
FFT3DFilter(sigma=1.37135, bt=5, sharpen=0.21135, interlaced=false, ncpu=16)
ConvertToStacked()
AutoAdjust(gamma_limit=1.0, scd_threshold=16, gain_mode=1, auto_gain=true, auto_balance=false, Input_tv=true, output_tv=true, use_dither=true, high_quality=true, high_bitdepth=true, asm_opt=3, temporal_radius=48, debug_view=false)
ConvertFromStacked()
ConvertBits(10, Dither = 1)
Prefetch(16) 

Note how before AutoAdjust, you now have the lines ConvertToStacked() and ConvertFromStacked,
and also inside Autoadjust, High_bitdepth must be set to true.
You may now even remove gamma_limit=1.0 and you wont get the screen splitted.
Many filters that have not been updated recently have the same issue.

**Comment by stax76** [comment]
It's not a staxrip issue, is it?

**Comment by 44vince44** [comment]
@stax76 it is not an issue, indeed. It is related to how to use a filter (and read the docs ;-))

**Comment by stax76** [comment]
@44vince44 OK thanks, without you and Patman I would be lost here.

**Comment by 44vince44** [comment]
@stax76 LOOOL, and without you there would be no staxrip ;-))))))))))))))))))))))))))))) Seriously thanks for all the work!!
