### ISSUE TITLE
Separate Update checker for beta version

### ISSUE THREAD

**Issue by Cyberavater** [staxrip/staxrip#167]
It'd be nice to have a separate update frequency for Beta version and automatic in-app updater.

**Comment by stax76** [comment]
It's too much work.

**Comment by Dendraspis** [comment]
Since  #262 beta versions can be included to update checks and you get a changelog as well as the possibility to download the file directly.
An in-app updater is not planned.

If you want to automate an update process or make something more independent, take a look at:
https://github.com/Dendraspis/StaxripBetaDownload
