### ISSUE TITLE
Resume encoding from the point you left before shutdown

### ISSUE THREAD

**Issue by Cyberavater** [staxrip/staxrip#170]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when The file is really big and for some reason, I need to shut-down the computer but I can't cause all the progress will be lost.

**Describe the solution you'd like**
It'd be nice if I could resume the job even after full restart of the PC.

**Describe alternatives you've considered**
N/A

**Explain why the feature matters to you**

When the job is really big and I **really** need to shutdown PC. All the hours of progress dies with the shutdown.

**Additional context**
N/A

**Comment by Dendraspis** [comment]
StaxRip won't be able to save all encoders data from memory to disk and re-write them back to the encoders after restart.
This would be a nice feature, but sadly impossible.

**Comment by Cyberavater** [comment]
Well, how about modifying the encoder to record the data to HDD after pressing pause?

**Comment by Cyberavater** [comment]
@Dendraspis I have thought of another alternative idea, but a key requirement for this would be to know if;
I cut a file into 2 and then encode it and append it later after encoding will there be a glitch at the connecting point? Or will I be not able to find any difference?
If it's the latter then this could be hope.

https://github.com/mifi/lossless-cut/issues/275

**Comment by 44vince44** [comment]
Please know that the **HIBERNATE feature of Windows** is intended for that, and that I have used this feature and it worked with staxrip (it was long ago, I didn't have the chance to use that recently).

**Comment by Dendraspis** [comment]
@44vince44  You're right, but as far as I understood (s)he needs to shut down and/or restart the computer. When you install, remove or update software and you need to perform a clean restart, the hibernate mode won't help.

@Cyberavater At the beginning I would check every joining point for artifacts or similar. Also have in mind that you loose "a few" MB on compression due to less efficient coding at the beginning/end of each part.
I wouldn't recommend such an solution, but if you have to shut down your computer within a few minutes, this should be *your* solution **if the hibernate mode is not possible**.

**Comment by Cyberavater** [comment]
Hmm, it seems like cutting n joining isn't a good option but I'll keep this open to see what other brilliant minds have, to say on this. But thanks for the info nonetheless.

**Comment by 44vince44** [comment]
@Cyberavater I suggest you close that thread now, because the options are obvious, and you can be pretty sure that there won't be any further suggestions:

1) cut video, process in parts with identical parameters, then join (losslessly) => the problem is that the lossless joiners always create files that cause problems, it's not safe. Problems such as: when you play beyond a cut point, then you seek backwards before the cut point, the video stops being rendered. 

2) use Windows hibernate, that allows you to shutdown the computer, and resume, but does not allow you to restart in order to apply updates.

3) the remaining option is to open staxrip in a virtual machine, run it and save state before you restart your computer. Then resume state. This will work theoretically (I haven't tried it) without problems, providing you activate in your UEFI/Bios the proper virtualization options. You'll need a huge amount of memory because in your virtual machine you'll have to boot a copy of windows.
It seems too much trouble.

So, you can PAUSE your updates in Windows (for 7 days) prior to processing the big file.
If you do so, you'll be able to use Windows hibernate should you need to shut down your computer and resume later.

**Comment by stax76** [comment]
Feature is too difficult.
