### ISSUE TITLE
Import VUI does not import correctly values of colormatrix, colorprim, and transfer for BT601

### ISSUE THREAD

**Issue by cfelicio** [staxrip/staxrip#172]
**Describe the bug**
Hi There,

I'm trying to convert some old VHS tapes to X264, deinterlaced via QTGMC. Staxrip is awesome for the task, but I'm having a couple of issues that I'm not sure if it's by design, or a configuration problem.

With all filters disabled, and simply converting the source to X264 (or X265, I tried both), I would expect the video to maintain original colors, but Staxrip seems to be saturating the colors. You can see an example here, the orange shirt makes it obvious:

![image](https://user-images.githubusercontent.com/7227683/80318132-c5c75d80-87bc-11ea-9a07-10d3eca69c94.png)

All my source videos are MPEG2, some are in MKV containers and get sourced with FFVideoSource, some are mpg and get sourced with MPEG2Source. The problem happens on both types.

I also tried the same steps via handbrake, and the issue does not seem to happen, but handbrake does not have QTGMC, so it's a no go.

**How to reproduce the issue**

Issue seems to happen on all my source videos (MPEG2). Since my sources are super big (3gb+), I looked for some small source clips on videohelp. See attached:
[sample.zip](https://github.com/staxrip/staxrip/files/4536408/sample.zip)

Interesting enough, the issue did not seem to happen to all sources. The main difference seems to be on the video encoding (PAL vs NTSC). The NTSC sources are having the issue, PAL is fine:

![image](https://user-images.githubusercontent.com/7227683/80318701-c235d580-87c0-11ea-872f-c5c1e199fe46.png)

![image](https://user-images.githubusercontent.com/7227683/80318708-d083f180-87c0-11ea-95d6-4e4c403a0c4a.png)

I also notice on the x264 encoder there is a flag for --colorprim bt470m, perhaps it's related?

These were attempted with the latest version (2.0.8.0) and with Avysynth.

If you need any more information, let me know. Appreciate your help!

**Comment by cfelicio** [comment]
Umm, I think I'm onto something. For the sample above, with handbrake I get the following output:

![image](https://user-images.githubusercontent.com/7227683/80319697-b4834e80-87c6-11ea-8ca4-57e119e37698.png)

And here is the staxrip output:
![image](https://user-images.githubusercontent.com/7227683/80319705-bea54d00-87c6-11ea-9b75-30dc3401dc7a.png)

Sample:
![image](https://user-images.githubusercontent.com/7227683/80319716-ccf36900-87c6-11ea-9a2c-fe9197492be0.png)

I'll play a bit more with the encoder and see if I can figure this out.

**Comment by cfelicio** [comment]
Success! Under x264 Options -> VUI, by default color settings are like this:
![image](https://user-images.githubusercontent.com/7227683/80319897-e648e500-87c7-11ea-8ad8-880fbb47386f.png)


I changed to this:
![image](https://user-images.githubusercontent.com/7227683/80319892-de894080-87c7-11ea-95a6-65dfcbb8a107.png)

And colors are coming out correctly! I'll leave this open for a few days to see if I can get any comment from the devs on the behavior for NTSC videos.

**Comment by PhoO3nX** [comment]
It's not issue, just knowledge.

It's a issue ticket here, not a forum. Ask your question on the videohelp staxrip forum

https://forum.videohelp.com/threads/369913-StaxRip

**Comment by cfelicio** [comment]
Sorry if it wasn't clear, I am reporting what I believe to be an issue. If that's not the case, and the tool is working as expected, I can close it.

**Comment by Patman86** [comment]
It's an issue. Staxrip is supposed to get the data from the source file and that doesn't happen in this case.

**Comment by cfelicio** [comment]
@Patman86 tried with BT 470 BG and I get the following on mediainfo:

![image](https://user-images.githubusercontent.com/7227683/80454467-f0a9d280-88de-11ea-8576-3c088f5a181d.png)

The original file is NTSC, so I'd not expect to see PAL there. Colors still seem a little off:

![image](https://user-images.githubusercontent.com/7227683/80454780-73cb2880-88df-11ea-8cad-0de747562509.png)

With SMPTE 170M, looks more accurate to my eyes. Thoughts?

**Comment by cfelicio** [comment]
Looks like the options are under VideoEncoder.vb (starting at line 57):

Select Case colour_primaries
            Case "BT.2020"
                If colour_primaries.Contains("BT.2020") Then
                    cl += " --colorprim bt2020"
                End If
            Case "BT.709"
                If colour_primaries.Contains("BT.709") Then
                    cl += " --colorprim bt709"
                End If
            **Case "BT.601 NTSC"
                If colour_primaries.Contains("BT.601 NTSC") Then
                    cl += " --colorprim bt470m"
                End If
            Case "BT.601 PAL"
                If colour_primaries.Contains("BT.601 PAL") Then
                    cl += " --colorprim bt470bg"**
                End If
        End Select


Looking at Wikipedia, this seems to be correct:

![image](https://user-images.githubusercontent.com/7227683/80510236-4c03b100-892f-11ea-8ef4-51ad43bf5211.png)

But somehow SMTP looks better (it is also a valid NTSC standard). At this point I'm thinking it makes sense to leave it as is, and I will just recompile a version for my specific needs with this flag commented out. 

In the videohelp forums, the running joke is NTSC = Never The Same Color, now I know why! lol

**Comment by Patman86** [comment]
You're right 😉 save a template with your settings for this case.

**Comment by cfelicio** [comment]
Umm, tried the template (both staxrip template and x264 template), and they still get overridden by this setting, so still doesn't work in batch mode. :(

Is it easy to setup a build environment to re-compile this with the setting commented out? Another option is maybe create the batch and change the settings on the temp folders via search and replace, not sure what would be easier... lol

**Comment by cfelicio** [comment]
Was not able to recompile with GCC, so I just used VS Studio, all working good now with the small changes above. Thanks for helping me sort this out! :-)

**Comment by 44vince44** [comment]
@cfelicio @Patman86 @stax76 I confirm the behaviour that is described here and it **IS A BUG!** It must be fixed. I have knowledge of colour matrices. Where the input is BT601, either pal or NTSC, the proper way to handle this is to set VUI primaries, transfer, and coefficients to **UNDEFINED**. Please fix that !!
Because UNDEFINED is interpreted as BT601 for resolutions <720p,  and the source video is less than 720p, because it's Pal or ntsc.

**Comment by Patman86** [comment]
Thanks for clarification @44vince44

**Comment by cfelicio** [comment]
Should I reopen?

**Comment by 44vince44** [comment]
@cfelicio yes definitely please reopen, and please consider changing title to "Import VUI does not import correctly values of color matrix for BT601" or something like that.
And BTW you got all the work already done here (quoting from your previous post):

> Select Case colour_primaries
> Case "BT.2020"
> If colour_primaries.Contains("BT.2020") Then
> cl += " --colorprim bt2020"
> End If
> Case "BT.709"
> If colour_primaries.Contains("BT.709") Then
> cl += " --colorprim bt709"
> End If
> Case "BT.601 NTSC"
> If colour_primaries.Contains("BT.601 NTSC") Then
> cl += " --colorprim bt470m"
> End If
> Case "BT.601 PAL"
> If colour_primaries.Contains("BT.601 PAL") Then
> cl += " --colorprim bt470bg"
> End If
> End Select
> 

FIX:
Case "BT.601 PAL"or Case "BT.601 NTSC" should make **no change to colorprim**.
Same thing for Colormatrix and Transfer, if source contains "BT.601", then **no change to colormatrix and transfer**.
So I guess it's easy, only a few lines to remove.

**Comment by cfelicio** [comment]
Done, I tried to submit a PR but somehow does not work. As you said, should be an easy fix :)

**Comment by cfelicio** [comment]
Looks like as a workaround, if anyone runs into this issue, is to disable this option:

![image](https://user-images.githubusercontent.com/7227683/80827996-7193f300-8b99-11ea-85f9-364974d9c2ab.png)

**Comment by Patman86** [comment]
Please test [this fix](http://www.mediafire.com/folder/xxvf21xtbhetp/Fixes_by_Patman)

**Comment by 44vince44** [comment]
The code changes seem ok (obviously ;-)))). I'll try to get such a file to test

**Comment by OnbekendHH** [comment]
I've noticed a similar issue... NTSC VUI Info is not correctly imported from Bluray...
Under VUI 2 / Videoformat is not switched to NTSC, but left to "undefined"... I always need to check this manually and set it to NTSC.
It'd be great, if this could be set/imported automatically.

**Comment by 44vince44** [comment]
@OnbekendHH you are importing from Bluray, I really wonder if Videoformat setting is relevant. What does it change if you don't set it to NTSC ? Did you see any difference ?

**Comment by OnbekendHH** [comment]
Yes, it appears differently... colors track differently, much like the comparisons posted here.

**Comment by 44vince44** [comment]
@OnbekendHH I tried to find out about that specific matter ("Videoformat") in players documentation, and I found nothing. Can you please paste here the mediainfo data so I can try and replicate it ?

**Comment by OnbekendHH** [comment]
![image](https://user-images.githubusercontent.com/7472445/80907889-dc206c80-8d1a-11ea-8191-e2d179a045d5.png)

**Comment by OnbekendHH** [comment]
Hope this helps... It's the MediaInfo of the Source Bluray...
With each import, I need to check the Bluray for this entry (or others, such as Component or PAL) and manually set it here:

![image](https://user-images.githubusercontent.com/7472445/80907922-2e618d80-8d1b-11ea-94d0-43c72c1efd41.png)

**Comment by 44vince44** [comment]
@OnbekendHH thank you for the data above which confirmed what I know: the metadata VideoFormat relating to video standards has absolutely NO MEANING when you are using color spaces YUV.
See, Component, Pal, Secam, MAC are standards way below YUV and are coded in a way that requires knowing what standard was used. YUV is a 3-plane system which remains as is, whereas Component is 3-plane data encoded to 2 signals, and NTSC, Pal, Secam encoded to 1 signal (also called composite). This is why in order to decode the 1-signal composite, you need to know the "Standard". The "standard" encloses how to decode from 1 signal to RGB, and what resolution is being used. 

In a Blu-ray, the resolution is set separately as a metadata value, and the colorspace is YUV, also set as a metadata value, and NTSC has simply no meaning there because we are not decoding from a composite signal. 

I guess this metadata is there for legacy information, and for sure, it is not used by any player.

Check this:

![SNAG-0001](https://user-images.githubusercontent.com/17828567/80913918-dba2c880-8d50-11ea-89da-94702d604f02.jpg)

The image above has Videoformat set to NTSC. The one below has it undefined. Both from same source.
If you see a difference, it's your screen. Grab a color picker and check all colors: the upper image is exactly the same as the lower image.


So to conclude this long post : Videoformat is a tag that has no use. So it's up to Stax whether he decides to import useless metadata or not.

But please, let's remember the ORIGINAL TOPIC: it was about BT601, and the commits by Patman are very OK.

**Comment by 44vince44** [comment]
@Patman86 I have tested your fix with a BT601 NTSC file, and it worked properly: not matrix VUI has been imported, which is the proper way that is expected (So VUI has been kept to undefined)

**Comment by mirh** [comment]
> the proper way to handle this is to set VUI primaries, transfer, and coefficients to UNDEFINED

No, this is bullshit from the broadcast age. 
If you are a TV station/studio, of course it's not like you can go much wrong. 
Wherever you were in space and time, there was just one standard at a time that your equipment even allowed you to target, so that's it (fun fact: ATSC requires explicit colorimetry info in their signal, probably aware of the unflattering NTSC backronym)
And even when mastering discs later on, every "generation" of specification still acted like they were the only one on earth ever (boy isn't DVD [complex](http://forum.doom9.org/showthread.php?t=133982))

But it's 2022, and we have [phones](https://www.gsmarena.com/oneplus_8t_handson-review-2182p6.php) that can do bt.601 4K 60fps H265 video, the web is sRGB (which is BT.709 for colours, but gamma is actually comparable to bt.601.. [fuck](https://docs.microsoft.com/en-us/windows/win32/medfound/extended-color-information) if I understood that), videos can totally be upscaled, and worse [historical](https://github.com/sekrit-twc/zimg/issues/155)) stuff.

Undefined should just happen if you ***legitly*** have no damn clue whatsoever about the values. 

> Because UNDEFINED is interpreted as BT601 for resolutions <720p, and the source video is less than 720p, because it's Pal or ntsc.

Case in point, I have seen just about all kinds of heuristic from video players (which have to handle all content in between SDTV and HDTV too). 
Some check exclusively a height > 576 pixels, [others](https://github.com/mpv-player/mpv/blob/v0.34.1/video/csputils.c#L269) have that ***or*** width > 1280, [others](https://github.com/mpc-hc/mpc-hc/blob/1.6.8/src/filters/transform/MPCVideoDec/MPCVideoDecFilter.cpp#L1643) again look for widths larger than 768 - and ffmpeg specifically just handles everything with bt.601 (even though it has at least the courtesy of using the right conversions to it first).

Let alone that primaries and transfer functions aren't useless either, and that's an even sneakier can of worms.
(which seems to have been one of the problems in this thread indeed, personally I would have recommended OP to use [madvr tags]() to first assess the best results of the VHS-to-DVD conversion)
