### ISSUE TITLE
Pausing x265 encodes for over a hour appears to reduce performance.

### ISSUE THREAD

**Issue by Inrixia** [staxrip/staxrip#175]
**Describe the bug**
Pausing a x265 encode in progress for over a hour appears to significantly decrease performance after resuming for the remainder of that encode. System performance remains at 100% utilization after resuming and this has happened on different machines more than once.

**Expected behavior**
Performance to remain the same after resuming.

**How to reproduce the issue**
Encode any UHD HDR file with the attached preset, pause it for a hour/several hours and then resume. Compare fps before and after pause/resuming.
[x265 HDR 10bits BT2020 UHD-BluRay (slow, BEST quality).zip](https://github.com/staxrip/staxrip/files/4549576/x265.HDR.10bits.BT2020.UHD-BluRay.slow.BEST.quality.zip)

Here is an example of a source file:
![image](https://user-images.githubusercontent.com/6373693/80556657-72f1de00-8a28-11ea-8f99-af262a927cd4.png)

**Provide information**

If there is a error message than copy the message if possible, if not then make a screenshot. Ater that search for the log file because it should not only contain the error message but also additional useful debug information. The log file is located in the temp folder and the temp folder is located in the same directory as the source file. The log file ends with _staxrip.log. Visit the wesite pastebin.com and paste the log file content there, use the auto expire feature and set it to one year.

Let me know if you need any other info. Unsure what may be causing this or how to fix. Due to the encode times being 30+ Hours for some files not being able to properly pause and resume is a nightmare for workflow at the moment.

**Comment by Inrixia** [comment]
An update, seems that after leaving resumed encodes running for a while (Likely a few hours cannot be certain on the exact time) the reported performance picks back up. It could just be that the reported fps is not accurate after resuming. Will try and check for this if/when it happens again

**Comment by 44vince44** [comment]
@Inrixia If I understand correctly, after you pause the process, and resume, the fps speed of preocessing is very low.

THIS IS NORMAL. Because the fps you read is a weighted average of the fps (weighted with the time of the fps) since the beginning. It is not the instant fps.

When you pause processing for a LONG TIME, at resuming the speed of provcessing (instant fps) will be the same as before pause, but the displayed fps (which is the weighted average fps) will be lower than because the weighted average of a value that has been NUL for a long time is close to NUL.

You can try the following to check what I'm saying:
- After pause a long time, when you resume, prepare your stopwatch.
- Note the frame index (where it says xxxx/yyyy frames) and start counting 60 seconds with your stopwatch
- 60 seconds later read the new frame index
Calculate:
REAL FPS = (frame index 2 - frame index 1) / 60

**Comment by Inrixia** [comment]
Awesome! I was really hoping it was this but wanted to be sure. From more testing it was beginning to appear that it was this. Thanks so much for clarifying that! <3

**Comment by Patman86** [comment]
Yeah @44vince44 i confirm that. Have a look [here](https://github.com/videolan/x265/blob/master/source/x265cli.cpp#L398)

**Comment by 44vince44** [comment]
@Patman86 indeed **int64_t elapsed = time - startTime;**
The only way to "fix" this issue would be **int64_t elapsed = time - startTime - totalpausedtime;**
and the problem is there is no way to get such value "totalpausedtime" :-) or is there??

**Comment by Inrixia** [comment]
Surely if you wanted you could save the date on the event triggered from pausing and then on resumption calculate the time difference to negate. Rather than trying to count while paused.

**Comment by Patman86** [comment]
This is certainly possible, but requires some adjustments. x265 does not consider resuming encoding, that is a feature of StaxRip.

**Comment by Inrixia** [comment]
Likely not high priority as once you know the fps is a weighted average its not a issue :)
