### ISSUE TITLE
Batch Encoding - Remove Chapters from source while encoding

### ISSUE THREAD

**Issue by sunnyx12x21x** [staxrip/staxrip#180]
Hi

i am encoding files which has chapter in source files. if i am encoding i can remove manually by container options. But problem is when doing batch process.

So either some am missing some tricks or we need a feature to ignore Chapters from source.

**Additional context**
While we at Feature request, i was thinking some scripting or something that can make staxrip wait for few seconds/minutes before jumping to next Encoding Job. This can probally help if one don't want his mashine to get overheat.

Thanks

**Comment by 44vince44** [comment]
@stax76 @sunnyx12x21x I think this is an important point, we should have an option to ignore the chapters completely, maybe in the OPTIONS menu, under the subtitles submenu...

**Comment by 44vince44** [comment]
@sunnyx12x21x for the feature of avoiding cpu overheating, this is not achieved by pausing between jobs. Because some jobs can last hours. If your computer has proper ventilation and heat management, you can have it running hours. If it has a flawed heat management then it can be damaged within 30minutes. The proper solution is to limit cpu Try changing the power mode to best battery life, this will decrease CPU usage. But if you want to act very professionally, you can by creating a new power plan with limited cpu that you can set to the exact percentage you want and that you can switch to on the fly... everything is possible.
![SNAG-0000](https://user-images.githubusercontent.com/17828567/81385287-c2689600-911b-11ea-9c25-f61c09d85f5d.jpg)

**Comment by stax76** [comment]
Chapter demuxing can be disabled at:

Main Menu > Tools > Settings > Preprocessing > mkvextrakt > Edit > Chapters Demuxing

So it's a somehow hidden global setting.

**Comment by 44vince44** [comment]
@stax76 I guess this is a way of doing it :-) but it's a global setting, not a tempate option. I guess it's satisfactory if no other people claim it! thanks!!

**Comment by 44vince44** [comment]
@stax76 i tried long time ago to put in the container command line additional switches the "--no-chapters" switch, but it was overriden by the chapter switch (so in the command line there were chapters and no-chapters at the same time, and the chapters override no-chapters)
