### ISSUE TITLE
Resizing Interlaced Content (25>50fps) = Frame Stuttering/Lag

### ISSUE THREAD

**Issue by NMX12** [staxrip/staxrip#181]
This problem is more noticeable with VapourSynth outputs but is still present with AviSynth.

All of my encoding jobs are DVB recordings from HD-1080i and SD-576i PAL broadcasts (25>50fps).
I know I can Deinterlace using 'Synth scripts but doing so significantly increases encoding time.

Encoding Performance (i5 7200u):
>Interlaced Output (25>50fps) = 26-42fps
>Script Deinterlaced (50fps) = 6-15fps

So I decided upon an interlaced output to match the input; keep things simple, close to source.

x264's settings I set TFF Interlaced and without resizing everything comes out fine.

Problem is I prefer to resize SD-576 to 864x480 & HD-1080 to 720 using VS's ResampleHQ Sinc so as to fix the SAR (720x576) & DAR (1024x576) difference in SD broadcasts, enhance edges through downscaling, and to save what little file size difference comes with it.

Though a little slower (for me), I've found VS provides a slightly higher, more visually accurate (compared to raw recording), quality output.

Unfortunately resizing interlaced content (Sinc especially (in AVS but more so in VS)) results in flickering watermarks and frame stuttering/movement lag. Screenshot examples below show fluidity of movement for each job.

The larger the downscale the more noticeable it becomes. Taking 1080 down to 720 or 480 stutters like crazy.

Current workarounds (so as to not increase job time) are to either not resize at all, which is restrictive, or output to 25fps progressive with no deinterlacing, which means throwing away half the field, which feels like cutting away half of the broadcast/detail.

I don't know if this is a problem that can be fixed but I thought I'd try posting anyway.

Began using StaxRip in 2008. Hope I don't sound like an idiot and that you'll forgive any unintentional ignorance I may have when it comes to all of this.

Thanks for your help.

p.s. Sorry for the length, tried cutting it down as much as possible.

Screenshots:
![No Resize](https://user-images.githubusercontent.com/63591866/80899047-9382a680-8d4e-11ea-9362-15751da9f402.png)
![Sinc Resize](https://user-images.githubusercontent.com/63591866/80899053-a6957680-8d4e-11ea-872c-1100681e7ed0.png)

Log Files:
[NoResize - 2.0.8.0_staxrip.log](https://github.com/staxrip/staxrip/files/4569641/NoResize.-.2.0.8.0_staxrip.log)
[SincResize - 2.0.8.0_staxrip.log](https://github.com/staxrip/staxrip/files/4569642/SincResize.-.2.0.8.0_staxrip.log)

**Comment by 44vince44** [comment]
@NMX12 , what you're asking is video related and is not specific to staxrip or Avisynth and Vapoursynth.
If you want to resize (which I do with all such sources), you have to deinterlace otherwise you'll get the artifacts shown in the SincResize. If you resize without deinterlacing, the resulting image will be irreversibly damaged!

Here is my advice:
1) For 1080i sources, you may discard a field, the result will be very good (remember it's broadcasting quality, so there's no significant loss). If the stream is frame based, then you'll need something like that:
 AssumeFrameBased()
 SeparateFields()
 SelectEven()
 AssumeFrameBased()

The result will be a 540 line progressive video, which is satisfactory, provided that the source is DVB.

2) For Pal (full 576), discarding a field is not an option otherwise you'll end up with a bit more than VCR quality. So chose a deinterlacer, then resize if you want.

In both cases, the output must be progressive 25fps for pal sources and 29.97 fps for ntsc sources.

It is important that the videos are processed correctly, even if it takes time. Interlaced videos that have been compressed without proper processing are damaged forever.

**Comment by NMX12** [comment]
Things are getting stranger.

(✓) NoResize - Vapour = Perfect
(X) Sinc - ReSampleHQ - Vapour = Artefacts
(X) Spline16 - ReSampleHQ - Vapour = Artefacts
(X) Spline16 - ResizeMT - AVS = Artefacts
*but*
(✓) Spline16 - (Normal) Resize - Vapour = Clean

This should help more than screenshots and log files:

https://drive.google.com/open?id=14dnxieYsqXzt4YxLliPe4f_vYkYWVPIl

**Comment by 44vince44** [comment]
@NMX12 it's your player !!!!!! There is something wrong with it, either it's the player and either it's the graphic drivers! ALL THE RESIZED VIDEO ARE PERFECT HERE ! ;-)))

**Comment by NMX12** [comment]
Okay, forget interlaced outputs, it's too much hassle.
I'll just use Synth field scripts to give me 50fps progressive output.

One last question though...

This is the default code for 2.0.8.0 VapourSynth's Yadifmod script.
`clip = core.yadifmod.Yadifmod(clip, core.nnedi3.nnedi3(clip, field=0), order=1, field=-1, mode=0)`

What do I have to write to get double rate (50fps)?

I tried:
`clip = core.yadifmod.Yadifmod(clip, core.nnedi3.nnedi3(clip, field=0), order=1, field=-1, mode=1)`

As according to this guide:
**https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Yadifmod**

But I get this error:
```
Script Error

Python exception: Yadifmod: edeint clip's number of frames doesn't match

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
  File "C:\Users\NMX7\Downloads\ToRunThrough\7mate_Brisbane-11252019-2027_temp\7mate_Brisbane-11252019-2027_new_preview.vpy", line 10, in <module>
    clip = core.yadifmod.Yadifmod(clip, core.nnedi3.nnedi3(clip, field=0), order=1, field=-1, mode=1)
  File "src\cython\vapoursynth.pyx", line 1852, in vapoursynth.Function.__call__
vapoursynth.Error: Yadifmod: edeint clip's number of frames doesn't match
```

Changing the code to mode=1 in AVS' Yadif gives me 50fps, but not in Vapour.

I tried VS>Field>W3FDIF and got 50fps with a Sinc-ReSampleHQ into x264 and everything came out great!

All that's left to do is see which does a better job, Yadif or W3FDIF.
I just can't get Vapour's Yadif to give me 50fps.

**Comment by 44vince44** [comment]
I'm afraid I can't help you much with VS, I don't use it, I kept using Avisynth for many reasons, and never got in depth into Vapoursynth (and probably never will)
And I don't have performance issues with Avisynth because the filters I use are all multithreading (this is why I use resizeMT).
I am just wondering why do you want 50 fps ? to get the "fake" smooth impression ? This is also something I dont do. I always convert 50 fps interlaced to 25 progressive because this is what interlace is all about. And I don't recommend any thing else...
However what you are wanting to do is a BOB operation on the separate fields, There are lots of examples of how to do that,  you can google them.

**Comment by Patman86** [comment]
@NMX12 test this code

`clip = core.yadifmod.Yadifmod(clip, core.nnedi3.nnedi3(clip, field=2), order=1, field=-1, mode=1)`

**Comment by NMX12** [comment]
@44vince44 Thanks for all your time and help.
@Patman86 Thank you for the code. You've helped workaround this issue.
