### ISSUE TITLE
Port staxrip to Linux

### ISSUE THREAD

**Issue by protvis74** [staxrip/staxrip#19]
Hello,
Sorry, if I posted my issue here wrongly. But I didn't find a better place to talk about. 

I just want to switch to Linux (Debian) as my main OS. But there are still a lot of applications where no Linux version is available. Staxrip is one of these applications. So I have to use Wine or a VM to emulate Windows again.

Is there any chance to port staxrip to Linux? Is it possible?  Are there problems with some libraries? I would also offer my help to port it to Linux.
What do you think?

regards
protvis74

**Comment by Revan654** [comment]
It's not possible. 

First Many of the dotnet libs do not run on Linux. If I recall it has something to do with dotnet .exe file that doesn't exist on Linux side. Along with DPI issue. 

Then there the issue that Avisynth doesn't exist on Linux. With that it kills any hope of StaxRip being ported over. 

Mint(V 19) is the only Linux that has Come close to run Staxrip, That was just base application.

**Comment by protvis74** [comment]
I think there is a misunderstanding. I don't want to run Staxrip with an emulator like wine. I want to rewrite it from scratch that it runs natively under Linux. Yes Avisynth doesn't exist on Linux but  VapourSynth is a Linux-compatible replacement. The scripts aren't Avisynth compatible, but likely 
I think they can easily be reworked into VS scripts, most of the common plugins have been ported. As a side benefit, it's a lot faster than Avisynth.

**Comment by mysteryx93** [comment]
StaxRip is written in plain old WinForms -- which "may" run on MONO on lucky days. Then there's the whole plugin dependency chain; Vapoursynth is mostly only usable on Arch-Linux right now with the AUR. But if you want to use it on another distro, you'll need to pre-compile all the DLLs for that specific distro? Not sure how that would work, but there would be a lot of work to do just there.

Then the UI, the best option for cross-platform programming is using [Avalonia UI](https://avaloniaui.net/) (similar to WPF but better), with MVVM design pattern. Would run very smoothly on .NET Core.

But we're talking about a full code rewrite here.

**Comment by stax76** [comment]
Blazor would also work, I think. I don't know if .NET bindings for QT exist, here is another framework:

https://github.com/picoe/Eto

Linux, MacOS and ARM support for mpv.net would be a lot easier and might actually happen because I'm now willing to open the development for collaboration (moving to github.com/mpv-net). There would be a separate main window implementation for each OS.

**Comment by mysteryx93** [comment]
ETO is more like good-old WinForms and would look native on each OS.

Avalonia is more like WPF/UWP and would share its customizable appearance across OS.

MVVM design pattern (highly recommended for maintenability) is probably only possible in Avalonia. I noted that you haven't caught up on MVVM design patterms, still doing it the old-fashioned WinForms way. I myself up-leveled my skillset in that regards pretty recently. I'd recommend to study MVVM, Dependency Injection and Unit Testing before deciding anything.

MVVM is turning spaghetti code into ravioli code... takes longer to get started, might require more code, and tests can take as long to write as the code itself -- BUT you don't need to spend 10x the development time on debugging anymore and the code is a lot more stable. The main idea: Each module or class does a specific thing only. The only reason that class should ever change is if that "thing" changes. It means that switching the UI framework should require very little change to the code-behind. Changes to MPV's API should require no change elsewhere in the code. Changing the settings storage method should require no change elsewhere whatsoever. Once a class is written and tested -- no need to edit it, because any other tasks are done through external interfaces. Compare that to spaghetti code of large apps.

Blazor is designed for web browser... won't be an optimal experience (nor performance / memory usage) for a full desktop app.

**Comment by stax76** [comment]
I've only basic MVVM experience and would have to improve that in case I wanted to do a larger GUI project, it appears to be complex.

Blazer I would guess can be used in Electron or something similar, it's much likely possible to build desktop apps with HTML frontend and .NET backend, it's something I would seriously consider, or even favor.

If anybody wanted to port staxrip, a VB.NET to C# code converter would also be a great help, I'm not sure if there is one good enough.

**Comment by mysteryx93** [comment]
Some of the components I use for myself could also be used in StaxRip. Sharing some components can reduce on development, so that's also something to consider.

Another project I designed that can be useful here: [FFmpeg / x264 / x265 wrapper](https://github.com/mysteryx93/EmergenceGuardian.Encoder)
