### ISSUE TITLE
AutoOverlay avisynth plugin

### ISSUE THREAD

**Issue by Rafawell** [staxrip/staxrip#2]
Good night.
Staxrip could have the AutoOverlay plugin so fans of rare videos could remove logos and watermarks.
It's the only thing I want for this program to become perfect for min and for so many others.

http://avisynth.nl/index.php/AutoOverlay

**Comment by Revan654** [comment]
You can already add additional plugins to StaxRip(as long as it's 64 Bit). Using the edit profile function.

**Comment by stax76** [comment]
@Rafawell 

The way this plugin works don't seem to be compatible with how staxrip handles included plugins. I tried to include it but gave up because the code that loads plugins is already too complicated and supporting this plugin would be too much work and make the code even more complicated.

Like Revan said it should be possible to add manually by editing the profiles. Any plugin can be added manually.

**Comment by Rafawell** [comment]
Many thanks to both Revan654 and stax76, I am immensely grateful for the effort invested to try to make the plugin viable.

I am an idiot with a command line kkkkk.

Thanks if you have a tutorial, or if you make a tutorial about add plugins to Staxrip.

Thanks brothers.

**Comment by stax76** [comment]
Thanks for the feedback. The filter profiles use an INI format with a special syntax to support multi line filters.

I've ignored the command line and shell scripting most of my life, still refuse to learn advanced batch scripting, took me a long time to understand the basics and some PowerShell, it's hard to learn but fun once you understand it.

I've added an issue regarding improving the documentation on custom filters.

https://github.com/staxrip/staxrip/issues/6

It's however not very difficult. Right click filters, select 'Profiles', find the filter category

[categoryName]

add an entry

```
filternameShownInMenu | submenu =
    LoadPlugin("dll path")
    FilterName()
```
