### ISSUE TITLE
ERROR: A newer Avisynth+ version is required

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#208]
Staxrip v2.1.1.5, using Avisynth.

Avisynth global version in System = 3.5.0.0
Avisynth portable version in APPS\Frameserver = 3.6.0.0

1) Case 1: In Apps Manager, path to Avisynth set to Windows\System32 (global)
 when I import a video, i get immediately  SCRIPT ERROR A newer Avisynth+ version is required

2) case 2: in Apps Manager, path to Avisynth set to Apps\Frameserver\Avisynth
 when I import a video, i get immediately  SCRIPT ERROR A newer Avisynth+ version is required

**So Staxrip is NOT USING portable, or still checking version in Windows\system32\**

**How to reproduce that:** 
1 Uninstall avisynth from your system (from Windows Settings, Apps & Features)
2. Install avisynth 3.5.x on your system  
3 Ask Staxrip 2.1.1.5 app manager to use the **portable Avisynth (point to Apps\Frameserver\Avisynth)**
   the status is OK
4 load a video (Avisynth mode), you get "SCRIPT ERROR A newer Avisynth+ Version is required"
5 close staxrip 2.1.1.5, DELETE Avisynth.dll from C:\Windows\System32
6 open a video in staxrip 2.1.1.5, NO ERROR !!

So Staxrip is checking Avisynth.dll in C:\Windows\System32. If not exist, it will check in Apps\Frameserver\Avisynth.

This is not good. It must check the location set in Apps Manager.

**Comment by stax76** [comment]
There are probably technical issues that are difficult or hardly possible to overcome. The problem is the way avisynth and avisynth tools are designed, staxrip uses many such tools like 10 and some work differently. I tried some tricks like using soft links but it did not work out. Chances are not good for it, for now if you have avisynth installed you have to ensure it's 3.6. I'll leave the issue open until my research is done.

**Comment by 44vince44** [comment]
It seems to be the case since the video source filter.

I there is anything i can do to help i'm here.

**Comment by stax76** [comment]
I changed it to don't allow old versions like currently done for Visual C++ 2019, it shows:

The currently used version of <Name> is not compatible (too old).

And it doesn't allow to edit the version except editing Versions.txt directly instead of using the GUI to do it.

Ideally it should not allow defining a custom path in this case but I'm not sure it's worth the trouble writing this code.

Here is the situation:

Most tools like StaxRip.exe or avs2pipemod.exe just load AviSynth with code like this:

LoadLibrary("AviSynth.dll")

This is however not a full path and what now is happening is the OS will search this DLL, for that it uses a strict order, first it will search it in the startup folder so next to staxrip.exe or next to avs2pipemod.exe or whatever tool is loading the avs file. Next it searches in the system folder, which is where avisynth is installed. I have tried to create soft links for avisynth.dll next to staxrip.exe but this did not work for unknown reason and then I gave up.

One issue was if avisynth is not installed then ffmpeg does not work because it does not use default DLL loading which searches in the path env var which staxrip sets. To fix that a soft link is working, qyot27 and stainless did help me to make this work, other tools like nvenc and qsvenc I cannot even test because I don't have hardware or drivers.

In staxrip I could use a full path to load avisynth.dll and avs2pipemod has an option for that too, for the other tools an option could be requested, I can image some authors like rigaya would help, for some tools a mod could be created but for some tools it would be very difficult like ffmpeg.

Maybe it's not worth the trouble and just leave it as is, it's many avs tools like 10.

**Comment by 44vince44** [comment]
Well, in that case the proper thing to do is remove the AviSynth portable. (imho) because that would lead to confusion.
The way it was before was very good. No conflicts, no problems.
AviSynth never caused problems. Vapoursynth did cause a few, but not AviSynth.
So just keep Vapoursynth portable, and AviSynth as it was before, with a button to install it. It was perfect!

**Comment by stax76** [comment]
I'm not seeing a real issue.

If avisynth is not installed it works.

If a new avisynth versions is installed it works.

If an old avisynth version is installed it will show:

The currently used version of AviSynth is not compatible (too old).

People can click download and download and install a new version, that would be needed anyway.

1. There is no real issue.

2. Portable mode without having to install anything is awesome.

**Comment by 44vince44** [comment]
I agree, it would bee ok, except for this exception: 

![SNAG-0000](https://user-images.githubusercontent.com/17828567/82762613-aac32a00-9e0a-11ea-8e50-b68f96f08f44.jpg)

![SNAG-0001](https://user-images.githubusercontent.com/17828567/82762629-c0385400-9e0a-11ea-9277-2c6a680eb397.jpg)

App manager shows status OK, but you get the error.
If you want to keep the portable version, then the app manager should do the following:
- If Windows\system32\ selected as path in app manager, then check version of 
   Windows\system32\Avisynth.dll 
- If portable or any other path selected, then check version of portable_path\Avisynth.dll
  AND check [if exists Windows\system32\Avisynth.dll] version of Windows\system32\Avisynth.dll

**Comment by stax76** [comment]
It would take too much complicated code for my taste, I changed it to disable the path customization menu items when the path is system32, it's only one small line code and makes also sense for other system32 tools VC++. The message 'The currently used version of AviSynth is not compatible (too old).' is good enough.

**Comment by 44vince44** [comment]
OK! as you wish :-)

**Comment by 44vince44** [comment]
Hi @stax76 , I hope you're doing fine today!

The latest beta 2.1.1.6 handles it ok, there you can NOT set any other path, so the exception described above will not happen, and that FIXED the problem.

However can you please put a line in the description, something like: **"Staxrip has an embedded version of Avisynth, that is used only when Avisynth is not installed on your system"**

**Comment by stax76** [comment]
The description in the apps dialog typically is only a very short description of the tool, it's not meant for documentation and I want to keep it like that.

I can describe things in the docs, the docs have a search field where you can search for _portable_, it will show a list with all pages that contain the word portable, then the ctrl+f page search can be used to find the word in the page.
