### ISSUE TITLE
Sort by name

### ISSUE THREAD

**Issue by fredlkrue** [staxrip/staxrip#210]
When files in batch are added from a folder they are not sorted by name like when you add them from within the folder. Can an option be added to sort jobs by name?

**Comment by stax76** [comment]
Please use the issue template.

Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Describe the solution you'd like A clear and concise description of what you want to happen and how it should work.

Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Explain why the feature matters to you

Additional context Add any other context or screenshots about the feature request here.

**Comment by fredlkrue** [comment]
![Untitled](https://user-images.githubusercontent.com/66029769/83204059-de5ac880-a118-11ea-9fcc-f726ea818745.png)
I am wondering if an option to sort by name can be added to the jobs window.

**Comment by stax76** [comment]
I'll add it if it's not too difficult.

**Comment by fredlkrue** [comment]
Thanks

**Comment by stax76** [comment]
It's available in 2.1.1.8 Beta.
