### ISSUE TITLE
AVS or VS Script as Output 

### ISSUE THREAD

**Issue by JonathonSunshine** [staxrip/staxrip#221]
**Is your feature request related to a problem? Please describe.**
StaxRip can make me some fantastic AVS scripts, but some times i'd like to use them in other programs. For example, load an AVS, export it in VirtualDub for frame serving etc, or just export raw uncompressed video for another program.

**Describe the solution you'd like**
I would like a "PreProcessing Only Mode" for batch encoding. PIck a template, load a bunch of files and StaxRip will do everything it usually does except encode the Video. Basically, just to give me a bunch of AVS files I can use in other programs.

**Describe alternatives you've considered**
Currently, I load up the videos to encode in any random format (with the avs template loaded), start the batch, hit abort when the video encoding starts, then start the batch again, repeat etc etc

**Explain why the feature matters to you**
I want to be able to make AVS VS files to use in other programs.

**Comment by 44vince44** [comment]
In very old staxrip versions, there was an option in the batch selector window that you could check, it was an option to do immediately the demuxing, when the batch is created. That allowed all the temp folders to be created, with the demuxed files, before running the jobs. I don't remember if the avs files where created.
Unfortunately this option was removed somewhere around v1.7.
What you suggest may be fixed by putting this option back, and generating the avs files, when batch is created. 
So what you suggest can

**Comment by stax76** [comment]
You could try to create a template for this task, to disable video encoding choose the video encoder profile Copy/Mux, to disable muxing choose the muxing profile 'No Muxing', to disable audio processing choose the audio profile 'No Audio'. I hope it works.

**Comment by 44vince44** [comment]
But he wouldn't get the avs file that he wants (with video encoding,audio encoding, muxing)

**Comment by stax76** [comment]
I tried to disable everything and it was working correctly, an avs file was generated. I've updated (locally) the docs page _Features_:

- Batch Processing, can not only be used for encoding but for any task like remuxing,
  demuxing or AviSynth/VapourSynth script generation.
