### ISSUE TITLE
Can NVEnc Hardware dencoder be able to encode using vapoursynth scripts?

### ISSUE THREAD

**Issue by YinnVI** [staxrip/staxrip#225]
Can NVEnc Hardware decoder be able to encode using vapoursynth scripts?

If i select the NVEnc Hardware decoder in the decoder option, the vapoursynth script that i use does not affect the results of the encoded video.

the vapoursynth script only has an effect when using the avisynth/vapoursynth decoder, besides that the decoder has no effect.

is there a solution?

**Comment by stax76** [comment]
In order to use AviSynth or VapourSynth you need to use the Decoder option _AviSynth/VapourSynth_ in the nvenc dialog, otherwise AviSynth/VapourSynth is bypassed, you can see this in the command line preview at the bottom of the dialog.

There is however a free AviSynth/VapourSynth source filter plugin that supports hardware decoding, this plugin is called L-Smash-Works and has two source filters:

For MP4:

LibavSMASHSource

For anything else:

LWLibavSource

StaxRip has GUI support to enable hardware decoding.

Double-click the filter list in the main dialog to open the Code Editor.

In the Code Editor right-click LibavSMASHSource/LWLibavSource and then select the menu item _prefer_hw_.

HW decoding might only help in certain situations like if you have very slow filters or only few CPU cores.
