### ISSUE TITLE
windows filepath longer than 260 characters

### ISSUE THREAD

**Issue by stgmihnea** [staxrip/staxrip#226]
When I try to import files with batch job I get an error telling me even though Windows technically supports >260 filepath length .NET can't handle it.

This happens erroneously even the filepath is minimal, e.g. D:\filename

When importing the same file from the same location with drag and drop in Staxrip the process works fine.

I suspect there's something weird happening in the batch importing side, could you help me fix it please.

**Comment by stax76** [comment]
I tried batch processing with this file:

C:\Users\JD\Desktop\aaa.mkv

Did not cause a problem.

Is there a log file?

Please post media info.

**Comment by okeeblow** [comment]
> When I try to import files with batch job I get an error telling me even though Windows technically supports >260 filepath length .NET can't handle it.

As weird at it sounds that was actually true until .NET 4.6.2 shipped with System.IO.LongPath!

https://docs.microsoft.com/en-us/archive/blogs/bclteam/long-paths-in-net-part-1-of-3-kim-hamilton
https://docs.microsoft.com/en-us/archive/blogs/jeremykuhne/net-4-6-2-and-long-paths-on-windows-10

**Comment by stax76** [comment]
It's simply unrealistic, anybody who thinks it's simple can give it try, good luck!

**Comment by okeeblow** [comment]
I didn't mean to imply it wasn't. I ran into this issue myself to find my way here and am more surprised that Microsoft of that era would be so inconsistent.

**Comment by stax76** [comment]
Technically it's very challenging, it has something to with the WinAPI being a C API and probably hundreds of API calls and structures use paths, many are probably not fixed or not possible to fix because they use fixed size buffers that cannot be changed because of backward compatibility.

Most tools do not support it and many are not maintained or even unmaintained plus closed source, staxrip has 200 tools.

In staxrip there might not be issues because I did a text search for 260 and increased buffer sizes, if there are issues with complex .NET APIs like Process then it would be too difficult to workaround it, it might be fixed in .NET Core but a port to that is not realistic either because of again extremely challenging form designer issues.

It's hopeless in my opinion and I don't think anybody can be blamed for it.

**Comment by Dendraspis** [comment]
>  I don't think anybody can be blamed for it.

Of course we can blame the MS guys for that.  😄  😜  
A path with over 260 characters is not that rare .... but we won't blame *you* for that.  🙂

**Comment by stgmihnea** [comment]
Ok so now I've just got the filepath message when normally dragging and dropping a file in Staxrip.

So I did the math: the filename is 74 characters long and it's located in D:\Complete\ on my system. Why is it then triggering a 260-character limit error when I try to open it in staxrip?

Could you check that this filepath error is triggered correctly? If not, is there any way to disable it?

And no, there's no log file because the error appears in a windows BEFORE Staxrip starts importing the file at all.

**Comment by stgmihnea** [comment]
Now that I think about it, is the issue being cause by the fact that Staxrip attempts to construct a folder with the same name as the file in that location and within that folder all files ALSO include the original filename in their name? 

Because that potentially triples the total filename length so with a filename in the 80s you could easily hit the limit behind the scenes. If that's the case, then can I propose that at least inside the working folder filenames should be short and generic?

**Comment by Dendraspis** [comment]
1. "Just" double the length in addition to the directory path.
2. The temp files should have a total length of about 200 chars. So there should be enough space left.
3. Have you tried to shorten the filename to about 20 characters?

**Comment by stax76** [comment]
It checks the full path for the limit (default 150) and the filename for half of the limit.

It's not so simple to work around this, too many features, too much code and not enough time.

**Comment by koolkunz** [comment]
On previous stable release 2.0.8.0 dragging and dropping this file "D:\Kooll Kunz\Downloads\Remux\Watchmen 2009 Director's Cut UK Transfer 1080p Blu-ray Remux AVC TrueHD 5.1 - KRaLiMaRKo.mkv" worked just fine and the generated encode was fine aswell but in the latest stable release 2.1.3.0 dragging and dropping the same file gives the 260 character error. If staxrip is able to encode such files shouldn't there be a better way for staxrip to identify that?

**Comment by stax76** [comment]
Like I said it's not simple to build because there are too many features. Code is somewhere between 50-100 thousand lines.

**Comment by stgmihnea** [comment]
Personally I'm in favor of less features with more robust use cases but that's just me.

I really hope you can find a way to fix this, otherwise batch encoding is pretty much impossible as it's quite common to get filenames in the 70s and 80s. 

I also think a fix would be what I recommended: If the filename X has length over 75 then instead of doing the normal folder called X containing files X.m4a, X.dts, X.avs, X_out.hevc, etc. just use generic filenames inside that folder like Audio1.m4a, Audio2.dts, Video_out.hevc, etc.

**Comment by Dendraspis** [comment]
> I also think a fix would be what I recommended: If the filename X has length over 75 then instead of doing the normal folder called X containing files X.m4a, X.dts, X.avs, X_out.hevc, etc. just use generic filenames inside that folder like Audio1.m4a, Audio2.dts, Video_out.hevc, etc.

Sounds interesting/good, but I would recommend making it completely optional instead of based on the length of the filename.
In most cases it should be enough creating generic temp folders like "StaxRipTemp1", ""StaxRipTemp2", etc instead of using the full filename.

**Comment by stax76** [comment]
OK, I'm convinced now but it probably will take time.

**Comment by stgmihnea** [comment]
Awesome, thank you so much :)

**Comment by Statick** [comment]
just adding a note to say that I'm rolling back to 2.0.8.0 because I'm finding this 260 character error far too much of a barrier

I've got 200+ .d2v files all exported from dgindex ready to go, and about half of them are over the limit despite not being very long. I've just spent ages renaming a bunch and I'm still having problems. I already encoded these files once using 2.0.8.0 without issues, but I just noticed a problem with my settings so I fixed my settings (doh!) and need to re-encode the lot, I've upgraded since I first encoded them and now these files that worked before won't import. None of them have total path lengths including filename over 120 characters, so it does feel a bit odd to be getting told "no", particularly as I've also already overridden the default temp folder name with simply "temp", to reduce the overall path length of temp filenames (this solved a lot of problems I was previously having with the temp folder being named after the filename, I haven't encountered any issues with path lengths since doing this simple change). I can go and rename all of the files to something smaller, but as they're already named as I need the final outputs to be, this means making a list of what all the file names are supposed to be, renaming them to something smaller, and then renaming the finished outputs back again afterwards. I could batch rename them to encode them but would be manually renaming the outputs afterwards, which I don't much fancy!

I'll update back when there's a more functional solution to this

other encoding software I've used before uses generated temp file names that are just 8 random characters or whatever, I feel that's probably a better solution than replicating the full file name for the temp subfolder and again for the files, and then enforcing very low filename lengths in order to accommodate that without crashing

**Comment by stax76** [comment]
I've marked the issue with high priority but it's all I can do right now because I really need to have a longer break, in that time I will absolutely not work on feature requests like this because it's a huge task.

I will try however:

- Try to follow and tag tracker requests.
- Try to lurk in the forums.
- Try to fix critical issues.
- Try to merge all pull request.

**Comment by Dendraspis** [comment]
Another possibility to handle path length limitations of third party apps:
An optional(!) usage of a global directory for the temp files while keeping the source file names for better identificaltion. Choosing a short temp folder like `A:\StaxRipTemp\` would let the file name be about 200 chars long.

--------------

>    Try to merge all pull request.

Still waiting for that.  😄 😉 😏

**Comment by stgmihnea** [comment]
That's not a bad idea either.

**Comment by stax76** [comment]
> An optional(!) usage of a global directory for the temp files while keeping the source file names for better identificaltion. Choosing a short temp folder like A:\StaxRipTemp\ would let the file name be about 200 chars long.

There is an option for this at:

Main Menu > Options > Paths > Temp Files Folder

I've committed a change that shortens the temp files if necessary.

First step for trying to support real long paths would be finding a file manager that supports paths longer than 260 characters, apparently File Explorer does not yet support it.

**Comment by stax76** [comment]
File Explorer has some limited long path support, better support has Double Commander.

First request:

https://github.com/AviSynth/AviSynthPlus/issues/187

**Comment by stax76** [comment]
MediaInfo is the only tool that supports long paths, it's pathetic...

But long paths can be supported by converting long paths to short paths, it's already working:

https://pastebin.com/gUR0YXLQ

**Comment by stax76** [comment]
New beta with experimental long path support is available, not all features and formats are yet supported.

**Comment by stax76** [comment]
It seems short paths are enabled by default only on drive c and for other drives they must be enabled manually.

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/ff621566(v=ws.11)?redirectedfrom=MSDN

**Comment by stax76** [comment]
MP4Box request:

https://github.com/gpac/gpac/issues/1589

**Comment by Statick** [comment]
one more note on this - I've just dragged 1200 files into the batch window for processing, I thought I'd already made sure every filename was under 75 characters, and the path length is only about 80 chars anyway, but it's still protesting with an error about path length. I have no easy way of finding out which file is causing the problem, these were dragged from search results from about 60-70 different subfolders

a little info in the error message would go a very long way :)

**Comment by Dendraspis** [comment]
@stax76 

> x265:
> https://bitbucket.org/multicoreware/x265_git/issues/4/windows-10-long-path-support

MCW imported their old issues back from the old repository and somehow they overwrote all 7 existing issues!  😠 
So it might be necessary to re-post this issue.

**Comment by stax76** [comment]
@Statick 

We try to enable real long path support.

Meanwhile, you can try to enable 8.3 names per system or per drive, this workaround needs an implementation in staxrip, so far only the most common features have an implementation in staxrip, more can be added on request. Please note that 8.3 names have a performance cost.

**Comment by 44vince44** [comment]
@stax76 does this thread still have a meaning ? Since there is a pinned box for Windows 10 long path, maybe this thread could be closed...

**Comment by Dendraspis** [comment]
What's about ffmpeg and MP4Box ?

**Comment by 44vince44** [comment]
I agree to close this, because this is enough as a reminder: https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

**Comment by stax76** [comment]
@Dendraspis 

The latest MP4Box build has full long path support.
