### ISSUE TITLE
DD+ audio gui support

### ISSUE THREAD

**Issue by skipp1510** [staxrip/staxrip#231]
Can you make eac3 available in the audio codec menu?
![audio](https://user-images.githubusercontent.com/3618431/84600649-3ca6db80-ae7b-11ea-8803-0d9e4ee3b64e.png)

It is supported through ffmpeg. And DD+ would be a good alternative to Dolby Digigtal encoding.

Thank you!

**Comment by 44vince44** [comment]
@stax76 i think that would be easy to do, it's the same as AC3 encoding with ffmpeg, but instead of ac3 in the command line, eac3 ??

**Comment by skipp1510** [comment]
Hello,

i found these infos about encoding bitrates:

Dolby Digital Plus is widely used by streaming and broadcast services to deliver surround sound audio at lower bitrates.

Stereo audio in Dolby Digital Plus is typically encoded at bitrates between 96-128 kbps.
5.1-ch audio in Dolby Digital Plus is typically encoded at bitrates between 192-256 kbps
Dolby Atmos audio in Dolby Digital Plus is typically encoded at bitrates between 384 and 768 kbps.

[https://developer.dolby.com/technology/dolby-audio/dolby-digital-plus/#!](url)
With these bitrates i have very good results and its a lot smaler than ac3 and nearly as wide supported.

Unfortunately ffmpeg supports only 5.1 channels for eac3 as far as i'm aware.

**Comment by 44vince44** [comment]
Maybe @stax76 will decide to include this feature, maybe not.
@stax76  a profile with command line encoder can be done easily, maybe you could consider that.
The encode command is
"%app:ffmpeg%" -i "%input%" -c:a eac3 -b:a %bitrate%k -y -hide_banner "%output%"

@skipp1510 you can yourself create a profile to encode Eac3, I just did and tested with aac, ac3, dts and eac3 (of course all under 5.1 due to limitation of eac3 encoding in ffmpeg.
Remember that it is stated in many places that blu-ray players will have problems with eac3 encoded with ffmpeg.

If you don't know how to do it I can post a small tutorial in images

**Comment by stax76** [comment]
Next build has GUI support and a default profile.

**Comment by 44vince44** [comment]
Thanks !!!

**Comment by stax76** [comment]
New beta is online.
