### ISSUE TITLE
Plugins Folder not defined when Avisynth is not installed in the System globally

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#232]
**Describe the bug**
If Avisynth+ is not installed on your system, then it seems that Plugins folder is not defined, so when you select in the menu TOOLS > FOLDERS > PLUGINS you get the message:

"Object reference not set to an instance of an object."

**Expected behavior**
It should open the folder of additional plugins, it is usually called "plugins64+" folder

**How to reproduce the issue**

1) UNINSTALL Avisynth from your setup (REAL uninstall, not only delete dll from system32)
2) Open staxrip, then Menu TOOLS > FOLDERS > Plugins

**Comment by 44vince44** [comment]
And there is more: 
All the plugins in \Apps\FrameServer\AviSynth are NOT ACCESSED!
The most important one is ConvertStacked.
Because there is a registry entry required that is missing, it would be
[HKEY_LOCAL_MACHINE\SOFTWARE\AviSynth]
@="C:\\Program Files\\StaxRip\\Apps\\FrameServer\\AviSynth"
"plugindir+"="C:\\Program Files\\StaxRip\\Apps\\FrameServer\\AviSynth\\plugins"

This only affects plugins in \Apps\FrameServer\AviSynth ... Maybe very few use the plugins inside..

**Comment by stax76** [comment]
Yes, something has to be done, not sure yet how exactly it will look like, there is a function called [AddAutoloadDir](http://avisynth.nl/index.php/AviSynth+).

**Comment by stax76** [comment]
I've fixed it now, if you click the menu in the next build in portable mode then staxrip will show the folder:

Apps\FrameServer\AviSynth\plugins

or for VapourSynth:

Apps\FrameServer\VapourSynth\vapoursynth64\plugins

vapoursynth auto loads this folder by default, for avisynth a little custom code was needed as it does not load it by default, but it was not difficult to build.

The general problem with this is that the folders are located in the apps folder and I don't recommend changing any files in the apps folder because then you will have it difficult to update staxrip.

But there is a workaround using an old feature:

Options > Filters > Code inserted at top of scripts

There you can add an own auto load folder with the AviSynth function AddAutoloadDir.

Maybe it would be better to move this to the global settings and have two versions, one for avisynth and one for vapoursynth.

**Comment by 44vince44** [comment]
`But there is a workaround using an old feature:

Options > Filters > Code inserted at top of scripts`

Yes this is a very clean way to work!!

**Comment by stax76** [comment]
In portable mode following folder will be supported:

<startup>\Apps\FrameServer\AviSynth\plugins
<startup>\Apps\FrameServer\VapourSynth\vapoursynth64\plugins

But I don't recommend modifying any files in the startup/apps folder because it would make updating staxrip difficult, so additionally there will be:

<settings>\Plugins\AviSynth
<settings>\Plugins\VapourSynth

And that's what the main menu will open in portable mode.

**Comment by 44vince44** [comment]
@stax76 It seems very good, and the selection of settings as root folder is logical, but maybe should be in the root? <StaxripRoot>\UserPlugins\Avisynth
Because when updating major versions, you often need to delete the settings of old version. And you wouldn't want to delete your those plugins, which are not settings btw...

Anyway, as it is intended for very advanced users, maybe its not important...

**Comment by stax76** [comment]
I wrote something about settings and updates here:

https://forum.doom9.org/showthread.php?p=1915875#post1915875

The docs probably needs to be improved regarding the topic because the topic is raised often and it seems many people manage things not ideal.
