### ISSUE TITLE
Detection of AVSynth and VapourSynth

### ISSUE THREAD

**Issue by IBIT-ZEE** [staxrip/staxrip#233]
**Describe the bug**
When opening an .avs file indicate that AVSynth is not installed
(also the same for VapourSynth that is installed inside Python 3.8.x .\Lib)

* Question
What is the method Staxrip uses to detect AVSynth 
(and also VapourSynth)

?is it possible to indicate manually the place where avisynth.dll is stored???
?is it possible to indicate also the path information to VapourSynth.py/dll

**Comment by 44vince44** [comment]
Staxrip has a slightly different logic for Avisynth and Vapoursynth:

1) Avisynth:
Provided that Avisynth installer lets you chose where to put the Avisynth+ folder, it will ALWAYS put the dll in Windows\System32 folder,
So Staxrip tries to detect is there is a AviSynth.dll in Windows\System32
a) if yes then Staxrip will use the the AviSynth installation of the AviSynth installer, and the Avisynth.dll that is in Windows\System32
b) if no, then Staxrip will use the Avisynth.dll included in staxrip's installation tree (the one included with Staxrip, "internal").
Next beta will fix a small issue we found with the plugins64+ folder supported by Avisynth when the internal version is used 

2) Vapoursynth
there is no detection, the user will select in Staxrip settings to use or not the Vapoursynth internal version.

In both cases, you shouldnt have to indicate manually any location, because if you have done correctly the installation of AviSynth and Vapoursynth, this location is written in the registry or is default. 
Now you still have in the setting the "Danger Zone" setting that allows you to set paths, but it is not recommended especially for Avisynth

Did you check in the menu > Apps > Manage that Avisynth shows it's OK?

**Comment by IBIT-ZEE** [comment]
Thanks... I'll go check all of that...

I would dare to suggest the possibility to ask and save 
the path to "avisynth.dll" and ""vapoursynt.dll" in settings, 
allowing the user choose the .dlls to use...

This will be nice for someone who do not want anything other than OS
in \Windows or \Windows\System32

and also for people who has more than one version of this libraries...

Anyway,,, thanks for your excellent answer...

**Comment by 44vince44** [comment]
> I would dare to suggest the possibility to ask and save
the path to "avisynth.dll" and ""vapoursynt.dll" in settings,
allowing the user choose the .dlls to use...

You can: Settings > Danger Zone
But it is intended for very advanced users, and staxrip won't support any malfunction in this mode

**Comment by stax76** [comment]
@IBIT-ZEE 

staxrip uses about ten avisynth tools that open avs files, if avisynth exists in System32 then that's what the tools will use, it's technically hardly possible to change this for most tools because of how windows and avisynth is designed. Few tools allow a custom location by passing it on the command line ignoring System32 but staxrip does not utilize this capability because not all tools support it.

**Comment by stax76** [comment]
In the last beta there is a setting that allows to use avisynth portable even when avisynth is installed.

I had tried the same before and don't know why it did not work, now it works, it uses soft links to achieve it.

Tools > Settings > General > Use include portable AviSynth
