### ISSUE TITLE
AVI Import Filter error

### ISSUE THREAD

**Issue by kaityou1230** [staxrip/staxrip#24]
I'm trying to encode video with vapoursynth script, but I get an error like the picture below.
![staxrip](https://user-images.githubusercontent.com/29443020/61084371-c9c20300-a468-11e9-87e6-ff135fd1671b.png)

The same error is displayed in Virtual Dub2.
![VD2](https://user-images.githubusercontent.com/29443020/61084538-1c032400-a469-11e9-953f-5f746bd493f6.png)

file path
‪C:\Program Files\Python37
‪‪C:\Program Files\VapourSynth
C:\Program Files (x86)\AviSynth+
‪C:\Program Files\Staxrip.2.0.2.4.x64
C:\Program Files\VirtualDub2_43702

**Comment by 44vince44** [comment]
seems related to the file. can you check with mediainfo the properties of your avi file?

**Comment by kaityou1230** [comment]
The file extension is mp4.
![info](https://user-images.githubusercontent.com/29443020/61162604-5b527300-a544-11e9-9f97-8e3d09de73fa.png)


 And with AviSynth i can open it without any problems.
![mp4](https://user-images.githubusercontent.com/29443020/61162620-660d0800-a544-11e9-8382-3bc0c5f00132.png)

**Comment by 44vince44** [comment]
The container is MP4, the streams are AVC (video) and AAC (audio). So this is a standard MP4 file.
The problem is that it is using AVI Import filter. See how you can specify the plugin for importing in the script (I don't use scripts, I use staxrip interface, but i guess it's a Loadplugin call).
Taking a guess:
core.std.LoadPlugin(path="<put the full path to ffms2.dll>")
