### ISSUE TITLE
2.1.3.7 Failed to create soft link

### ISSUE THREAD

**Issue by DandyClubs** [staxrip/staxrip#254]
Failed to create soft link

I:\Encoder\StaxRip\Apps\Encoders\x265\AviSynth.dll

When AviSynth+ is installed then portable mode requires soft link creation due to limitations of AviSynth+ and most AviSynth reading tools.

Option one is installing a compatible AviSynth+ version and disabling AviSynth+ portable mode in the StaxRip settings (Tools > Settings > General).

Option two is running StaxRip with administrative privileges until soft link creation completes, this has to be done only once, after the links were created, regular privileges are sufficient.

Option three is enabling Developer Mode in the Windows 10 settings, this allows soft link creation without administrative privileges.

**Comment by stax76** [comment]
Did you understand what it tells? I suggest option two.

**Comment by DandyClubs** [comment]
> 
> 
> Did you understand what it tells? I suggest option two.

i recoding screen

https://youtu.be/SSIpSeQcpKY

**Comment by Dendraspis** [comment]
You must read/translate the error message and follow one of those three options to solve your problem.

**Comment by 44vince44** [comment]
I must be missing a point. I'm still on version 2.1.3.4, which is BEFORE all this softlink, and I had no problem, with or without a global avisynth installed... Would anyone mind explaining why all this softlinking ? PLEASE !!

**Comment by 44vince44** [comment]
Is it to allow use the Global Avisynth when it is installed ? I'm really not undertsanding why this softlink thing is here...

**Comment by DandyClubs** [comment]
ok i undetstand. my poor english

sorry

**Comment by stax76** [comment]
@44vince44

StaxRip has portable mode enabled by default because many uses have incompatible avisynth versions installed, portable mode can be disabled in the settings as option one explains, if it's disabled and avisynth is installed then no soft links are needed, 

If avisynth is installed and portable mode should be used instead of the installed version then it can only be achieves with soft links because there is no way to tell a tool from where it should load avisynth, default DLL loading applies and that includes the system folder where avisynth is installed. A tool needs an implementation to use a custom/portable path and right now there are only two tools that have such an implementation, that is staxrip and avs2pipemod, they don't need and use soft links, staxrip uses an environment variable to pass the avisynth path to the frameserver.dll library and avs2pipmod a command line option which staxrip passes. The problem is avisynth and all tools except staxrip and avs2pipemod, that is ffmpeg, x265, NVEnc, QSVEnc, VCEEnc, x264 and mpv.net, OK I could fix mpv.net easily but then still the other tools would need an implementation or soft links. And to make it even more complicated some tools like x264 and x265 can have more than one avisynth reader implementation that would all need to support it, so it's rather unrealistic to convince all other authors to support it because there are too many avisynth readers and probably at least one would deny the request, for instance because of ignorance.

If avisynth is not installed then only ffmpeg needs a soft link because ffmpeg blocks default DLL loading which uses PATH which staxrip sets in portable mode. Because of that staxrip does check if the current settings will use ffmpeg loading avisynth and only then will ask for creating the soft link.

If people continue to ask questions and create issues then I will add it to the docs next year, meanwhile maybe it makes sense to leave this issue open.

**Comment by 44vince44** [comment]
Thanks for the explanation @stax76, it is very clear !!

**Comment by MattAKAFred** [comment]
I'm having a similar issue to the one described here, with some caveats:

Background: I'm currently trying to degrain a 16-bit FFV1 and re-encode as FFV1 using FFMPEG (I do not have this problem if I set FFMPEG to convert to x265, or many other formats). I've simplified it down to simply re-encoding 16-bit FF1V without any filters and still receive errors.

I've tried:

Running StaxRip as an administrator and enabling developer mode (suggestions 1 and 3)- StaxRip fails to create soft link

```Failed to create soft link
F:\PortableApps\StaxRip\...\AviSynth.dll```

followed by
```NullReferenceException (2.1.4.2)
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
  at StaxRip.TaskDialog`1.DialogProc(IntPtr hwnd, UInt32 msg, IntPtr wParam, IntPtr IParam, IntPtr IpRefData) in D:\Projekte\VB\staxrip\UI\TaskDialog.vb:line 314
... (more error code - won't let me copy, can screenshot)
```
(for reference, I do not have a drive D:\, if that matters)

Additionally, I have tried installing the latest AviSynth separately and disabling portable mode (suggestion 2), and I get even more errors.

Please advise.

**Comment by stax76** [comment]
@DandyClubs 

Please post screenshots.

**Comment by MattAKAFred** [comment]
Guessing you meant me, not DandyClubs, but here you go!
![StaxRip-001](https://user-images.githubusercontent.com/10765607/91748775-59e37000-eb75-11ea-991d-925c1ee488f7.PNG)
![StaxRip-002](https://user-images.githubusercontent.com/10765607/91748776-5a7c0680-eb75-11ea-9d57-4905a2da3000.PNG)
![StaxRip-003](https://user-images.githubusercontent.com/10765607/91748765-5819ac80-eb75-11ea-98a6-cdda902cd903.PNG)
![StaxRip-004](https://user-images.githubusercontent.com/10765607/91748767-58b24300-eb75-11ea-92a3-1fda7f3f8c62.PNG)
![StaxRip-005](https://user-images.githubusercontent.com/10765607/91748770-594ad980-eb75-11ea-9195-c631ccd98d7b.PNG)
![StaxRip-006](https://user-images.githubusercontent.com/10765607/91748772-59e37000-eb75-11ea-8304-6f430cb9acf9.PNG)

**Comment by stax76** [comment]
@MattAKAFred

It's unclear why soft link creation fails and also why the exception happens. Which OS Version is used here?

As workaround, you can install AviSynth from here:

https://github.com/AviSynth/AviSynthPlus/releases/download/v3.6.1/AviSynthPlus_3.6.1_20200619.exe

In the staxrip settings choose:

Main Menu > Tools > Settings > Frameserver > AviSynth Mode: Use installed directly

This will use the installed AviSynth which don't require soft link creation and usage.
