### ISSUE TITLE
Add support for VVC and xHE-AAC

### ISSUE THREAD

**Issue by asif-ansari** [staxrip/staxrip#266]
Let's add the support for VVC (H.266) and xHE-AAC codecs.

Reference implementation of VVC: https://vcgit.hhi.fraunhofer.de/jvet/VVCSoftware_VTM
Exhale supports xHE-AAC: https://gitlab.com/ecodis/exhale

**Comment by asif-ansari** [comment]
vvenc is now available here -> [](https://github.com/fraunhoferhhi/vvenc)

**Comment by 44vince44** [comment]
Are there any binaries ? It seems too soon yet.

**Comment by Dendraspis** [comment]
@44vince44 
There a build instructions.  😁 

> 6 July 2020: Completion of final standard

So I think we could start to add it. The question is if it makes sense in such an early state.  🤔  But implementation could be a nice challenge.  🙄

**Comment by 44vince44** [comment]
@Dendraspis it clearly seems that this VVC has a simpler options approach than aomenc 🤣 But that could still change....
Let's wait to somebody builds it....

**Comment by Dendraspis** [comment]
@44vince44 
Seems like you didn't read the whole Introduction. 😁  😗 
To be honest I believe this will be a very huge task if we would like to get full control over the expert encoder!

They give us this example:
```
vvencFFapp -c randomaccess_medium.cfg -c sequence.cfg
```
So it seems like the configuration is done by configuration files instead of parameters. This could lead to a few issues, but at least to a complete overhaul codewise. 

Here the sources:
https://github.com/fraunhoferhhi/vvenc/blob/master/cfg/sequence.cfg
https://github.com/fraunhoferhhi/vvenc/blob/master/cfg/randomaccess_medium.cfg

The standard encoder uses just a few parameters, that should be easier. But is it worth it?  🤔  I think we should wait.

**Comment by 44vince44** [comment]
@Dendraspis I share your concern about the expert mode, it's far too different from the current logic in staxrip (BTW I read it, but I didn't comment because I assume the expert encoder will be non-free), As far as I imagine, the "basic" mode would fit the needs of 99.9% of the users.
If we compare to x265, there are people using too many parameters, and multi-pass etc. And there are people using those three parameters only : tune, preset, crf.  I'm not sure there is a significant gain in using too many parameters.

But the real point will be: will there be a x266 (NOT h266) project, I think so. Maybe it will ise same kind of logic as x265! 

> I think we should wait.

Definitely, it's really too soon !

**Comment by 44vince44** [comment]
These codecs are not yet decoded in the players. I think we can begin thinking of integrating them when a serious player (mpv*, mpc*, vlc) will ship with a decoder for those codecs. Maybe we should close this thread.
