### ISSUE TITLE
New beta or release, please

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#29]
Dear coders and contributors, can we please have a new version, at least a beta (public or private), since there has not been any code change for the last 8 days, and the last beta is almost dated one month ago.
Thank you!

**Comment by pwacooijmans** [comment]
Same request as vince, thank you for asking.

Kind regards,

Pieter

**Comment by Revan654** [comment]
There is a pipeline, Not all released will be released on github, Since that takes allot more time to do.

**Comment by 44vince44** [comment]
Thank you Revan. Is there a link to other /9private/0 betas ?

**Comment by stax76** [comment]
@Revan654 

I think there are a couple of issues with the pipeline, it don't get updated when commits are made to https://github.com/staxrip/staxrip and it has a versioning issue, not including apps is also a major drawback.

I uploaded a new test build including apps and posted it to the old thread because the old thread has an up to date first post pointing to https://github.com/staxrip/staxrip

https://forum.doom9.org/showthread.php?t=172068

https://forum.doom9.org/showthread.php?p=1882197#post1882197

The biggest challenge is to keep our apps in sync. If I remember right then I used the apps of your last 2.02.4 release. Two open issues are missing icons and ffms2 I think.
