### ISSUE TITLE
Support for multiple ffmpeg version with different licenses

### ISSUE THREAD

**Issue by nikolasr** [staxrip/staxrip#292]
It would be great if You could somehow implement the use of multiple ffmpeg versions with different licenses for different tasks.

For example:
To use a LGPL ffmpeg build with fdk-acc enabled for aac encoding. However LGPL lacks other codecs, so there is the need for a second GPLv3 ffmpeg version, e.g. to compile with x264 codec.
And for those who need closed source settings like CUDA and so on, a nonfree version. 

This would also eliminate a legal issue for those who don't want a "nonfree" version and do not use any of its features.

Kind of 3 step:
LGPL and GPLv3 ffmpeg as standard and optionally nonfree ffmpeg for those who acknowledge the legal risk.

**Comment by 44vince44** [comment]
Under what category falls the currently used builds by @Patman86  ?

**Comment by Patman86** [comment]
A version with fdk-aac enabled would never be published because of the license terms. My version is compiled with non-free license because of the usage of CUDA and the other Codecs. Have a look at the config file inside the archive.

**Comment by nikolasr** [comment]
Well, it's just about _support_ for a fdk-aac enabled ffmpeg version in Staxrip. ;-)

When compiling ffmpeg the source accepts a LGPL/fdk-aac setting. However this doen't mean it's legal. I wouldn't publish a fdk-aac binary build, either. But StaxRip cannot be blamed for only _supporting_ such a combination. Where to get a binary *and* a license is the sole problem of the end user. To be sure StaxRip could give a license warning before activating such an option.

**Comment by 44vince44** [comment]
@Patman86 I love your version and I hope that nothing changes ;-)))

**Comment by Patman86** [comment]
Now my ffmpeg contains the GPLv3 license. All libraries work as before, only openssl is missing. I hope that's a good thing. Anyone who wants to use a different version of ffmpeg is welcome to do so.

**Comment by nikolasr** [comment]
@Patman86:
I know. It's not about using a custom ffmpeg version. The problem is if I want to use 2 different ffmpeg versions in one conversion task, I need at least to use the "command line" setting for one of them and edit _"%app:ffmpeg%"_ to "my" version including parameters for endcoding. Sure, it would work, but it would be a PITA ;-)

My intention was to have a kind of _"%app:ffmpeg_lgpl%"_ , _"%app:ffmpeg_gpl%"_, _"%app:ffmpeg_nonfree%_" (or _"%app:ffmpeg%"_ and _"%app:ffmpeg_custom%"_ or something like this) setting.

**Comment by Patman86** [comment]
@ Nikolasr
Hey, you're welcome. Now you've explained and described your request in such a way that everyone knows what you mean ;-)
And i changed the license of my ffmpeg version because of legality :-D 
We only need two versions, ffmpeg.exe (GPLv3) and ffmpeg_custom.exe (non-free). The non-free licensed version can include everything, also fdk-aac. The compiling script defines the required libraries.

**Comment by nikolasr** [comment]
@Patman86:
Sorry, feel free to call me "Moss" :-D

**Comment by stax76** [comment]
There has been some changes in the last beta regarding this issue.

**Comment by nikolasr** [comment]
Just tested. Looking good, worked fine :-)

However, for "end-users" (TM) I think it would be good to edit the help text a little bit. Kind of 
"Beware! 
Here you can specify a custom compiled 'non-free' version of ffmeg, which might use codecs (like fdk-aac) generally *not* considered free to use without a license. 
However since license laws vary around the globe, Staxrip only gives you the option to use a ffmpeg version specially designed to you and your local laws and license portfolio. If in doubt, do consult a local lawyer regarding this issue, *before* using a custom ffmpeg version. Staxrip is in no way responsible of any copyright infringement you do. Because of that: *DO NOT* ask the Staxrip developers for a non-free ffmpeg version. Thank you!"
Maybe this text should be appear in a kind of checkbox with "I understand" to check to activate.

Yeah, as you might have guessed, I'm not only an IT-pro but a failed law student ;-)

**Comment by stax76** [comment]
Next build:

> Versatile audio video convertor console app. Custom build with non-free libraries like fdk-aac.

More detailed descriptions might require a redesign in regard of UI and performance:

https://github.com/staxrip/staxrip/issues/320

**Comment by JJKylee** [comment]
@stax76 

Thanks for introducing the new **%app:ffmpeg non-free%** macro in 2.1.4.3 Beta.

![StaxRip-2 1 4 3-Beta_non-free-ffmpeg_introduction_20200906](https://user-images.githubusercontent.com/3157518/92334152-438b5780-f040-11ea-9afc-d401a9b871b1.jpg)

Now we can have more freedom in customizing the command line. :)

**Comment by JJKylee** [comment]
> @stax76
> 
> Thanks for introducing the new **%app:ffmpeg non-free%** macro in 2.1.4.3 Beta.
>  
> Now we can have more freedom in customizing the command line. :)

Having said this, I'm kind of skeptical about including non-free ffmpeg as a separate tool and a macro in StaxRip.

If you need fdk-aac, you can always choose _fdkaac_ as the audio encoder; fdkaac is incorporated in StaxRip as a separate audio encoder.

If you need CUDA hardware filters (in ffmpeg, they're available only via libnpp which needs CUDA SDK headers, and the resulting ffmpeg build is non-redistributable) in video encoding, you can download @Patman86 's [64bit npp dll files](http://www.mediafire.com/file/rhqnkblmnqqu3g3/npp64_11.7z/file), and put them in NVEnc folder so that _NVEnc_ can make use of them.

As for me, the only time when I miss fdk-aac for ffmpeg is when I run ffmpeg on its own. And the same applies to CUDA hardware filters. Since we can always have other **better alternatives** in StaxRip, I don't see any reason why we need to incorporate a non-free ffmpeg as a separate tool in StaxRip.

Furthermore, this can incur another problem: if a user is not aware of the difference between GPL version and non-free version and what exactly each of them is capable of, he/she can run into a confusing situation like [this](https://github.com/staxrip/staxrip/issues/337#issue-698286022). If the user sets the path for non-free ffmpeg to a GPL ffmpeg executable, he/she can come across an unexpected error because the ffmpeg that is executed is not capable of processing the task assigned to it.

Another imaginable situation (albeit not feasible unless ffmpeg is used as a command line encoder) is when the non-free ffmpeg binary of the user's choosing is not built with DXVA2 or VapourSynth support. The user can see an error if he/she chose to use the non-free ffmpeg for piping the source file via DXVA2 or having the non-free ffmpeg take a vpy file as an input.

Well, I think it's food for thought. Maybe we can put a big warning on the non-free ffmpeg item in Apps Management. But like I said above, I'm sort of dubious about the effectiveness of the non-free version itself in StaxRip.

**Comment by nikolasr** [comment]
> As for me, the only time when I miss fdk-aac in ffmpeg is when I run ffmpeg on its own. 

I agree :-)

> Since we can always have other better alternatives in StaxRip, I don't see any reason why we need to incorporate a non-free ffmpeg as a separate tool in StaxRip.

Well, talking about "better alternatives", do you mean running fdkaac is a standalone application oder using other encoders like qaac and neroaac?

When it comes to legality, I don't see any difference between standalone fdkaac and ffmpeg/fdkaac.

Fdkaac license says:
> 3. NO PATENT LICENSE
> 
> NO EXPRESS OR IMPLIED LICENSES TO ANY PATENT CLAIMS, including without limitation the patents of Fraunhofer, ARE GRANTED BY THIS SOFTWARE LICENSE. Fraunhofer provides no warranty of patent non-infringement with respect to this software.
> 
> You may use this FDK AAC Codec software or modifications thereto only for purposes that are authorized by appropriate patent licenses. 

So IMHO by providing either fdkaac or ffmpeg/fdkaac we are kind of skating on thin ice.

**Comment by JJKylee** [comment]
I'm talking about _functionality_, not legal issues.

My point is, I feel non-free ffmpeg is almost redundant in StaxRip considering fdkaac and NVEnc are at least equally effective as their counterparts embedded in non-free ffmpeg, and we don't have to introduce unexpected errors to the uninitiated users not familiar with ffmpeg usage.

**Comment by nikolasr** [comment]
OK, in my point of view (please do correct me, when I'm getting it wrong), in Your answear, You're saying: 
- keep fdkaac standalone
- ffmpeg-nonfree is not important because fdkaac standalone can be used


OK, and then, I must admit, I don't really get it (sorry, it's my fault!): You're talking about NVEnc. Great thing to encode, but what is the point about ffmpeg-nonfree and fdkaac? Well, ffmpeg non-free, maybe... but fdkaac?
 
Let's stick to fdkaac (for now)
Is it redundant regarding ffmpg-non-free/fdkaac standalone?
Maybe (in *most* use cases: yes)
Let's say: I agree :-)

But, and that's the difference, regarding legality (I know, You don't want to talk about it, but it's part of the problem),
wouldn't it be better (better as "better safe than sorry") to drop fdkaac-standalone support (or, much better, make fdkaac binary optional, with to same disclaimer as ffmpeg-nonfree) and move fdkaac encoding to ffmpeg-nonfree?
Pros:
+ one application less to care about
+ far more "lawyer-safe"

Cons:
- Usability problems with custom non-free ffmpeg
     (would be solved if "someone" (tm) totally not being part of staxrip development would publish a version "somewhere" to find on google, for those who do have a license... -- no cancel this, nobody would do such a thing)

**Comment by Dendraspis** [comment]
> [..] wouldn't it be better (better as "better safe than sorry") to drop fdkaac-standalone support (or, much better, make fdkaac binary optional, with to same disclaimer as ffmpeg-nonfree) and move fdkaac encoding to ffmpeg-nonfree?

In my opinion fdkaac should/could be removed at all. Many tests showed iTunes/qaac being better, so why using the second best when you can use the best tool without issues?

**Comment by nikolasr** [comment]
Well there might be use cases where fdkaac might prove superior. It's not big issue of code change to "blacklist" fdkaac (IMHO, don't hit me! ;-) ) and re-enable it if the license waring has been accepted. So in my opinion: give the end user as much freedom as possible :-D

**Comment by Dendraspis** [comment]
> Well there might be use cases where fdkaac might prove superior.

The tests included music and voice at lower bitrates. At high bitrates there is almost no difference - unless you want it. 😉 

> So in my opinion: give the end user as much freedom as possible :-D

Yeah, in the meantime the end user could use qaac with lower bitrates instead for same quality.  😄  Just kidding, but that's something others have to realize. Just wanted to say that you guys are talking about funny things.  😉 
I'm silent again ...

**Comment by JJKylee** [comment]
There are some software applications that include **fdk-aac** as a _separate_ encoder library within them.

For example, XMedia Recode ships with (in-house built) _fdk-aac.dll_, and it doesn't even issue a license warning in execution when used in the portable mode.

So, is XMedia Recode violating the license terms of FDK-AAC? If so, is the author aware of this and releasing the software at his own risk?

Well, legal stuff is ambiguous, hard and challenging, and only the court has the authority to make a determination in many cases. I've wondered about the questions I asked above, but haven't been successful in finding any definitive answers. Since I'm not a lawyer and a total layman about laws, I don't want to talk about this any more.

However, I agree with @nikolasr about taking a protective approach by putting license warning notes on the help texts of the two legally sensitive tools, non-free ffmpeg and fdkaac, **preserving their positions as registered tools in StaxRip**.

And if the inclusion of a stand-alone fdkaac executable in StaxRip could bring up a legal issue, I also think that it should be handled with the same amount of caution as non-free ffmpeg: fdkaac executable be removed from StaxRip distribution, but its position is preserved. (Well, of course, as long as qaac is still there. 😄)

@stax76 should not take the legal burden on his shoulders by himself, so I guess this could be a reasonable approach.

**Comment by stax76** [comment]
There should not be a risk for anybody, so which binaries should rather be removed?

Candidates:

Apps\Audio\eac3to\neroAacEnc.exe

Apps\Audio\fdkaac

Apps\Audio\qaac\QTfiles64

**Comment by JJKylee** [comment]
Personally, I think neroAacEnc.exe is least useful (10 years old!), so if we have to remove at least one of the three, this one comes first to my mind.

But I'm not sure if fdkaac is equally risky in terms of legality as non-free ffmpeg like I said above: some programs have been shipping with it as a form of a dll file for quite a long time. However, if you want to avoid the smallest possibility of legal issues, I guess you can remove it with its position still remaining in Apps Management and Audio Encoder profile.

And about QTfiles64, I remember there was a time when the user had to get those files on his/her own for StaxRip. Well, at least I had to when I started using StaxRip in early days, although I don't remember how long ago it was. I remember asking @stax76 how to get those files. 😄 

So, I guess it's not a bad idea to get back to those days, as long as it's well documented how to get those dlls. (Not sure if it can be officially documented, though.)

In all of these measures, I strongly believe that their positions as a registered tool and their predefined profiles should not be removed along with the binary files from StaxRip in any case.

**Comment by nikolasr** [comment]
Well ffmpeg-non-free with only gplv3 options and fdkaac compared to fdkaac standalone surley **is** equally risky. And considering QTfiles64 ... well yes, there might be license problems too, but Apple IMHO seems, at least right now, not to take actions against it's use. But, yes, I agree this is one thing I would be careful about.
But I'm not so much into license details to say, if installing iTunes might give the option to use qaac or not.

Well, but as long as Staxrip only gives the _option_ to use those tools, Staxrip should be safe.
I strongly believe those users with the correct license portfolio will the able to find the right binaries ;-) (to put it that way :-D )

Considering NeroAAC: It might be old, but, (yeah, you don't want to hear it... I know ;-) ) legally it is one of the safest options, if not provided directly by Staxrip.
It's free to use, but I would be careful if Staxrip has the license to redistribute it. But any simple google search should provide enough downloads.
So I would vote for it to remain in Staxrip, but not as binary. but external download. Maybe there is even a direct link to Nero AG's / Ahead Software's download server.

**Comment by nikolasr** [comment]
@JJKylee 

> So, is XMedia Recode violating the license terms of FDK-AAC? If so, is the author aware of this and releasing the software at his own risk?

Well, copyright laws vary around the globe.... 
IMHO if the author is a citizen of USA or EU ... I whish him best of luck :-)
If he's e.g. a chinese citizen, well ;-)

**Comment by nikolasr** [comment]
NeroAAC cannot be downloaded from Nero's ftp server, as it had been removed.
But... web.archive.org has that page (and download) archived. So it might be an option to point users to
`http://web.archive.org/web/20160706054853/http://ftp6.nero.com/tools/NeroDigitalAudio.zip`
and avoid redistributing it :-)

**Comment by nikolasr** [comment]
**IANAL** (!) but let's put it that way: Having read [https://github.com/nu774/qaac/blob/master/COPYING](https://github.com/nu774/qaac/blob/master/COPYING), I personally (IMHO!) would use and distribute qaac without license concerns.

**Comment by stax76** [comment]
Can this be closed?

**Comment by JJKylee** [comment]
> Can this be closed?

Yes.

**Comment by stax76** [comment]
OK thanks.
