### ISSUE TITLE
Extract DTS Core does not work on dtshd streams added in the form of container (mka)

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#293]
**Describe the bug**   (reported by user hevron)
When adding an EXTERNAL dtshd audio stream wrapped in a container (possible containers are **mka** and **m4a** although not totally official), the DTS Extract feature doesn't work: the stream is copied as is, the core is not extracted.

**Expected behavior**
It is expected to have the DTS Core extracted as requested.

**ADDITIONAL information**

When the external stream is added in a container mka or m4a, the bug appears. 
BUT if the stream is added as a pure .dtshd stream, then the process works perfectly, no bug.

==> So it seems that Staxrip require a missing demux step when the file is external mka or mka.

**WORKAROUND**
Manually extract the stream from the container using an external software, rename it to file.dtshd, and add this file to the audio streams list in Staxrip

**Comment by Patman86** [comment]
THX for the issue info. I think the problem is the line here and after

[.../General/Muxer.vb#L805](https://github.com/staxrip/staxrip/blob/b9b260a8cc5f753032ab29ae62cba6561325861a/General/Muxer.vb#L805)

[.../General/Muxer.vb#L820](https://github.com/staxrip/staxrip/blob/b9b260a8cc5f753032ab29ae62cba6561325861a/General/Muxer.vb#L820)

You're right, a demux step could be the solution. Or via the feedback from mediainfo and the codec format of the audio file.

**Comment by stax76** [comment]
Thanks @44vince44 and @Patman86, I'm working on it right now.

**Comment by stax76** [comment]
It checks the caption for DTSMA, DTSX and DTSHRA now, but I really don't know if DTSX (DTS XLL X) and  DTS HRA can actually have a core.

https://github.com/staxrip/staxrip/blob/master/General/Muxer.vb#L816

**Comment by Patman86** [comment]
DTS HRA includes a core but for DTS:X i'm not sure. But I think there is no core, it's an other method to produce the surround effects. All Infos for the surround effects came from the metadata.

**Comment by stax76** [comment]
I found a sample (using the media info folder grid), DTS:X has also a core.
