### ISSUE TITLE
NVenc API 10 and new presets

### ISSUE THREAD

**Issue by johnvick** [staxrip/staxrip#294]
Will Staxrip be updated to accommodate the changes to NVenc API 10 which has 7 preset levels and not three?

Please refer to this thread:

https://github.com/rigaya/NVEnc/issues/257#issuecomment-667962525

Thanks for considering.

**Comment by Dendraspis** [comment]
I'm pretty sure that *yes*. I'll try to have a look at the presets the next days.

**Comment by Dendraspis** [comment]
As far as I can tell the preset values changed, but the old ones are still supported for legacy reasons. So I added them because StaxRip is already using a NVEnc version that supports the new API.

The new default preset is ***P4 (=Default)***.

![StaxRipNVENC](https://user-images.githubusercontent.com/50659978/89274762-a785bf00-d641-11ea-894f-d686e987beb0.JPG)

**Comment by johnvick** [comment]
Thanks I look forward to trying it out.
