### ISSUE TITLE
Backups of stats file for each pass when using x265

### ISSUE THREAD

**Issue by VEGAX265** [staxrip/staxrip#295]
When I try to restart the encode on the second or third pass using command prompt I get errors because of frame counts being different.  ie less frames were processed in the failed pass so the stats file is now corrupted.

I would like Staxrip to keep the xxx.stats.temp file created for each pass and label it as such  xxx.stats.pass1, xxx.stats.pass2
This may be an x265 request.

I have lost hours of encoding time due to fails on second or third passes.  

This is a low priority request unless its something simple for you guys.

Also thanks for the great apps.

I have attached a log file for my video xxx.mkv its an hevc 2160p
this one was really odd as it actually finished the encoding process but the video was only 89 megs when it should
 have been over a gig.

I tested this video in versions StaxRip-x64-2.1.3.7-beta StaxRip-x64-2.1.3.9-beta.

[xxx_staxrip bad encode.log](https://github.com/staxrip/staxrip/files/5022987/xxx_staxrip.bad.encode.log)

**Comment by 44vince44** [comment]
@Dendraspis please allow me to suggest that this should not be adressed. When pass 1 is successful, then pass 3 and pass 2 will be successful. Failing in pass2 or pass 3 when pass 1 is successful means that there was a hardware error due to overheating or overclocking or bad memory chips.
I don't know to which point Staxrip must handle errors due to hardware failure.
Anyway it could be easy: after each pass, copy the stats file stats.pass1 stats.passn  stats.pass2.
Again, doing multipass stuff 😕

**Comment by Dendraspis** [comment]
@44vince44 
Though multiple times about a good solution, but I think you're right.  ☺️
