### ISSUE TITLE
Concurrent audio jobs error

### ISSUE THREAD

**Issue by K4Li** [staxrip/staxrip#297]
**Describe the bug**
When running 2 separate audio encoding jobs concurrently from the same source audio, whichever job is started second results in error 

**Expected behavior**
Both audio jobs should complete

**How to reproduce the issue**
An example of my workflow... demux, index, crop for 1080p x264, choose x264 settings, 5.1 downmix to ac3 5.1, set encode to begin. Use same indexed input, resize to 1280 x xxxx for 720p encode, choose ac-3 2.0 downmix for 720p encode and run concurrently results in error, if first audio job is complete, no issues... can run both audio jobs manually in command or vie .bat but not in the staxrip ui?

**Comment by 44vince44** [comment]
By design, due to a naming scheme in Staxrip, audio processing will create errors if simultaneously working on the same source file. 
Here's a very obvious example: use a source file called sourcefile.mp4.
Create two almost-identical jobs with destination file: dest1.mkv and dest2.mkv, that will use different processing ranges RANGE1 and RANGE2.
Staxrip will create intermediate audio file with the same name derived from sourcefile.mp4 adding "CUT" in the name, and will not use dest1 and dest2. So if Job1 and Job2 run one after another there is no problem. But if they run simultaneously, there's a by-design problem. The result is that one video will end up ok, but the other will end up with audio from the wrong range.
I think fixing it requires major rethinking of the audio process.

**Comment by K4Li** [comment]
*Update* so it seems the error is due to the auto naming scheme "a1" and "a2". The workaround I found was to use a1 for 5.1 downmix profile and a2 for 2.0 downmix profile... seems a possible fix for this would be to change the default naming scheme of audio mixes...

**Comment by 44vince44** [comment]
I think it would be actually easy to fix:
The current naming scheme for audio is:
source_name+stuff1+suff2+stuff3+...+.ext
Fix=change it to:
dest_name+stuff1+suff2+stuff3+...+.ext

**Comment by 44vince44** [comment]
@Dendraspis This has been fixed, please close ! Thanks
