### ISSUE TITLE
not gaining focus after processing

### ISSUE THREAD

**Issue by hani-yassine** [staxrip/staxrip#298]
hello im using staxrip beta 2.1.3.9 to test the new "ShowOpenSourceSingleFileDialog" command and it's working great but it cause a small problem when i use shortcut to use it (in my case ctrl+G) after opening the file the focus is not on the staxrip windows so if i want to open a subtitle file with ctrl+h i cant i have to press the staxrip windows to gain the focus then press ctrl+h so hopfully you can add that staxrip gain focus after opening files with the new commands just like when you open it manually with the mouse, thanks for the great work :)

**Comment by stax76** [comment]
It's by design, the idea was after processing the app should not be in the foreground because it might interrupt whatever people are doing, like watching a movie.

I'm not sure if it's still important because Windows 10 has new focus related features (I don't know much about), it can be found in the Windows 10 settings (searching for keyword focus).

It could be tried to make this behavior optional, this code area is complex.

https://github.com/staxrip/staxrip/blob/ea20f03876d190df14a338700cc7f70d65112101/Forms/MainForm.vb#L6060

**Comment by hani-yassine** [comment]
> It's by design, the idea was after processing the app should not be in the foreground because it might interrupt whatever people are doing, like watching a movie.
> 
> I'm not sure if it's still important because Windows 10 has new focus related features (I don't know much about), it can be found in the Windows 10 settings (searching for keyword focus).
> 
> It could be tried to make this behavior optional, this code area is complex.
> 
> https://github.com/staxrip/staxrip/blob/ea20f03876d190df14a338700cc7f70d65112101/Forms/MainForm.vb#L6060

if you open single file by the classic way (right click then select the file) like in the pic it will gain focus after processing the video and you can immediately use ctrl+h to open a sub file, only when using the shortcut to open the file it will loose focus, it seems you miss understood me as after encoding what i meant is when opening the video, hopefully it can be added as an option in the settings since i dont know how to add this line of code you provided, thanks :)
![Untitled](https://user-images.githubusercontent.com/39760468/89824314-9bc35c80-db5b-11ea-9117-f35d4c90c11f.png)

**Comment by stax76** [comment]
I hope this was fixed.

**Comment by hani-yassine** [comment]
> I hope this was fixed.

yes fixed thank you :)
