### ISSUE TITLE
No metadata when converting using staxrip

### ISSUE THREAD

**Issue by RayCist1608** [staxrip/staxrip#309]
In every codec options I tested (QsvEnc, X265, X264, ffmpeg), none of them would produce a video with metadata, and often I have to read the metadata using mediainfo, to reproduce this is very simple, just convert any video using the QsvEnc x264 codec, the result file will have no metadata when you click on properties from file explorer, not yet tested in linux.

**Comment by stax76** [comment]
What kind of metadata?

**Comment by Asphxiated** [comment]
I don't know what you mean, I get great 'metadata' from x265 if the VUI settings are set properly, so as stax76 asked, what kind of metadata? The main reason I use staxrip is because it does produce all the metadata I wanted and allows me to have a full 10-bit pipeline that is easy to understand. If you're not talking about VUI then I'd be very interested in what metadata is missing for you?

**Comment by RayCist1608** [comment]
Usually when I encode, the resulting file will have 0kpbs for bitrate in both a audio and video, the width and height is empty, the frame rate is also empty, I view the metadata using properties from file explorer. Also how do you set this "VUI"

**Comment by stax76** [comment]
Which Windows version do you use and which container format?

Maybe there are shell extensions, like this one:

https://www.videohelp.com/software/Media-Preview

Try [MediaInfo.NET](https://github.com/stax76/MediaInfo.NET).

**Comment by RayCist1608** [comment]
I use windows 10 build 2004, I would usually use mp4, and I have already installed mediainfo, and used it for sometime now

**Comment by JJKylee** [comment]
As for me, I've never come across this kind of weird situation over the year I've been using StaxRip.
@RayCist1608 , uploading a screenshot of the MediaInfo window showing **no metadata** (as you mentioned) will help.
