### ISSUE TITLE
Incorrect x265 UHD HDR chroma handling

### ISSUE THREAD

**Issue by therealt3nzin** [staxrip/staxrip#319]
**Describe the bug**
UHD HDR chroma subsampling 4:2:2 should have a default of `--chromaloc 2` when using x265 to avoid a potential shift in the chroma of the encoded image.

**Comment by stax76** [comment]
I don't know if there is a staxrip contributor with HDR expertise, so you might have to provide more info. In order to detect the x265 options StaxRip analyses the source file using MediaInfo. Which MediaInfo properties are relevant here? 

https://github.com/staxrip/staxrip/blob/master/Encoding/VideoEncoder.vb#L59

**Comment by Dendraspis** [comment]
@stax76 
I know what he mean and I can take care of it - when you can wait. 😉

**Comment by stax76** [comment]
> I know what he mean and I can take care of it - when you can wait.

Great, no need to hurry. 🙂

**Comment by Dendraspis** [comment]
Should be fixed with some other bugs since v2.1.7.2.  😄
