### ISSUE TITLE
BT 601/Rec.601 colour matrix and primaries

### ISSUE THREAD

**Issue by eppic6502** [staxrip/staxrip#323]
Is there any particular reason that the BT 601 standard for SD footage is missing from the codec VUI options (specifically x264 and x265)?

**Comment by JJKylee** [comment]
Well, my guess is that Rec. 601 and Rec. 709 are almost the same in practice (despite some minor chromaticity disparities) and thus conversion between them is rarely performed in real world. See [this Wikipedia document](https://en.wikipedia.org/wiki/Rec._709#Standards_Conversion).

Isn't is the case that most people leave VUI parameters undefined(blank) except for HDR video streams so that devices can handle color spaces in their own way? I think most modern devices assume the underlying color spaces are Rec. 709 if those VUI parameters are not set in the metadata. Plz, correct me if I'm wrong.

**Comment by MikeBruschke** [comment]
You are correct that almost anything will default to Rec.709 if no standard is defined and that there are only minor differences between 601 and 709. However, there still is a difference, which I would really like to preserve.

After some twiddling about, I have figured out that the colour primary of 601 PAL can be archived by using BT 470 BG (which wasn't too surprising), while the colour primary of 601 NTSC will be set by using SMPTE 170 M. The matrix of 601 can be defined by using SMPTE 170 M as well.

It would be incredibly nice if BT 470 BG and SMPTE 170 M would be automatically associated with the BT 601 standard, so the colorprim and colormatrix fields will be set to the correct values and not left undefined when loading a file that has already parameters set for BT 601.

**Comment by JJKylee** [comment]
Since bt470bg and smpte170m are available for --colorprim and --colormatrix options in both x264 and x265, you can apply your findings in your encoder profiles after you open a file.

Or, maybe there's way to set encoder option values automatically at the program level based on VUI mediainfo values like StaxRip does on HDR videos. See [this issue](https://github.com/staxrip/staxrip/issues/319). I think your issue is very similar. Maybe @Dendraspis can help if he's interested and willing to. :)

**Comment by Dendraspis** [comment]
I'll have a look at it these days.

**Comment by Patman86** [comment]
A similar respectively this error has already been reported and for this reason the VUI parameters for BT 601 have been removed. Look here # 172

**Comment by Dendraspis** [comment]
@Patman86 
Perfect, couldn't find it.  :+1:

We have to pay attention to this issue and other side effects.

**Comment by Patman86** [comment]
The change can be reversed with the necessary adjustments. Then you should definitely test whether there are any color changes. That was the problem before.

Created pull request

**Comment by 44vince44** [comment]
@MikeBruschke there is a reason in x265 and x264 that BT.601 is not available : these are modern codecs and BT.601 is LEGACY.

In order to allow that, there is a RULE that all players respect:

1 If COLORMATRIX is specified in video stream or in container, then use the specified COLORMATRIX
2 if COLORMATRIX is not specified in video stream and not in container either, then:
   2a. if content is <720p, then the color matrix that will be used is BT.601
   2b. if content is >= 720p then the color matrix that will be used is BT.709

As a consequence:
- if you are re-encoding SD content without upscaling it to 720p or more: LEAVE color related VUI data UNDEFINED.
- if you are re-encoding SD content and upscaling it to 720p or more, then YOU MUST CONVERT color matrix to at least BT709, and specify in VUI what matrix you are using.

It must NOT be allowed to have 720p+ content with BT.601 in the metadata !

So please, @Patman86 , cancel the pull request !

**Comment by Patman86** [comment]
@44vince44 
THX, pull request canceled

**Comment by 44vince44** [comment]
@Patman86 Thanks to you ;-)

**Comment by JJKylee** [comment]
Thanks for the info, @44vince44 .

I googled and read _[this article](http://www.glennchan.info/articles/technical/rec709rec601/rec709rec601.html)_ about the difference between those two. Your explanation made it clear how to apply it in reality. 😄

**Comment by 44vince44** [comment]
You're welcome! The whole thing around color matrices is very simple actually, but it's hard to get comprehensive information about it. But fortunately I have good knowledge about that.

The most common error that is made is to omit the color matrix definition when downscaling from HD to 480p:
An HD video with BT709 will play in BT709 whether the color matrix is defined as BT709 or undefined (case 2b. in my explanation above). So when you downscale it to 480p, if you don't check that the matrix is set to BT709, your final video will play in BT601.
Resulting in a "more green, more purple" look.

**Comment by MikeBruschke** [comment]
@44vince44 Sorry for not getting back earlier. I'm just converting some SD footage for archiving purpose. No upscaling or anything like that. Good to know that undefined SD content will still be interpreted as BT601, however I still prefer to have the colour information stored in the metadata, even if it's just for the peace of mind alone.

For the time being, I have created extra profiles for SD footage, but, it would still be nice if the fields would automatically be populated with the right settings, like with HD footage that has its colour information predefined in the metadata.

**Comment by 44vince44** [comment]
@MikeBruschke 

Those fields that are not copied are not copied on purpose because they shoudn't be there in modern codecs.
You must not use the  BT 470 BG and SMPTE 170 M data any more! In your SD files, those shouldn't have been there from the beginning. Only in a very few rare cases they are justified.
Instead of putting lines of explanation, I suggest you do the following two encodings:

**Encode one:**
encode with x265 with everything about color and range is set to undefined => file 1

**Encode two:**
encode with x265 with manually placing color and range metadata (T 470 BG and SMPTE 170 M) as you see it in source file's mediainfo except BT601 that you leave undefined. BTW you can check that all muxers available (MKVToolnix etc) don't have the BT601 option when muxing.

Compare Encode1, Encode2 and the source....

**Comment by 44vince44** [comment]
Well considering the answer, I thought some things may have not been clear....

> Don't repeat yourself

Yes, sir! ;-)

**Comment by ValZapod** [comment]
> between them is rarely performed in real world

Yet it should be. BT.709 primaries are SMPTE C primaries are different (this has nothing to do with YCbCr)... Moreover if we are talking about BT.470 System M it even uses a different white point -- so chromatic adaptation must be applied.

> I think most modern devices assume the underlying color spaces are Rec. 709 if those VUI

That is wrong, they also assume sRGB transfer which is also wrong.

> correct that almost anything will default to Rec.709 if no standard is defined

Yet ffmpeg defaults to BT.601 matrix. And BT.709 primaries but...

> and BT.601 is LEGACY

No, it is not. As primaries may be. But not as matrix. JPEG uses it.

>Resulting in a "more green, more purple" look.
When decoding Rec709 matrix as Rec601, the Green bar is bright and over-saturated and the Red bar is dim... True. But that has nothing to do with primaries.
