### ISSUE TITLE
Is there an option in the settings of x265 that enable --limit-refs?

### ISSUE THREAD

**Issue by Asphxiated** [staxrip/staxrip#326]
Hey,

This is just a question because I can throw the --limit-refs 3 into the custom line but there are options that say "Limit Refs" with options of 0, 1, 2, 3 which is the typical range of options for --limit-refs but simply having this enabled will not turn 'limit-refs' on, I have to include the --limit-refs 3 into the custom command-line option in order for this to be enabled during encoding. Is this a bug or is the "limit refs" in the settings different from --limit-refs n ?

**Comment by JJKylee** [comment]
I guess it's a **bug**.

Although the default value for --limit-refs is 1, setting it to 3 in _x265 Options window_ makes it disappear from the command line. It means StaxRip regards 3 as the default value.

**Comment by Asphxiated** [comment]
but why does the encoder say that it is off during encode then if its on "by default" at level 3?

```
References / ref-limit  cu / depth  : 3 / on / on
```

would be 

```
References / ref-limit  cu / depth  : 3 / off/ on
```

unless I specifically put --limit-refs 3 in the custom window

**Comment by JJKylee** [comment]
StaxRip omits _--limit-refs_ option in the command line when you set its value to **3** in **x265 options window**.
But **x265** takes this command line and thinks that _--limit-refs_ is set to its default value, 1 since there's no _--limit-refs_ part in the command line.
So the encoding status you're looking at is x265 running the command line with _**--limit-refs 1**_.

This inconsistency between StaxRip and x265 will be fixed when this "wrong default value for --limit-refs in x265 options window" issue is fixed.

**Comment by Dendraspis** [comment]
@Asphxiated 
Which Preset do you use?  Medium, Slow, Slower, VerySlow, ... ?

**Comment by JJKylee** [comment]
> Which Preset do you use? Medium, Slow, Slower, VerySlow, ... ?

Ah! I forgot about the encoder presets.

According to x265 documentation, _--limit-refs_ is set to **3** in the **medium** preset. [Here](https://x265.readthedocs.io/en/default/presets.html).

So this may **not** be a bug. My bad.

**Comment by Dendraspis** [comment]
...if he/she uses the Medium preset. 😉

With the last x265 bugfixes I double-checked every preset related setting and I'm very sure there is no bug anymore.

This problem seems to be a misinterpretation of the encoder settings. 😃

**Comment by Asphxiated** [comment]
ok that is all fine and good but I still get an 

```
References / ref-limit  cu / depth  : 3 / off / on
```
if I do not add a --limit-refs 3 in the custom box whether I set Limit Refs to 3 or 2 or 1 in the settings so.... I still don't understand.

**Comment by Dendraspis** [comment]
Congratulations, you have found a bug in x265! 🎉 
This is because you use the default **Medium** preset. Regarding its documentation, `limit-refs 3` **should** be used, but `limit-refs 1` seems to be used instead. As far as I could see this bug only affects the **Medium preset** - if it is a bug!

So you only have the choice to choose another preset or specify this parameter in the custom section if you want `limit-refs 3`, because StaxRip will treat it as a default value and don't set it by itself.

**Comment by Dendraspis** [comment]
I opened an issue for this:
https://bitbucket.org/multicoreware/x265_git/issues/5/medium-preset-limit-refs

Let's see how long it takes.

At the moment I'm not changing anything in StaxRip, because it could be a bug or an outdated documentation. So every solution would be non-satisfying.

**Comment by stax76** [comment]
@Dendraspis 

When the preset Very Slow is selected, the command line shows --limit-refs 0 --max-merge 5, is it intended?

**Comment by Dendraspis** [comment]
@stax76 
Investigating...

**Comment by Dendraspis** [comment]
[Pull Request](https://bitbucket.org/multicoreware/x265_git/pull-requests/4) created - let's see if it will be reviewed/merged this year.  🙄 

Asking one of the well known x265 modders could be a possibility, but since StaxRip uses sometimes different versions between each version, I don't think this could be an appropriate and lasting solution.  😞

**Comment by Dendraspis** [comment]
@DJATOM added the fix recently to his modded version of x265 (https://github.com/DJATOM/x265-aMod), that is shipped with StaxRip since a while. So I think we can close this now without waiting for the official fix. 😁
