### ISSUE TITLE
AOMENC Better defaults with explanations.

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#361]
Change:
﻿Basic > Mode:  Change from One-pass to Two-pass
﻿
﻿Reason(s):
﻿  1. first pass is usually always very fast
﻿  2. Aomenc does not use alt ref frames when performing a single pass, therefore it is generally recommended to always perform a 2-pass encode, no matter what Rate Mode is chosen.
﻿
﻿---﻿﻿---﻿﻿---﻿﻿---
﻿
﻿Change:
﻿﻿﻿Basic > ﻿Rate Mode:
﻿  1. Rename "Q" to "Q (Constant Quality)﻿"
  2. Rename "CQ" to "CQ (Constrained Quality)"
﻿
﻿Reason(s):
﻿  1. This will help eliminate confusion because users coming from x265 might choose "CQ", expecting it to behave similar to x265's CRF (CQ), but it will result in a terrible quality encode due to it producing a constrained quality video.
﻿
﻿﻿﻿---﻿﻿---﻿﻿---﻿﻿---
Change:
﻿Basic > ﻿Rate Mode﻿﻿: Change from VBR to Q
﻿
﻿Reason(s):
﻿  1. Aomenc is less likely to be used for targeting precise filesizes, and more likely to be used for targeting quality at imprecise, yet small filesizes.
﻿
﻿---﻿﻿---﻿﻿---﻿﻿---﻿

﻿﻿Change:
﻿Basic > Bit Depth﻿﻿: Change from 8 to 10
﻿
﻿Reason(s):
﻿  1. 10bit is basically the new norm as, there are almost no new devices/software that do not support 10bit decoding
﻿  2. 10bit almost always produces a better quality encode with smoother gradients in skies.
﻿  3. It's safer to do 10bit final encode than 8bit, even if converting an 8bit source video into a 10bit result. There will almost always be fewer anomalies going with a 10bit final encode.
﻿﻿﻿---﻿﻿---﻿﻿---﻿﻿---

Change:
﻿Basic > CPU Used: Change from 8 to 4 (Medium)
﻿
﻿Reason(s):
  1. 8 Will produce a very low quality encode with poor VMAF scores in a lot of cases.﻿
﻿﻿﻿  2. 4 is a good balance in terms of speed and quality and produces good VMAF scores.
﻿  3.﻿﻿﻿ Charts show that cpu speeds 0-4 all have very close VMAF scores, but cpu speeds 5-8 begin producing much worse VMAF scores, therefore CPU 4 should be the default (in my opinion)

﻿---﻿﻿---﻿﻿---﻿﻿---
﻿
﻿﻿Change:
﻿Basic > CQ Level﻿﻿: Change from 0 to 25
﻿
﻿Reason(s):
﻿  1. 0 is lossless, and lossless should never be the default for a lossy encoder.  This shouldn't require a huge explanation, as the reasons should be obvious.
﻿  2. 25 is a good default quality level since it produces a high quality encode at a small filesize.  AV1 excels at higher CQ levels compared to x265, and AV1 is primarily used to create low filesize encodes at a target quality.  AV1 isn't well optimized for low CQ levels due to quantizer related denoising anomalies (especially on grainy content).  The goal of AV1 is to denoise / remove granular details without becoming a blocky, swimming mess, and it is better able to achieve that goal at higher CQ levels, until some kinks have been ironed out.  Believe me, I would LOVE to use a lower CQ level as a default, but CQ 30 just, across the board, produces more consistent results.
  3. CQ Level 25 provides good quality for both 8bit and native 10bit content.  According to user BlueSwordM, native 10bit content benefits more from a CQ level of 25 compared with higher CQ levels.  25 is going to be a safe starting point for content of either bit depth.
﻿
﻿﻿﻿---﻿﻿---﻿﻿---﻿﻿---
﻿﻿Change:
Analysis > Tile Columns: Change from 0 to 2
﻿﻿﻿Analysis > Tile Rows: Change from 0 to 1﻿
﻿
﻿Reason(s):
﻿  1. Assists with multi-threaded encoding by better utilizing cores on your cpu, with a downside of a small hit to encoding compression.  However, many AV1 users agree that the speed gained is worth the tradeoff.
﻿  3. Reddit user said this:
﻿    ﻿

"By keeping tiles as "square" as possible, you have the lowest edge/area ratio. Edges cause a small loss in coding efficiency.

So for a 16:9 video, 2x1, 2x2 or 4x2 is recommended depending on resolution. Most times 2x1 is good for 1080p, 2x2 for 1440p and 4x2 for 2160p and higher."
﻿
﻿  4. Since most content being encoded is still 1080p, then 2x1 is probably a safe default.

﻿

﻿﻿﻿---﻿﻿---﻿﻿---﻿﻿---

﻿﻿Change:
Slice Decision > Min GOP Size: Rename to Keyframe Min Distance
﻿﻿Slice Decision > Max GOP Size: Rename to Keyframe Max Distance

﻿﻿﻿﻿﻿Reason(s):
  1. This will better reflect the parameter name since AV1 refers to this as keyframe distance, rather than "Group of Picture" size
﻿  2. Easier to understand without inexperienced users having to resort to google to figure out what GOP means.

﻿﻿﻿﻿---﻿﻿---﻿﻿---﻿﻿---﻿﻿

﻿﻿﻿Change:
Slice Decision > Max GOP Size (i.e. Keyframe Max Distance): Change from 0 to 240
﻿
﻿Reason(s):
﻿  1. ﻿﻿I heard AV1 users at one point discussing this number being recommended by the AV1 developers, and also I believe this is a recommended number even for VP9.
﻿  2. It represents approximately maximum of 10 seconds between keyframes (if your framerate is approximately 24fps), otherwise keyframes could be placed at "who knows".  Better to specify than to leave it unspecified, since the AV1 parameter doesn't say what the default value is. 

﻿﻿﻿﻿﻿---﻿﻿---﻿﻿---﻿﻿---
﻿
﻿﻿Change:
Slice Decision > Lag in Frames: Change from 0 to 25
﻿
﻿Reason(s):
  1. ﻿--lag-in-frames parameter defines an upper limit on the number of frames into the future that the encoder can look
  2. I ﻿have seen people preferring 25 for AV1.
﻿  3. For VP9, a value of 16 was recommended.  I have no idea what the recommended or the max value is in AV1, but it seems safe to default this to 25.

﻿﻿﻿﻿﻿﻿﻿---﻿﻿---﻿﻿---﻿﻿---
﻿
﻿﻿Change:
Performance > Add a checkbox called "Automatically determine thread count".  Enabling this would gray out/disallow user input for "Threads", and the Thread count would be automatically determined based on the CPU's multi-threading capability.
﻿
﻿Reason(s):
﻿  1. 0 doesn't actually cause aomenc to auto multi thread.  0 disables multi-threading.
﻿  2. Sloppy Workaround: You could try setting default thread count to 8 since that's a safe number in 2020, since most people doing video conversion in 2020 have at least a quad core with hyper threading, however it would be best if StaxRip could automatically determine the cpu's maximum thread capability and automatically set this number accordingly.

﻿﻿﻿﻿﻿﻿﻿﻿﻿---﻿﻿---﻿﻿---﻿﻿---

﻿﻿﻿Change:
Misc 2 > Auto Alt Ref: Change from 0 to 1
﻿
﻿Reason(s):
﻿  1. ﻿﻿﻿﻿It is better to have "auto alt ref" Enabled because according to some AV1 users in discord, having it disabled will result in a "completely shit encode"
﻿  2. If you're doing a single pass encode, auto-alt-ref is actually disabled by default, but you can force it to be enabled by forcibly specifying it.
﻿  3. alt-ref frames are used when using a 2-pass encode by default if it is not specified.  Based on my limited understanding, you are generally better off just forcibly enabling this setting for most case scenarios.

**Comment by JJKylee** [comment]
> ﻿﻿Change:
> ﻿Basic > Bit Depth﻿﻿: Change from 8 to 10
> ﻿
> ﻿Reason(s):
> ﻿ 1. 10bit is basically the new norm as, there are almost no new devices/software that do not support 10bit decoding
> ﻿ 2. 10bit almost always produces a better quality encode with smoother gradients in skies.
> ﻿ 3. It's safer to do 10bit final encode than 8bit, even if converting an 8bit source video into a 10bit result. There will almost always be fewer anomalies going with a 10bit final encode.

Nope. It's not true.

Still lots of devices are 8 bits or even 6 bits. Esp. computer monitors. So in order to render a 10 bit video, we should rely on the **internal dithering process of the monitors** to avoid _banding_. The video stream is 'tweaked' in this process, and we watch the resulting dithered data.

And when the source is 8 bits, simply converting the bit depth to 10 bits does not give better quality.
Just because we change the 'container' does not mean we can increase the volume of the 'content'.
Suppose the source values are 01~10, but we decide to denote it by 001~010 based on the scale of 100. Does it mean the quality has improved?

Take a gif file with 32 colors. We decide to increase the number of colors that the palette can contain from 32 to 128. Does it mean that the original gif has suddenly 128 colors? Definitely not.

There's no magic in converting the bit depth from 8 to 10: unless the conversion is accompanied by **filter operations** such as color space conversion (_tone mapping_), interpolation, and so on. 8 bit data are just 8 bit data denoted by the 10 bit rule. The color space is still BT.709, not BT.2020 and the transfer function is still BT.709, not PQ. The color gamut does not expand at all by simply changing the bit depth.

Rather, it's highly probable that in order for lossy compression, this _narrow range data_ are prone to loss more easily by the 10 bit quantization process than by the 8 bit quantization process. As a result, 10-bit encoding is more likely to yield smaller sizes than 8-bit encoding. Many 10-bit encoding worshippers argue that this is the evidence that 10-bit encoding is better than 8-bit encoding for 8-bit sources. In this case, smaller file sizes mean more data loss. Nothing more.

10 bit encoding is most useful when it deals with 10 bit sources with a full data range/color gamut.

**Comment by Neltulz** [comment]
> 10 bit encoding is most useful when it deals with 10 bit sources with a full data range/color gamut.

I appreciate your verbose response, however this is something that is frequently discussed in the AV1 discord channel, and the consensus I've heard is that, for whatever reason, encoding 8bit footage in 10bit, nets better results, despite the seemingly illogical nature of doing so.  A lot of subjective and objective analysis is performed in the AV1 discord channel.  I will pass this response on to them and get back to you with more info.

But yes, when it comes to converting an (for example) 8bit image to a 16bit image, there should be no different in perceived quality because the most simplistic thing is occuring here.  When it comes to video encoding, there's a LOT more to consider, since AV1 is doing a lot of quantizer work which can be better perceived even if you go from 8bit to 10bit.  It's not black and white.

Allow me some time to get a better response from the AV1 community on this.

**Comment by Alkl58** [comment]
AV1, especially aomenc, has the issue, that it's denoising is way too aggressive, resulting in lot's of banding in flat (dark) areas.

Encoding 8bit content to 10bit does help alot avoiding these issues, the overall perceived quality increases, the overall needed bitrate decreases for the same quality. 

It's common knowledge in the Anime Community to use 10bit in HEVC, even if the source is 8bit. 

But yes, 10bit encoding is intended for 10bit content, but there are reasons why nearly all hevc anime encodes you find on "some sites" are encoded in 10bit. - even StaxRip defaults to 10bit hevc encoding, even if the source is 8bit.

Here a comparison: https://preview.redd.it/a7u89k4lag441.png?width=1920&format=png&auto=webp&s=e42d02f1b3536da1694da671e45b8b1cc6634255

Here my old encoder comparisons: https://www.reddit.com/r/AV1/comments/f1h2u1/aom_vs_rav1e_vs_svtav1_vs_x265_vs_vp9_vs_svtvp9/

The metrics VMAF, PSNR and SSIM show that the "quality" for the same bitrate increases, which is also visible to the naked eye.

**Comment by JJKylee** [comment]
> AV1, especially aomenc, has the issue, that it's denoising is way too aggressive, resulting in lot's of banding in flat (dark) areas.
> 
> Encoding 8bit content to 10bit does help a lot avoiding these issues, the overall perceived quality increases, the overall needed bitrate decreases for the same quality.

You mean deblocking and other in-loop filters in the encoder? If it's related to that, your argument makes sense, 'cuz those processes are basically about manipulating source data. Yeah, I've been forgetting about them... 😦 

I admit that my argument was technically too simplistic and naive. Then at this point, I'm curious: why does the same logic not hold for 10-bit to 12-bit conversion? Or why do many 10-bit encoders argue that 8-bit to 12-bit conversion is not superior to 8-bit to 10-bit conversion?

Well, anyway, thanks for the pointer and data. I've been feeling very against 10-bit encoding _worshippers_ because they almost always cannot provide proof or theoretical explanations but give arguments only. And I've seen many cases where people complain about 10-bit encoded contents because they can't play those on relatively old devices.

That said, I'm still in favor of the default bit depth of 8 bits. Like I said, there are still lots of cases where 8 bits are necessary. And converting from 10 bits to 8 bits for those requires another encoding hassle. ☹️

**Comment by Neltulz** [comment]
> I admit that my argument was technically too simplistic and naive. Then at this point, I'm curious: why does the same logic not hold for 10-bit to 12-bit conversion? Or why do many 10-bit encoders argue that 8-bit to 12-bit conversion is not superior to 8-bit to 10-bit conversion?

Probably because it's very easy to see the problems of banding at 8bit, and they resolve at 10bit.  The human eye can only see so much, there are diminished returns going from 10bit to 12bit if we're strictly speaking about end user viewing here and not intermediary production work.

> And I've seen many cases where people complain about 10-bit encoded contents because they can't play those on relatively old devices.

Fuck em. ;) :chonker_thumbs_up: /s

Sarcasm aside, if people really have problems regarding viewing 10bit videos on old devices, they need to convert it, or rely on something like Plex to do it for them.

> That said, I'm still in favor of the default bit depth of 8 bits.

I was too for a long time, until I started realizing the banding artifacts on low bitrate files.  I've spent a lot of time encoding x265 at > 8000 bitrate, with grain tune enabled, usually for grainy content.  These issues do not present themselves at high bitrates.  It's usually at low bitrate or high CQ levels that these issues become prevalent... in which case 10bit output depth resolves them nicely like magic.

> And converting from 10 bits to 8 bits for those requires another encoding hassle.

I digress.  If the problem is really that rampant, I'd have heard about it much much more than I have, which is practically never.

**Comment by JJKylee** [comment]
> Probably because it's very easy to see the problems of banding at 8bit, and they resolve at 10bit. The human eye can only see so much, there are diminished returns going from 10bit to 12bit if we're strictly speaking about end user viewing here and not intermediary production work.

That makes sense.
 
> Sarcasm aside, if people really have problems regarding viewing 10bit videos on old devices, they need to convert it, or rely on something like Plex to do it for them.. or (here's a crazy thought)... stop using old hardware/software.

Well, not all people can do that, but I can see your point.

> AV1 really is targeting the future.

Yeah, you've got a point there. I can't disagree. There's still a lot of time ahead.

**Comment by dali99** [comment]
As an added point AV1 has 10 bit decoding in it's base profile. All decoders **must** support 10 bit decode to be compliant AV1 decoders.

**Comment by BlueSwordM** [comment]
I would like to respond, and provide some insight.

**1. Change:
﻿Basic > Mode: Change from One-pass to Two-pass**

The reason for this as he has said, is that many powerful parameters in the reference aom encoder are disabled by default in 1-pass mode, such as auto-alt-reference frames. And since the 1st pass is very well multi-threaded and *fast*, for non realtime encodes, it is plain recommended to use 2-pass by default.

**2. ﻿Change:
﻿﻿﻿Basic > ﻿Rate Mode:
﻿ 1. Rename "Q" to "Q (Constant Quality)﻿"
2. Rename "CQ" to "CQ (Constrained Quality)"**

Q does not pose limits on bitrates for constant quality, so bitrate will go as high as necessary to keep the quality up, while CQ(Constrained Quality) does have a bitrate limit needed to be set.

**3. `Change:
﻿Basic > ﻿Rate Mode﻿﻿: Change from VBR to Q**

As always, only use VBR and 2-pass if you want to target a specific file size. So Q mode as a default would be good.

**4. ﻿﻿Change:
﻿Basic > Bit Depth﻿﻿: Change from 8 to 10**

This one is more subjective. Even from a native 8-bit source, encoding in 10-bit does provide higher efficiency and quality vs pure 8-bit, as it reduces losses made from denoising and produces less banding. From native 10-bit source, it's a no-brainer.
Overall, just recommending 10-bit is great, as AV1 HW decoding has to support 10-bit natively.

**5. Basic > CPU Used: Change from 8 to 4 (Medium)**

That is pretty obvious. Going from Speed 8 to Speed 4 provides a big quality boost while still being decently fast, unlike the lower presets.

**6. ﻿Basic > CQ Level﻿﻿: Change from 0 to 30**

I agree, but only for native 8-bit content. Native 10-bit has a different rate control path, and so, I would recommend lowering the CQ value from 30 down to 25 when presented with native 10-bit content(yuv420p101le).

**7. Analysis > Tile Columns: Change from 0 to 2
﻿﻿﻿Analysis > Tile Rows: Change from 0 to 1**﻿

Be very careful here. As you devs already know, the number of tile columns and rows are based off of log2. So, 2 tile columns would equal to 4 tile columns(2^2) and 2 tile rows would equal to 4 tile rows(2^2). 4x4 = 16 tiles, which does provide notable lower efficiency. I would just specify 1 tile column default(2^1=2 tile columns) and 0 tile rows default(2^0=1 tile row).

**8. ﻿﻿Change:
Slice Decision > Min GOP Size: Rename to Keyframe Min Distance
﻿﻿Slice Decision > Max GOP Size: Rename to Keyframe Max Distance**

I agree.

﻿﻿﻿**9. Change:
Slice Decision > Max GOP Size (i.e. Keyframe Max Distance): Change from 0 to 240**

Nah, do it simply. Set the default keyframe interval to like 10s worth of footage. For 30FPS, that would equal to 300. For 60FPS, that would equal to 600. You get what I mean.

**10. ﻿﻿Change:
Slice Decision > Lag in Frames: Change from 0 to 25**

This is basically lookahead. Giving it 25 frames of lookahead(lag-in-frames) is what I would recommend IMO.

**11. ﻿﻿Change:
Performance > Add a checkbox called "Automatically determine thread count". Enabling this would gray out/disallow user input for "Threads", and the Thread count would be automatically determined based on the CPU's multi-threading capability.**

I agree.

**12. Change:
Misc 2 > Auto Alt Ref: Change from 0 to 1**

In essence, auto-alt-reference frames are quite important to efficiency. So always forcing it to auto-alt-ref=1 is a good choice.
﻿

**Comment by Neltulz** [comment]
Updated my CQ-level recommendation to 25 as per BlueSwordM's information regarding bit-depth.

**Comment by Dendraspis** [comment]
Even though the whole menu changed:

> ﻿Basic > Mode: Change from One-pass to Two-pass ✔️ 

> Basic > ﻿Rate Mode:
﻿ 1. Rename "Q" to "Q (Constant Quality)﻿" ✔️ 
﻿ 2. Rename "CQ" to "CQ (Constrained Quality)" ✔️ 

> ﻿Basic > ﻿Rate Mode﻿﻿: Change from VBR to Q ✔️ 

> Basic > Bit Depth﻿﻿: Change from 8 to 10 ✔️ 

> Basic > CPU Used: Change from 8 to 4 (Medium) ✔️ 

> ﻿Basic > CQ Level﻿﻿: Change from 0 to 30

I set it to 24.

> Analysis > Tile Columns: Change from 0 to 2
  ﻿﻿﻿Analysis > Tile Rows: Change from 0 to 1

I stick to @BlueSwordM and set it to 1 / 0.

> Slice Decision > Min GOP Size: Rename to Keyframe Min Distance
﻿﻿Slice Decision > Max GOP Size: Rename to Keyframe Max Distance

Change it to ***Min/Max keyframe interval***.

> Slice Decision > Max GOP Size (i.e. Keyframe Max Distance): Change from 0 to 240

I set *Min = 23* and *Max = 250*. Should be fine for now and for almost everybody.

> Slice Decision > Lag in Frames: Change from 0 to 25 ✔️ 

> Performance > Add a checkbox called "Automatically determine thread count". Enabling this would gray out/disallow user input for "Threads", and the Thread count would be automatically determined based on the CPU's multi-threading capability.

🤔   But this options just limits max used threads. Setting it to 0 or e.g. 99999 should be also okay to use everything aomenc wants and the CPU has to give.

> Misc 2 > Auto Alt Ref: Change from 0 to 1 ✔️

**Comment by jorismak** [comment]
> 
> Nope. It's not true.
> 
> Still lots of devices are 8 bits or even 6 bits. Esp. computer monitors. So in order to render a 10 bit video, we should rely on the **internal dithering process of the monitors** to avoid _banding_. The video stream is 'tweaked' in this process, and we watch the resulting dithered data.
> 
> And when the source is 8 bits, simply converting the bit depth to 10 bits does not give better quality.
> Just because we change the 'container' does not mean we can increase the volume of the 'content' by doing so.
> Suppose the source values are 01-10, but we decide to denote it by 001-010 based on the scale of 100. Does it mean that we have more data than before?
> 

The reason (quality) wise to go for 10bpp with x264 / x265 when you can is because the codec switches to 10 bit precision, and that means rounding errors in the codec will be less visible / not visible.

I assume this is the same for aomenc and other AV1 encoders. For this to be true, the _internal_ bit depth in the codec algorithm needs to be 8bpp when doing a 8bpp encode and 10bpp when doing a 10bpp encode. If this is the case, the 10bpp will always produce better quality for the bitrate, even if the source was 8bpp.

Let's take something like the example you gave - but maybe more in my own words :P.

You have a series of values, in the range 0 - 31. This is what you are encoding. Sometimes - because of bitrate constraints - the codec will have to 'miss'. So the source contained the number '28', but the codec will end up with a '27'. Sometimes it misses big, and the '28' will end up as a '10'. This is the basic quality loss of encoding -> you can't match the source 1 to 1.

Ok, now we take that same source in 10bpp. So we get 4x times as much 'range' in the values. So our values are now between 0 and 127. _But_, the source was 8bpp, so what we are doing is scaling everything, multiplying it by 4. This is not creating quality (yet), this is just putting numbers across a different range. So, our number '28' from before will now be the number 112.

Now the encoder starts encoding it. Sometimes it misses small, sometimes it misses big. So sometimes our number '112' ends up being the number 111, sometimes our number '112' ends up being the number '42'.

Somewhere down the line we are viewing the 10bpp encode on a 8bpp system, like most of our desktops (excluding the 10bpp desktop pros for a moment :)). Maybe even displayed on a 6bpp FRC monitor (stop buying the cheapest monitors there are :)).

So, our 10bpp data is going to be scaled back to 8bpp data (with or without some dithering). So we are dividing everything back by 4 again. Our small error '111' divided by 4 ends up being 27.75, so probably will end up as 28... that is our original source value. The rounding error in the codec was so small that the 'error' disappeared in the bit-scaling and/or in the dithering. Our number '42' divided by 4 ends up being 10.5... that it's probably 11. Still a big error -> 10bpp can't do miracles :P.

Keeping everything the same (so the bitrate / final output size!!!) but going from 8bpp to 10bpp, will increase the quality. Even on a 8bpp source. If you are going to notice it, and if it's worth the extra computing power (for encode and for decode), is up to you of course.

Those 'small errors' are also what can cause banding. If you have a small range, small errors or more 'disruptive' then if you have a big range. And due to how our gamma is encoded (well, let's ignore HDR for a bit) a small step / error in the dark areas is more likely to be visible than in the bright areas. Those dark areas 'in the background' without much going on, and still a lot of dark blotches and banding going on -> 10bpp has a good chance of helping with that.

Of course, a good encoder will 'recognize' the situation and allocate extra bits to those areas. There is not much detail there, but we can't tolerate much error there because it will be really visible. This is the start of 'psycho-visual-modeling', and one of the things x264 has done right where other commercial H264 encoders around the time were failing.

It could also be the case that your source is just tricky or bad. Lots of film-grain in dark areas without enough bitrate to encode it all will yield a mess, 10bpp isn't going to fix that.

Also, banding (particularly in anime) could also be a problem already found in your source, not your encode. If you have a 8bpp source like a DVD with some challenging material with flat edges in the wrong places, your source might show banding. Encoding this as 10bpp isn't going to do anything, fix your source first! 
That's where the popular thing to do was use f3kdb in Avisynth -> scale up to 10bit or even 16bit, apply a smoothing algorithm to areas detected as 'banding'. Now you have a fixed source, but it's in 16bit. Howto encode this?

You can scale it down to 10bit (with or without dithering) and encode it as 10bpp. What you are doing now is 'leaving the problem up to the viewer, not the encoder' Since AV1 decoders are by nature supposed to support 10bit decoding this is a good option. That means that the viewing device has to decode the 10bpp material, dither it down to 8 (or even 6) bpp and view it to get rid of the banding.

You can also do the dithering yourself and get it down to 8bit like this, without much visible banding at all. But the dithering is a very small (VERY small) grain-like detail that is now important. Getting an encoder to not destroy that but to keep it alive requires some skillful tweaking of parameters and bitrate :). But in the end you can have a 8bpp file free of banding.

With the arrival of HDR most HEVC devices can play back 10bpp material just fine (like my 2017 budget Samsung TV, and all my recent phones), and modern codecs 'require' it from the start like AV1. So encoding 10bpp is in my opinion for sure 'the default' now.

**Comment by BlueSwordM** [comment]
Yeah, that's essentially it.

YUV 8-bit conversion has precision losses at the last conversion process, unlike RGB and 10-bit YUV for 8-bit content which don't, so that is another argument for using 10-bit.

That's why codecs like VVC and AV2(currently in the research/experimental department, so not final for a while) in the video world process everything in HBD(10-bit minimum with 16bpc processing), since it avoids those losses and makes the decoding process more streamlined. There's also JPEG-XL in the image world which processes everything at VHBD(up to 32-bit integers or floats), which means there's not much issue with precision all around.

All in all, with AV1, there are currently 3 reasons why you'd want 8-bit over 10-bit:
1. You want maximum efficiency at very very low bitrates.
2. Software decoding efficiency on x86_64 since until recently, there hadn't been any work done on SIMD for x86_64 CPUs.
3. Encoding 10-bit by nature is around 15-25% slower depending on the use case, but the nice efficiency boost over 8-bit is worth it.

Overall, if you can use 10-bit, I strongly recommend using it.

**Comment by rohitghali** [comment]
> AV1, especially aomenc, has the issue, that it's denoising is way too aggressive, resulting in lot's of banding in flat (dark) areas.
> 
> Encoding 8bit content to 10bit does help alot avoiding these issues, the overall perceived quality increases, the overall needed bitrate decreases for the same quality.
> 
> It's common knowledge in the Anime Community to use 10bit in HEVC, even if the source is 8bit.
> 
> But yes, 10bit encoding is intended for 10bit content, but there are reasons why nearly all hevc anime encodes you find on "some sites" are encoded in 10bit. - even StaxRip defaults to 10bit hevc encoding, even if the source is 8bit.
> 
> Here a comparison (aomenc 8bit vs aomenc 10bit): https://preview.redd.it/a7u89k4lag441.png?width=1920&format=png&auto=webp&s=e42d02f1b3536da1694da671e45b8b1cc6634255 (Source is 8bit)
> 
> Here my old encoder comparisons: https://www.reddit.com/r/AV1/comments/f1h2u1/aom_vs_rav1e_vs_svtav1_vs_x265_vs_vp9_vs_svtvp9/
> 
> The metrics VMAF, PSNR and SSIM show that the "quality" for the same bitrate increases, which is also visible to the naked eye.

The difference between 8bit and 10bit is day and night. Can clearly see the difference. 10bit should be the default. What would be the effect on file size? How much increase would it be?

**Comment by ls-milkyway** [comment]
Hey... what about `--coeff-cost-upd-freq  --mode-cost-upd-freq --mv-cost-upd-freq`???

What I have searched is `--mv-cost-upd-freq=2` is good option .......but the 2 others are also appearing .....even if I select `--coeff-cost-upd-freq=3  --mode-cost-upd-freq =3`???

Staxrip is showing whole lot of options & searching them all on the net is PITA ...specially when aomenc is still getting defeated by SVT-AV1 with far less options ,,,when analyzing with  video quality metrics??
