### ISSUE TITLE
AV1 chunk encoding (with aomenc etc.)

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#368]
**Is your feature request related to a problem? Please describe.**

This request is not directly related to a problem. Rather, it's related to performance of the app.

I did an encoding test with a trimmed trailer video (Iron Mask (2020) Trailer 2 cut, initial 34 seconds, 1080p24 AVC) with _NotEnoughAV1Encodes(NEAV1E)_ and _StaxRip_. The result is archived [here](https://drive.google.com/drive/folders/1ovk0NGgsEogssySAKZnwcOUH4L7RiN5w?usp=sharing).

As you may know, NEAV1E is capable of AV1 chunk encoding a la Av1an.

Using the _same_ aomenc build, I reach the conclusion that chunk encoding is definitely necessary in AV1 encoding for ordinary users like me who don't own high-end hardware.

The encoding settings are based on the recommendations discussed in #361 .

> OS: Windows 10 x64 Home 19041.508
> CPU: i5 7300HQ (4C 4T)
> aomenc version: 2.0.0-898-gda177b534
> StaxRip version: 2.1.4.8 Beta
> NEAV1E version: 1.3

- **Encode 1**: NEAV1E with 5 chunks

Encoding time: 00:19:37
Encoding speed: 0.69fps (1.85 times faster than Encode 2)
CPU usage: _100% flat_

- **Encode 2**: StaxRip with the same settings as in Encode 1

Encoding time: 00:36:14
Encoding speed: 0.38fps
CPU usage: _fluctuation_ b/w 45%-90%

- **Encode 3**: StaxRip with doubled threads

Encoding time: 00:26:07
Encoding speed: 0.52fps (1.39 times faster than Encode 2, but still slower than Encode 1)
CPU usage: _fluctuation_ b/w 50%-100%

Looking at the result, we can see that **chunk encoding provides not only faster speed but stable full CPU usage as well**.

**Describe the solution you'd like**

Implementation of chunk encoding in AV1 encoding just like x265 in StaxRip.

**Explain why the feature matters to you**

AV1 encoders are still in their early stage, and thus cannot seem to make full use of multi-threading as yet.
Therefore, chunk encoding can be a good solution in addressing this issue for the time being.
I'd greatly appreciate it if I could take advantage of AV1 chunk encoding in StaxRip.

**Comment by Neltulz** [comment]
Chunk encoding would be a great feature to have, however there are some important concerns.

Pros:
- Much faster encoding time if the user specifies correct number of threads per chunk that is simultaneously encoded.  I.e.  A quad core CPU with 8 total threads, should be split into 4 chunks with 2 threads per chunk (correct me if I'm wrong).

Cons: 
- Encoding extremely small files (60 seconds or less) lowers the efficiency so much, that the filesize increases.
- In order for chunking to work properly, it must be able to do some kind of scene change detection, and place the split at the scene change.  Otherwise, there will be motion animation anomalies where the 2 chunks were joined together.  This is less of an issue with fewer large chunks, but when dealing with more small chunks, this makes the problem more noticeable / prevalent.

Workaround for Quad core with 8 threads (Untested):
- Create 4 jobs, with cuts at exactly the spots that you want, precisely on scene changes (preferably).
- Ensure each job is multithreaded with 2 threads
- Launch 4 instances of Staxrip.
- Start one job per instance of StaxRip.

That *should* provide the speed benefit of chunking / simultaneous encoding..  It's tedious / cumbersome, but should work.

This is obviously not recommended for people with more than 8 threads, as doing this manually would be annoying.

**Comment by JJKylee** [comment]
@Neltulz , thanks for the detailed info.

To clarify my request, I'm _not_ demanding StaxRip should adopt chunk encoding as the _default/compulsory_ method of AV1 encoding. I'm just asking if chunk encoding can be introduced as an _option_ for AV1 encoding just like for x265.

**Comment by brendanw36** [comment]
>Encoding extremely small files (60 seconds or less when chunks are combined) lowers the efficiency so much, that the filesize increases.  Therefore, when encoding samples to gauge filesize / bitrate, I 100% do not recommend chunking.

Instead of forcing the program to make more splits than is efficient so that it uses all of the user's specified threads, I would suggest chunking on scene changes and if it doesn't result in as many chunks as the user has specified then just don't use all the threads.  You may also continue enforcing a minimum chunk length

>In order for chunking to work properly, it must be able to do some kind of scene change detection, and place the split at the scene change.  Otherwise, there will be motion animation anomalies where the 2 chunks were joined together.  This is less of an issue with fewer large chunks, but when dealing with more small chunks, this makes the problem more noticeable / prevalent.

FFmpeg (libavfilter) has built in scene detection you can use.  You can call FFmpeg with the select filter to detect scene changes and keyframes followed by the showinfo filter and then read the detected scene change's timestamps from stderr.  When chunking large videos it would be advisable to to sort the chunks by duration and encode the longest chunks first (at least in a thread pool implementation).  This way you can avoid waiting for one really long chunk to finish encoding after all your other chunks have finished.

People in the AV1 community (myself included) have extensively discussed the logistics of chunked encoding and would be glad to share anything we've learned about it.

**Comment by fmohican** [comment]
> Chunk encoding would be a great feature to have, however there are some important concerns.
> 
> Pros:
> 
> * Much faster encoding time if the user specifies correct number of threads per chunk that is simultaneously encoded.  I.e.  A quad core CPU with 8 total threads, should be split into 4 chunks with 2 threads per chunk (correct me if I'm wrong).
> 
> Cons:
> 
> * Encoding extremely small files (60 seconds or less when chunks are combined) lowers the efficiency so much, that the filesize increases.  Therefore, when encoding samples to gauge filesize / bitrate, I 100% do not recommend chunking.
> * In order for chunking to work properly, it must be able to do some kind of scene change detection, and place the split at the scene change.  Otherwise, there will be motion animation anomalies where the 2 chunks were joined together.  This is less of an issue with fewer large chunks, but when dealing with more small chunks, this makes the problem more noticeable / prevalent.
> 
> Workaround for Quad core with 8 threads (Untested):
> 
> * Create 4 jobs, with cuts at exactly the spots that you want, precisely on scene changes (preferably).
> * Ensure each job is multithreaded with 2 threads and tile-columns / tile-rows specified in a 2:1 configuration for 1080p content.
> * Launch 4 instances of Staxrip.
> * Start one job per instance of StaxRip.
> * That _should_ provide the speed benefit of chunking / simultaneous encoding..  It's tedious / cumbersome, but should work.
> * This is obviously not recommended for people with more than 8 threads, as doing this manually would be annoying.

I tried that with 16c32t cpu, work like charm, but as you said, is annoying.

**Comment by Dendraspis** [comment]
Is aomenc enough or do you really want/need all?   😉

**Comment by 44vince44** [comment]
imho aomenc would be enough (I still wonder why people use FFMPEG for those when you have directly the encoder)...

**Comment by JJKylee** [comment]
I agree. _aomenc_ is more than enough for now. 😅

**Comment by Dendraspis** [comment]
Okay, so we can close it.   🎉 🥳
