### ISSUE TITLE
[Question] How to keep Subtitle Name

### ISSUE THREAD

**Issue by HartLarsson** [staxrip/staxrip#38]
hi,

i still running the latest version 2.0.3.0 and when i try to convert a mkv h264 to x265 I've found that the subtitles names are all blank. Every time i need to manually insert the original name using the Container Option:

![image](https://user-images.githubusercontent.com/16102074/63420754-abf0a200-c407-11e9-8324-c20c8fec4a89.png)

Also the Forced field is lost.

There is a way to keep that information by default to avoid the manual editing every time?
If not, could be anice implementation for a future version (if is possible)

Thanks

**Comment by stax76** [comment]
Thanks for the feedback. Next build has:

- the title (track name) wasn't detected from demuxed audio and subtitle tracks

I cannot reproduce that forced is lost. In order to examine this I would need to see a log file.

The demuxer should write _forced to the file name and the muxer should detect this, it works here.

**Comment by HartLarsson** [comment]
i've tried to re-rendering a h264 with a forced subtitle (i'm sure is forced) and i can say forced flag is keep.
Was a wrong report before.

but sub titles are not saved.

from mkvtoolnix:
![image](https://user-images.githubusercontent.com/16102074/63502301-92b22900-c4cd-11e9-8603-37e7bc51f1b9.png)

after processing in staxrip:

![image](https://user-images.githubusercontent.com/16102074/63502419-d3aa3d80-c4cd-11e9-9d12-07e24b762f86.png)

So i  will wait the next release with the track name import feature :)

thanks for your work!
