### ISSUE TITLE
Max number of parallel processes not respected?

### ISSUE THREAD

**Issue by FootieB0y8** [staxrip/staxrip#382]
Hello!

I've used StaxRip before and I've found it pretty easy to use. Now I want to try a different usage scenario but I'm having problems :/

I'm using StaxRip 2.1.3.0. What I'm trying to do is run StaxRip from CLI.

I would like to:

Add a job to StaxRip from CLI (or Powershell)
StaxRip start working on that job.
I then add another job via CLI, and StaxRip starts working on that.
I would like to repeat this BUT I want StaxRip to respect the 'Max number of parallel processes' that is set in Settings -> General. Which, in my case, is currently '2'.

I can't get this to work though. StaxRip keeps on Starting new jobs, even when there are 2 encodes currently being done.

The commands I'm using are:

StaxRip -LoadTemplate:TEST1 C:\Users\***\Desktop\video.h264 -StartEncoding

The template 'TEST1' is just a simple resize 1080p to 1280x720 x264 encode.

What am I doing wrong?

Thanks!

**Comment by 44vince44** [comment]
The max number of parallel processes means that in the same job being executed, you can't have more than 2 processes. For instance, audio and video, or video chunk 1 and video chunk 2 (supported by x265 "Chunks" in Input/Output options).
If you start n staxrip from CLI you'll have n processes running ! This is handled by the system.

**Comment by 44vince44** [comment]
If you want to achieve processing of a job list by two staxrip processes ONLY, then you have to work otherwise:
1. create a job list from the UI of CLI (add JOBS not start encoding)
2. once your job list is complete, open two staxrip UIs, open the job list, and for each of them start executing the job list. There you'll have only two parallel staxrip processes working.
