### ISSUE TITLE
StaxRip does not recognize metadata in video container that indicates video rotation

### ISSUE THREAD

**Issue by Zcehtro** [staxrip/staxrip#390]
**Bug description**
Video files that have rotation metadata are viewed incorrectly when processed by StaxRip.

StaxRip does not recognize the metadata for video rotation found in Mediainfo dialog:
![2020-12-10 23 53 01 _ mpc-hc64 _ cXp4UhF5iT](https://user-images.githubusercontent.com/10564090/101856988-3ef5a400-3b45-11eb-8df3-fda58b091c73.png)

Said metadata is even recognized by Windows as well:
![2020-12-10 23 55 28 _ explorer _ 7hZuJqz3K6](https://user-images.githubusercontent.com/10564090/101857006-487f0c00-3b45-11eb-8698-a70379157044.png)

**Expected behavior**
Read orientation metadata and rotate video resolution in avisynth
OR
work with video as is and pass on video rotation metadata to output container.

Perhaps offer option to choose, but default to 1st option if user does not want to be asked or wants to change later.

**How to reproduce the issue**

Occurs on any video that holds said metadata.

**Provide information**

Nothing more that I currently have.

**Notes before posting**
Understood.

**Additional context**
Been using this program since 2016.
Like it so much more than Handbrake.
Tyvm for the hard work!

**Please be as clear and as detailed as possible**
Will do!

**Comment by 44vince44** [comment]
This looks that something that should be implemented as the Aspect Ratio is currently implemented:
Rotate metadata taken into account when muxing, but also when previewing (F5 preview and player) ! It should work as currently Aspect Ratio is working, with an option inside the Image Options of "Target Angle", which would work similarly to Target DAR and Target PAR, right ?

**Comment by JJKylee** [comment]
> EDIT: PROBLEM => mkv does not support officially Rotate tag, and the --projection-pose-xxx switches that are supposed to do rotation have no effet :-((((

Yeah. For your reference, here's a [post on Reddit](https://www.reddit.com/r/Matroska/comments/i5yorw/autorotate_matroskamkv_with_tags_during_playback/) explaining how to put a `rotate` tag as a video metadata via an `xml` file using `mkvpropedit.exe` for `mkv`. But of course it depends on the player whether this `rotate` tag in `mkv` will be respected or not. MPC-XX and PotPlayer seem to be supportive, but mpv developers seem to be very against this idea of putting an (officially-not-supported) `rotate` tag in `mkv`. See [this](https://github.com/mpv-player/mpv/issues/6718). (You can find [a 'rotated mkv video' sample](https://sites.google.com/site/dp79lakas/home/allpurpose/sample.mkv?attredirects=0&d=1) there as well.)

Anyway, this is somewhat off topic.

Per @Zcehtro's post, I also think it'd be desirable if StaxRip showed the source video at the correct angle _automatically_ so that crop, preview, and other video processing jobs can be done in the perspective the source video was intended to be viewed. Well, passing on the source rotation metadata seems to be easier, but I believe auto-rotation is more convenient and natural for video processing jobs.

That said, in order to view the source video at the correct angle as intended, rotation tag parsing should be supported by **source filters**. That's because video frames are _interpreted(decoded)_ and served in the beginning by source filters in AVS and VS. So **it's basically an issue not related to StaxRip itself**.

If a source filter does not support this feature, you can always rotate the video frames using a rotation-related filter. I.e. for AVS, native filters `TurnLeft`, `TurnRight`, or [`Rotate`](http://avisynth.nl/index.php/Rotate). For VS, [`Transpose`](http://www.vapoursynth.com/doc/functions/transpose.html) is natively available.

**Comment by Dendraspis** [comment]
@Zcehtro 
Can you give us a small video file with 90° or 270° rotation for testing?

**Comment by Zcehtro** [comment]
> @Zcehtro
> Can you give us a small video file with 90° or 270° rotation for testing?

Sure.

**Comment by Zcehtro** [comment]
Here:


https://user-images.githubusercontent.com/10564090/106534131-615eca80-64c1-11eb-9ce8-a486ad6982a0.mp4

**Comment by Zcehtro** [comment]
For reference, this is a user created video in WhatsApp.

**Comment by Dendraspis** [comment]
Thanks for the sample. Seems like there is a solution, but it might take a while....

**Comment by 44vince44** [comment]
@Dendraspis It's only a tag!
In the whole processing chain, the video must be considered without the rotation tag. Video must be handled as it is. WxH.
Then for the tag:
case 1: mp4 (no problem)
case 2: mkv MUST PUT a warning that the rotate tag is unofficial in mkv !

**Comment by Dendraspis** [comment]
@44vince44 
Thanks for taking care of me.  😁   But I have a different approach in mind.  😇 
Let me try something ....

**Comment by 44vince44** [comment]
Can't wait to see what you have in mind 😍

**Comment by Dendraspis** [comment]
Nothing special, bit I have to think about two possible solutions with their pros and cons. 🤔

**Comment by 44vince44** [comment]
> Sounds like you are willed to test it. 😁

you seem surprised 🤣

**Comment by Dendraspis** [comment]
@44vince44 , @JJKylee 

First step is done - and what a step!  😠 
***No automatism yet***, but it would be nice, if you could test this. I suggest using a copy of an existing StaxRip folder and change the exe - you have to use StaxRip without a settings file, so that the new *things* will be visible. You'll see them on the left list.

Normally rotations would not be applied to source informations, cropping, etc. but in this build it is. This leads to another issues, but tell me what you think.

Tested VPY only, but AVS should also work. The provided test file above is perfect for testing.
[StaxRip v2.1.7.5D_Rotation1.zip](https://github.com/staxrip/staxrip/files/5921802/StaxRip.v2.1.7.5D_Rotation1.zip)

**Comment by JJKylee** [comment]
Like you said, the source video is _not_ automatically rotated contrary to what the video option promises. 😁

![StaxRip v2 1 7 6D_Rotation1_Options-Video_20210203](https://user-images.githubusercontent.com/3157518/106838542-5cc91c00-6651-11eb-9a88-302eefb02965.jpg)

Oh, I see a big **IF** there: _when possible_. 😓

But at least it's a good start, though. Adding a new category, **Rotate**, to the filter profiles is not bad.

![StaxRip v2 1 7 6D_Rotation1_Rotate_as_new-filter-item_20210203](https://user-images.githubusercontent.com/3157518/106838733-b03b6a00-6651-11eb-8de9-6f7baebc530b.jpg)

Considering the work flow, putting _Rotate_ category right beneath _Source_ looks better, but never mind. Users can arrange the order.

BTW, if the rotated source is _portrait_, **Crop** window does not show the correct AR. Is it normal or has it been there before this? 😶

![StaxRip v2 1 7 6D_Rotation1_Rotate_Crop_20210203](https://user-images.githubusercontent.com/3157518/106839542-3efcb680-6653-11eb-8dd1-9458b60e57e3.jpg)

Anyway... Good job, man~ 😄

**Comment by Dendraspis** [comment]
> BTW, if the rotated source is _portrait_, **Crop** window does not show the correct AR. Is it normal or has it been there before this? 😶

It might have to do something with limitations. But yes, this is something that has to be checked later. 
But what about the source information and resize slider?

> Considering the work flow, putting Rotate category right beneath Source looks better, but never mind. Users can arrange the order.

For better usage I decided to sort the entries by name - it's a lot faster. 😀

> [..] contrary to what the video option promises.

This checkbox was my starting point. 😂 Totally forgot it! 🤣

> Adding a new category, Rotate, to the filter profiles is not bad.

If I fail, this category will persist to make it easier to do it by hand. 😎

**Comment by JJKylee** [comment]
> But what about the source information and resize slider?

I forgot to check it out. Maybe @44vince44 can help here. 😆

**Comment by 44vince44** [comment]
@Dendraspis @JJKylee I'm sorry for reacting late to this. Nut now i am testing this solution. The idea works, except for the case that video is not reencoded (copy/mux).

Solution 1 (Dendrapsis): Auto-rotate by inserting a filter that really rotates the image
+Pros: video is rotated for real, pixels are rotated, better in most cases
-Cons: does not work in operations where videos are copy/muxed

Solution 2 (44vince44): only handle the metadata tag rotate
+Pros: works as expected for mp4, including when video is copy/muxed
-Cons: support in mkv is unofficial, most players don't recognize that tag

As I usually don't process videos from smartphones in Staxrip (because there is also the problem of variable frame rate, that is not handled correctly in Staxrip, or maybe I don't know how to work with it), I don't know what solution is better. But it seems the solution of @Dendraspis is better (unless one day mkv supports the rotate tag)

**Comment by 44vince44** [comment]
BTW I forgot to say: i have nothing to add to @JJKylee 's comment. Everything is working fine, except the crop WINDOW orientation!
but the crop parameters apply properly as they must.

**Comment by stax76** [comment]
@Dendraspis 

For auto rotate it should probably be put into the source filter like this code:

https://github.com/staxrip/staxrip/blob/master/Forms/MainForm.vb#L2415

There should probably be a new stable release soon.

**Comment by Dendraspis** [comment]
@stax76 
I doubt that this would work as expected. When I started some tests at the beginning of my coding, there were some issues when rotation is made only there.  🤔

**Comment by Dendraspis** [comment]
Okay, seems the new feature is working.  🥳 

You have to use StaxRip without a settings file (again) to get the *full experience*. 
[StaxRip v2.1.7.9D_Rotation2.zip](https://github.com/staxrip/staxrip/files/5943681/StaxRip.v2.1.7.9D_Rotation2.zip)

The Crop window has to be improved yet ... 🙄

**Comment by 44vince44** [comment]
I'll test this evening !  maybe by that time the crop window will work 😁

**Comment by Dendraspis** [comment]
@44vince44 
I hate myself for making your thoughts true!   😜 

[StaxRip v2.1.7.9D_Rotation4.zip](https://github.com/staxrip/staxrip/files/5944040/StaxRip.v2.1.7.9D_Rotation4.zip)

**Comment by 44vince44** [comment]
I love you for that, exactly 😍 Ok I'll do the tests just a bit later !!

**Comment by Dendraspis** [comment]
@44vince44 
@stax76  couldn't wait and already merged it 😁 , so the next beta is going to have this feature included. 

But if you can't wait to test it, here the latest build:
[StaxRip v2.1.7.9D_Rotation5.zip](https://github.com/staxrip/staxrip/files/5945834/StaxRip.v2.1.7.9D_Rotation5.zip)

**Comment by 44vince44** [comment]
@Dendraspis   what's the difference between Rotation4 and Rotation5?
Rotation4 seemed ok (including crop), still doing some tests...

**Comment by Dendraspis** [comment]
Almost nothing ... @stax76  added compatibility for when old settings are used.

**Comment by 44vince44** [comment]
you mean it has all the commits after 2.1.7.9 ?

**Comment by Dendraspis** [comment]
Sure - it's 10min old.  😁

**Comment by Dendraspis** [comment]
Ah, you were irritated because *Rotation1* was based on v2.1.7.5.  😁 
Therefore I include the official StaxRip version, that was used as base. 😉

**Comment by 44vince44** [comment]
🤣

**Comment by stax76** [comment]
@44vince44 

For the new feature to work there must be a category with exact name _Rotation_ and there must be filters in it with exact names _Left, Right, Upside Down_, if that is not present the feature is silently skipped.

```
[Rotation]
Left = TurnLeft()
Right = TurnRight()
Upside Down = Turn180()
```

**Comment by 44vince44** [comment]
@Dendraspis the test I am doing is:

- mod a video with exiftool so it gets different rotation values (because I didn't find videos with rotation on the internet, so I create them)
- do a couple of tests in staxrip.

The values of rotation are:
- 0 : the tag disappears, which is expected
- 90 : this was our main testing video
- 180 : no comment
- 270 : no comment
- minus90 : the tag is written 270 (which is expected, and conform with gpac docs, where rotation is n*90, where n positive integer)

**Comment by 44vince44** [comment]
@stax76 @Dendraspis this feature is working perfectly! all tests were successful!
