### ISSUE TITLE
Error with Autoupdate

### ISSUE THREAD

**Issue by Mister-XY** [staxrip/staxrip#394]
Hello, if I want to use the new "Auto Update" function, I get e.g. an updated version of 7z will appear. As soon as I confirm with OK, I get this message "URIFormatExecption". I have already started Staxrip as admin, but I get the same error.
```


------------------------- System Environment -------------------------

StaxRip    : 2.1.5.1
Windows    : Windows 10 Pro 2009
Language   : German (Germany)
CPU        : AMD Ryzen 5 PRO 4650G with Radeon Graphics
GPU        : AMD Radeon(TM) Graphics
Resolution : 1920 x 1080
DPI        : 96

------------------------------ Exception ------------------------------

System.UriFormatException: Ungültiger URI: Das URI-Format konnte nicht bestimmt werden.
   bei System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bei StaxRip.DownloadForm..ctor(String url, String path) in D:\Projekte\VB\staxrip\Forms\DownloadForm.vb:Zeile 18.
   bei StaxRip.ToolUpdate.Download(String url) in D:\Projekte\VB\staxrip\General\ToolUpdate.vb:Zeile 58.
   bei StaxRip.ToolUpdate.VB$StateMachine_23_Update.MoveNext() in D:\Projekte\VB\staxrip\General\ToolUpdate.vb:Zeile 47.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

![Screenshot 2020-12-15 180911](https://user-images.githubusercontent.com/10309056/102247903-de79b480-3f00-11eb-87c3-94430b5e9a3f.jpg)

**Comment by stax76** [comment]
It's because the download URL is not defined, the build I just uploaded fixes it by disabling the auto update.

But careful, it's not working with the zip tool, this is a 10-year-old legacy tool, not longer maintained I think, maybe we have to look for an alternative due to security, you cannot update this, the tool auto update feature is generally experimental and should only be used by pro users.

As a rule of thumb, it mostly only works with tools on github, that is many, there are some exceptions, mkvtoolnix is downloaded from videohelp.com, fosshub is not supported... and also not mediafire... it's rocket science to support those sites...

**Comment by 44vince44** [comment]
@stax76 7zip is still under dev. Latest stable version is form 2019!  And I agree, such tools must **not** be autoupdated.
I think NO tool should be autoupdated, because sometimes some tools introduce changes in syntax or parameters.
And that was the logic that gave a sense to portable avisynth and portable vapoursynth.

**Comment by stax76** [comment]
> 7zip is still under dev. Latest stable version is form 2019! or am i missing some specific thing ?

The main problem is that Microsoft does not have an efficient (de)compression tool. PowerShell supports only the zip format.

People that install 7zip have an up-to-date CLI tool available, I think they don't offer a small CLI only package for download unfortunately. About the CLI tool that gets installed I don't know about the license for distribution and about the file size.

> I think NO tool should be autoupdated, because sometimes some tools introduce changes in syntax or parameters.

Yes, maybe we need to hide it via hidden shortcut. 

And it should be documented... we need to think about what needs to be done in order to find people willing and enjoying contributing to the docs, we should use Markdown instead of rest format, the current experience is poor.

**Comment by 44vince44** [comment]
@stax76 : here is the license for 7-zip software.
There are two licenses in the 7-zip package:
-license for 7z.dll that we DON'T need
-license for "all others", including 7z.exe the cli, that we need

The license for "all others" is GNU LGPL, quote:

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You can receive a copy of the GNU Lesser General Public License from
    http://www.gnu.org/

**Comment by Dendraspis** [comment]
But I would bet 7z.exe needs 7z.dll to work. :thinking:

**Comment by 44vince44** [comment]
> 
> 
> But I would bet 7z.exe needs 7z.dll to work. 🤔

No, fortunately, it doesn't !

**Comment by stax76** [comment]
I found now it's still maintained and updated it to v19.0.

And I disabled the auto update for 7zip.

**Comment by 44vince44** [comment]
Yes I saw that in the commit! great find ! It is still under development and it's available in the binary archive called "Extras".
And 7za.exe does not require the dll, so it's free of copyright stuff.
