### ISSUE TITLE
Add Anime4KCPP to staxrip for upscale animation

### ISSUE THREAD

**Issue by SkyAFS** [staxrip/staxrip#398]
Hi, i was wondering if would be possible to implement the avisynth version of Anime4KCPP

Directly inside staxrip build, i'm trying my best to put the plugin manually but with no success, the reason for this is that i always use staxrip since the beginning and i don't have experience about how the code work, and i think im doing something wrong,

for people who don't know what the plugin is, is a upscaler in real time to 4k used for animation, and the results are very good,

i also would like to suggest the add of any line darkening filter, and a dark theme for the GUI, i believe this are the only 3 things i fell that is missing on staxrip

this is the link for the github of the plugin and i don't think will be difficult for the developers to put inside the build, im just to dumb to figure out, if this is not implemented im probably create another topic lately trying to find why my code is not working hahahahahah

Please give my this birthday and christmas present :)

Henrique Sena, Brazil, 31 Years old. big fan since 2006

https://github.com/TianZerL/Anime4KCPP/releases

**Comment by stax76** [comment]
There is a 50 MB DLL, so it's too large to include into the distribution. So the only thing we can do is helping you with the integration, generally there are many ways, auto loading, manual loading, add a filter profile etc.

There is something in the docs about filter profiles here:

https://staxrip.readthedocs.io/usage.html#filter-profiles

Since it has multiple DLLs some advanced steps might be needed like modifying the path environment variable.

I tried hard to make it run on avisynth, but it gives an access violation, so there is a bug somewhere, and it's unlikely on our side, you have to request support from the authors.


It runs on vapoursynth however.

```
core.std.LoadPlugin(r"C:\Anime4KCPP_VapourSynth\Anime4KCPP_VapourSynth.dll", altsearchpath=True)
clip = core.anime4kcpp.Anime4KCPP(clip, GPUMode = 1, ACNet = 1, zoomFactor = 2, HDN = 1, HDNLevel = 2)
```

**Comment by SkyAFS** [comment]
I tried putting like you said, but i only get errors, could you send me a template so i could see how  should look like, because i already put the folder of the dll in the path variables, and i put the dll on the vaporsynth autoload folder, but i still cant get to work, i dont know if maybe im putting wrong on the edit profiles, 

i would like a screenshot of the code on your edit profiles, and a template please, i think that with this two things i can figure out on my one the rest, vaporsynth is more greek than avisynth already was

if its not to much trouble, i can even enter on discord (Sky#4483) or skype, im trying to remaster something that i have that i will need in the end of the year for a project

**Comment by stax76** [comment]
Did you maybe use the wrong plugin autoload folder? You can open it in the main menu at:

Tools > Folders > Plugins

**Comment by SkyAFS** [comment]
nop. the folder is right, i actually open the same way, just paste everything inside whitout any other folder

**Comment by stax76** [comment]
In my opinion putting all those DLLs in the plugin autoload folder is very bad for performance because not all those DLLs are plugins but VS will try to load them as plugins. And it's also very messy, a plugin that has multiple files should have an own directory, it's the only way to know that these DLLs belong together. I rather suggest not to use autoloading but manual loading.

You should however be able to delete all DLLs that contain 140 in the filename because these DLLs are VC++ runtime DLLs, and they are likely already on your system. In case they are not on your system you can still delete them because staxrip has its own VC++ all in one package included (Apps\Support\VC) and always adds it to the PATH environment variable so the OS can find it.

All you really have to do is create a filter profile which allows you to select the filter in the context menu.

First you have to load a VapourSynth filter setup using the menu:

Filter Setup > VapourSynth

Then you can open the Filter Profile editor in the menu, the menu item for that is named _Profiles..._

In the profile editor search the resize section [Resize], then you can add your profile like so:

```
Anime4KCPP =
    import os.path
    # Add folder path to PATH env var
    os.environ["PATH"] = r"C:\Anime4KCPP VapourSynth\dll" + os.pathsep + os.environ["PATH"]
    core.std.LoadPlugin(r"C:\Anime4KCPP VapourSynth\dll\Anime4KCPP_VapourSynth.dll", altsearchpath=True)
    clip = core.anime4kcpp.Anime4KCPP(clip, GPUMode = 1, ACNet = 1, zoomFactor = 2, HDN = 1, HDNLevel = 2)

```

I don't know why the folder path must be added to the PATH env var because I thought that exactly what altsearchpath=True will do. I will ask at doom9 and get back to you.
