### ISSUE TITLE
Vapoursynth LSFmod has a new dependency

### ISSUE THREAD

**Issue by ukharley** [staxrip/staxrip#412]
The LSFmod module in havsfunc has a new dependency, cal.dll ( https://github.com/HomeOfVapourSynthEvolution/VapourSynth-CAS )
I dropped the dll into the  <Apps\FrameServer\VapourSynth\vapoursynth64\coreplugins> folder which works for me.
You'll know it's proper place.

**Comment by stax76** [comment]
Thanks for reporting, CAS will be included in the next build.

An error in the LSFmod defaults was also fixed.

I do not recommend adding, removing or replacing any file in the Apps folder because everything will be lost if you update staxrip.

Copy new files over old files is generally not a good idea.

There is another vapoursynth plugin directory, you can find it in the menu:

Tools > Folders > Plugins

It' located at:

`<settings>\Plugins\VapourSynth`

**Comment by stax76** [comment]
Changelog

https://github.com/staxrip/staxrip/blob/master/Changelog.md

Download

https://staxrip.readthedocs.io/introduction.html#beta
