### ISSUE TITLE
x265 failed to load VapourSynth

### ISSUE THREAD

**Issue by lifta19** [staxrip/staxrip#471]
D:\PortableApps\Video\StaxRip\Apps\Encoders\x265\x265.exe --crf 21 --preset slow --output-depth 10 --no-rect --aq-mode 3 --subme 5 --bframes 8 --rc-lookahead 80 --colorprim bt709 --colormatrix bt709 --transfer bt709 --deblock -3:-3 --no-sao --no-strong-intra-smoothing --output C:\Users\Rain\Desktop\test_temp\Video_out.hevc C:\Users\Rain\Desktop\test_temp\Video.vpy
vpy  [error]: failed to load VapourSynth
x265 [error]: unable to open input file <C:\Users\Rain\Desktop\test_temp\Video.vpy>
--------------------------------------------------------------------------------------------------------------------------

When you copy and run the command line, the plug-in fails to be loaded.

Works by copying x265.exe to the FrameServer\VaporSynth folder

**Comment by JJKylee** [comment]
This is because `x265` does not support a custom `VSScript.dll` path. But @DJATOM's most recent mod version fixed this issue by introducing a custom option as follows:

```
--reader-options library=<PATH-TO-PORTABLE-VS>\VSScript.dll
```

Try [his most recent build](https://github.com/staxrip/staxrip/issues/464#issuecomment-763819976) and include the above extra option to your copied command line.

Or you could [make a soft link](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink) to `VSScript.dll` in the `x265` folder.

Another method is to choose `vspipe` in the `x265` `Input/Output` options category.

**Comment by 44vince44** [comment]
@lifta19 
Please use the templates for reporting a bug.
The least you could mention is the version of Staxrip you're using.
Get latest beta here (links available on the page) : https://staxrip.readthedocs.io/introduction.html#download

**Comment by lifta19** [comment]
2.1.7.3 Use beta. 
Only 2-pass encoding sometimes copies and executes command commands.
And x265 used Patman build.
mklink seems to be the most convenient way

**Comment by stax76** [comment]
It's fixed in the last Beta.
