### ISSUE TITLE
bad behaviour (number 2) with preview window when opened from the Code Editor window

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#493]
**Describe the bug**
If you open a preview FROM the Code Editor window and then close the Code Editor window, but NOT that preview, then you get this Warning:
![SNAG-0000](https://user-images.githubusercontent.com/17828567/107145274-1c1b1c80-6949-11eb-8fee-b3c04b48ed6f.jpg)

As you can see, there is nothing involving any frame rate here:
![SNAG-0001](https://user-images.githubusercontent.com/17828567/107145320-4a98f780-6949-11eb-90f5-1c0886361656.jpg)

The message is misleading !

**Suggested fix**
Maybe only changing the error message could be enough, add to it "Closing any preview window still open could fix that."

**Comment by stax76** [comment]
Unfortunately I cannot reproduce it.

**Comment by 44vince44** [comment]
@stax76 : here are the exact steps

1) Load video
2) Open CODE EDITOR
3) Press F5 from inside the code editor, a preview window opens
4) Create a range in this preview, do NOT close the preview
5) Close code editor by pressing OK

**Comment by Dendraspis** [comment]
🤔   I can't reproduce it, too.  After closing the Code Editor window, I'm still able to close the Preview window.

**Comment by Dendraspis** [comment]
🤔 I can't reproduce it, too. After closing the Code Editor window, I don't get any error messages.

Seems like it must have to do something with your filters.  🤔

**Comment by JJKylee** [comment]
Ditto. With a simple script (only DGSource), I can't reproduce the error.
I also think it may be related to the filters in use. 🤔
I will join you if I run into a similar error when I use multiple filters.

**Comment by 44vince44** [comment]
No filters involved: I just reproduced it with a **fresh install**... and made more tests. It seems to do it on some videos.
The thing is that, when you close the preview window, or if you open a new preview from the main window, the warning disappears.  

Watch screenshot video: (i edited a small part, because the preview opens in fullscreen when first time, so the screenshot is less confusing)

https://user-images.githubusercontent.com/17828567/107153308-77fb9a80-6975-11eb-89e1-205b8440bad5.mp4


You can reproduce it by using the **source video**  in https://github.com/staxrip/staxrip/issues/390 the video is in the 6th post of that thread.

**Comment by Dendraspis** [comment]
Perhaps when `AssumeFPS` kicks in?

**Comment by 44vince44** [comment]
Nope, it's in comment (#) , It puts itself automatically

**Comment by JJKylee** [comment]
@44vince44 is right. I re-checked and this happens _regardless of_ the source filter type and frame rate variability of the source video.

I guess the reason I couldn't reproduce it on the first attempt was because I didn't close the code editor.
The warning message appears as soon as I close the code editor. I just checked out if there's a warning message without closing the code editor.

Good find, @44vince44! 👍👍👍

**Comment by JJKylee** [comment]
Plus, I don't know if this is a related issue, but I cannot edit `Trim` values in _Code Editor_.
Even if I change the values, it's not reflected in _Preview_: the values revert back to before.
This is the same when _Preview_ is not open with _Code Editor_.
Cutting is only possible with _Preview_.
Is this normal? 🙄

**Comment by Dendraspis** [comment]
Okay, I can reproduce it now ...

> And the warning message disappears right after I close Preview as well.

... and it even does ***not*** appear at all when the Preview was (opened and) closed before. This is the reason I couldn't reproduce it last time.  😁 
Seems like the framerate is set/changed when the Preview closes. Opening and closing Preview is enough to let the message disappear.

> Even if I change the values, it's not reflected in _Preview_: the values revert back to before if I close _Code Editor_ and reopen it.

This should be okay, because both settings are *glued* together, being Preview the master.

**Comment by JJKylee** [comment]
> ... and it even does _**not**_ appear at all when the Preview was (opened and) closed before. This is the reason I couldn't reproduce it last time. 😁

You're right. This seems to be _the correct_ explanation on why I couldn't find it on the first try, either. (I was confused again. 😓)
I had also opened and closed _Preview_ working on another project before I tried to reproduce @44vince44's find.

I admit the 'experiment' was not fair since I didn't do it on a fresh start of StaxRip. 😅

> > Even if I change the values, it's not reflected in _Preview_: the values revert back to before if I close _Code Editor_ and reopen it.
> 
> This should be okay, because both settings are _glued_ together, being Preview the master.

Yes, I see, Master. 🙇😓

**Comment by Dendraspis** [comment]
@stax76 
Seems like more conditions are necessary or setting `p.CutFrameRate` when the cut is made.
`p.Ranges` has some items, so `p.CutFrameRate` is checked which is `0` , because it is first set when Preview is closing: 

https://github.com/staxrip/staxrip/blob/7bf24a3a712dae6801772b678ff36a07f276162b/Forms/PreviewForm.vb#L1071-L1083

https://github.com/staxrip/staxrip/blob/7bf24a3a712dae6801772b678ff36a07f276162b/Forms/MainForm.vb#L2965-L2989


@JJKylee 
This was just my explanation to give you a reason for that *strange* behavior.  😊

**Comment by 44vince44** [comment]
> 
> 
> Plus, I don't know if this is a related issue, but I cannot edit `Trim` values in _Code Editor_.
> Even if I change the values, it's not reflected in _Preview_: the values revert back to before if I close _Code Editor_ and reopen it.
> 
> This is the same even when _Preview_ is not open with _Code Editor_.
> Cutting is only possible via _Preview_.
> 
> Is this normal? 🙄

YES THIS IS NORMAL: the trim must be set with the graphical interface of the preview window (and it works fine, with both preview opened from MAIN window, and from CODE EDITOR). You're not supposed to type the trim values.

**Comment by 44vince44** [comment]
Can't we just add to the message : "Closing any preview window still open could fix that."

**Comment by Dendraspis** [comment]
...or even better, because there is only one human on earth  who would recognize such a bug:
***Also stop cross-closing windows, Vince! You know what happens!***

**Comment by 44vince44** [comment]
I "love" doing color correction, it allows to have great videos where sky is blue, skin is color of skin, and not purple or green-yellow. Of course this requires opening many preview windows and cross closing them 🤣 
Obviously, I use a color picker to check colors, don't trust the combination screen/env. light/ eyes. Color picker is a must.
That's probably the only (small) window I never close 😄

**Comment by 44vince44** [comment]
@stax76 Many thanks ❤️ 😍 this is fixed indeed !!
