### ISSUE TITLE
Please make "show command" display the command line for all passes in multipass mode for most popular codecs

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#496]
Currently, "show command" allows you to see all multipass commands for **only x265**.

But for other codecs (x264, aomenc, nvenc, etc) the "show command" will show only first pass command.

Can we please make it show all passes commands in multipass mode, at least for the most important codecs: x264, ~~nvenc~~, aomenc.
???

**Comment by JJKylee** [comment]
@44vince44, NVEnc 2pass works differently.
Instead of running first pass globally and then taking up 2nd pass from the start, it repeats first pass-second pass locally. Therefore, no explicit reference file is output during the first pass. The command is _not_ run twice.
So, NVEnc does not belong in this group. 😉

**Comment by 44vince44** [comment]
I stand corrected ! thanks @JJKylee 
So that leaves aomenc and x264 mainly...

**Comment by Dendraspis** [comment]
Done for x264 and aomenc.  😊
