### ISSUE TITLE
HDR ingest, error in command line generation

### ISSUE THREAD

**Issue by frankysan** [staxrip/staxrip#502]
**Describe the bug**
The command line that should ingest HDR metadata after MKV muxing fails, because of a missing space before "--white-colour-coordinates".
The command succeeds if I copy it from the log file, correct the missing space, and run it manually.

**How to reproduce the issue**
This happens with every HDR file I try to encode.

**Provide information**
StaxRip version 2.1.7.0.
Template, AVS and log attached
[HDR ingest error.zip](https://github.com/staxrip/staxrip/files/5953837/HDR.ingest.error.zip)

**Comment by 44vince44** [comment]
@frankysan this bug has been fixed in beta 2.1.7.2, I think. Since the release 2.1.8.0 is available, please get it and try it. Any feedback would be welcome. Extract the archive to a clean folder (no trace of the older files) and if possible, no older setting files as well since many structural modifications have taken place since then.

**Comment by 44vince44** [comment]
@frankysan If your problem is fixed with 2.1.8.0 please close this thread, otherwise we'll consider it fixed and close it maybe in a few days... or hours...

**Comment by Dendraspis** [comment]
> this bug has been fixed in beta 2.1.7.2, I think

Nope, in v2.1.7.1   😁 

So I close this now...
