### ISSUE TITLE
Strange behavior with sharpening in NVEnc

### ISSUE THREAD

**Issue by ZeroCool22** [staxrip/staxrip#514]
**StaxRip version:** x64-2.1.8.0-Stable
**Source video:** 10 Bits.

When i use VapourSynth + Sharpen the video losses brightness and contrast.

**I did a video showing the problem:**

https://www.youtube.com/watch?v=lp-9-5HhX38

It's normal?

**PD:** I use VapourSynth because i need to hardcode subs on a H265 10 Bits video.

**PD2:** The source video: http://www.mediafire.com/file/fhdwlsvh86wush4/Test.rar/file if someone want to try it.

**Comment by 44vince44** [comment]
@ZeroCool22 This appears to be totally not related to Vapoursynth at all.

You see, you are using SHARPEN of NVENC, not a sharpen filter of Vapoursynth. Here you are using only Vapoursynth to handle the "source".
I think it is a problem with NVEnc. In order to make sure, do the same test, but, in addition, select in NVEnc's options Basic > Decoder >"NVEnc Hardware".

If the problem is still the same, then it is a problem with NVEnc and must be reported in https://github.com/rigaya/NVEnc

**Comment by ZeroCool22** [comment]
Same result: https://www.youtube.com/watch?v=32OwrlbioiQ

**Comment by JJKylee** [comment]
[This issue](https://github.com/rigaya/NVEnc/issues/310) in NVEnc was fixed in [5.28](https://github.com/rigaya/NVEnc/releases/tag/5.28).

**Comment by ZeroCool22** [comment]
> 
> 
> [This issue](https://github.com/rigaya/NVEnc/issues/310) in NVEnc was fixed in [5.28](https://github.com/rigaya/NVEnc/releases/tag/5.28).

Thx for the info.

I just download that version and replace the files in E:\StaxRip-x64-2.1.8.0-Stable\Apps\Encoders\NVEnc right?

**Comment by 44vince44** [comment]
Yes, exactly. You should download and use 5.29 instead, it's the latest!

**Comment by ZeroCool22** [comment]
Working fine now with NVEnc 5.28.

**Comment by 44vince44** [comment]
Great !!
