### ISSUE TITLE
Staxrip set the wrong PAR/DAR by DVD Movies

### ISSUE THREAD

**Issue by Mister-XY** [staxrip/staxrip#527]
If i rip a DVD with MakeMKV and load it into Staxrip, i have a wrong PAR/DAR.
If i have a 16:9 movie, Staxrip did not load the 16:9 DAR. It's load a other PAL DAR.
In first picture, you see the 16:9 DAR but Stxrip load the 1.823361 DAR
![DAR](https://user-images.githubusercontent.com/10309056/108593905-e7f72100-7376-11eb-8528-7affc8279f12.jpg)
In second you see if i set it manualy.
![DAR2](https://user-images.githubusercontent.com/10309056/108593907-eaf21180-7376-11eb-9bf4-ef8d459d76ab.jpg)

**Comment by Dendraspis** [comment]
@44vince44 
Similar to [this one](https://github.com/staxrip/staxrip/issues/428#issuecomment-757434381) regarding the PAR?

**Comment by 44vince44** [comment]
Gimme a few moments I'm away. Be back in a few minutes

**Comment by 44vince44** [comment]
It's working here. made several tests (with mks and mp4) but not with dvd source.
![SNAG-0002](https://user-images.githubusercontent.com/17828567/108596244-690ce300-738c-11eb-9c9a-ac2bb0294a1f.jpg)

So either:
- a) it's specific to mpeg2 streams
- b) or it's @Mister-XY you forgot to delete old settings (too many changes happened lately, can't use old setting and old templates)

I'll try to find a mpeg2 and report it.

**Comment by 44vince44** [comment]
@stax76 @Dendraspis There is a problem indeed ONLY with the mpeg2s streams. You can also wrap them in mks, the problem is still there.
The DAR is not correctly read or set. Here is a file for you to test, just drop it inside Staxrip.
The DAR by Mediainfo is 1.33
The DAR read by Staxrip is 1.36
The storage AR is 1.25, and that's correctly read by Staxrip.

[VTS_01_1.zip](https://github.com/staxrip/staxrip/files/6015098/VTS_01_1.zip)

**Comment by Mister-XY** [comment]
with mpeg4 i have no problem. i have this problem with mpeg2

**Comment by 44vince44** [comment]
> There is no problem here, @Mister-XY you only need to REMOVE THE ITU-R compliant aspect ratio.

This options shouldn't be here anymore ! It is deprecated.

**Comment by Mister-XY** [comment]
Thx, you are right, with deactivated ITU-R, it shows the correct DAR and PAR.

**Comment by stax76** [comment]
I don't remember such details, but I would guess it's enabled by default for a reason.

The author of [encodingwissen.de](https://encodingwissen.de/) was involved when it was developed.

**Comment by 44vince44** [comment]
@stax76 well please unselect it by default. itu-r bt601 is WAY deprecated, you may only need it when you are creating a mpeg2 stream for a DVD.
Since Staxrip is not a mpeg2 encoder, this has no use now.
I'm only asking to deactivate it by default, not to remove it. 
I always deactivate it when I create my templates (and I always handle aspect ratio stuff and resizing in my encodings).

**Comment by Dendraspis** [comment]
> The author of [encodingwissen.de](https://encodingwissen.de/) was involved when it was developed.

Back in 2011 when almost all pages were made and DVDs were at their peak?  😁

**Comment by 44vince44** [comment]
Yes, as @Dendraspis says, BT601 is deprecated, so the option to set it as colormatrix is not available anymore in x264, x265 and even in muxing software. BT601 was replaced by "undefined".
Same thing here, ITU-R AR standard that involves a calculation with predefined pixel aspect ratio and PAL/NTSC differenciation, has absolutely no use here. All we need is video size and aspect ratio.
So we can easily untick it in default, we have nothing to fear.
I stop talking here because @Dendraspis hates when I repeat myself especially on this subject 😁

**Comment by 44vince44** [comment]
@stax76 in 2.1.8.2 the option is still selected by default. It seems you're gonna keep it.... right ?

**Comment by stax76** [comment]
It will be disabled in the next commit.

**Comment by mirh** [comment]
I'm still having this problem (I disabled every auto crop/adjust setting)
My dvd-rip is being detected with PAR=255:215 and DAR=1,777083 instead of the proper 32:27 and 1,777777.
