### ISSUE TITLE
tune : psnr doesn't work in x265 encoding

### ISSUE THREAD

**Issue by mr-qansuh** [staxrip/staxrip#530]
tune : psnr doesn't work in x265 encoding....

What's the solution?????

**Comment by 44vince44** [comment]
It works here ! can you copy the full log and paste it here ?

**Comment by JJKylee** [comment]
Same here.
@mr-qansuh, an anecdotal statement is not enough. Provide your **_proof_**!

**Comment by mr-qansuh** [comment]
Sorry, I seem to have missed it
I knew the error
but you can tell me best sittings to convert hardsub and get best quality and meduim size not high size

**Comment by 44vince44** [comment]
Tell me the following:
- resolution (720p, 1080p ?) =
- total time of video =
- what size do you want for the resulting video (1gb, 2gb, 3gb ?) = 
- what is your cpu =

@mr-qansuh you must give us some information here we can't help you if you tell us nothing....

**Comment by mr-qansuh** [comment]
> Tell me the following:
> 
> * resolution (720p, 1080p ?) =
> * total time of video =
> * what size do you want for the resulting video (1gb, 2gb, 3gb ?) =
> * what is your cpu =
> 
> @mr-qansuh you must give us some information here we can't help you if you tell us nothing....
resolution (720p, 1080p ?) =720p
total time of video =43:09
what size do you want for the resulting video (1gb, 2gb, 3gb ?) =260mb
what is your cpu =intel(R) Core(TM) i5-4690 CPU @ 3.50GHz   3.50 GHz

But I want subtitles for hardsub without any errors

Another question 
What is the difference between quality and quantizer ?
and which get best quality

**Comment by stax76** [comment]
Please, the issue tracker is for tracking staxrip bug reports and feature requests.

Such general encoding questions should be researched with Google and if necessary asked at Doom9 or VideoHelp.

**Comment by JJKylee** [comment]
> What is the difference between quality and quantizer ?

Wow... 😲
If you truly don't know the difference b/w those two, you better refer to the basics of encoding, not here.
We need to spend _too much time_ to explain the basics to you.
Why don't you visit Doom9's forum or VideoHelp forum, or Reddit instead?
And you could google for basic concepts.

As a starter, [here](https://slhck.info/video/2017/03/01/rate-control.html)'s a document explaining the rate control modes for x264, x265, and vpx.

**Comment by 44vince44** [comment]
@mr-qansuh I will answer you to help you, but after that, you should look for that information on google, because it's general knowledge in compression (exactly as @stax76 told you) :


resolution (720p, 1080p ?) =720p
total time of video =43:09
what size do you want for the resulting video (1gb, 2gb, 3gb ?) =260mb
what is your cpu =intel(R) Core(TM) i5-4690 CPU @ 3.50GHz 3.50 GHz


Use x265, leave mode to Quality (it's BETTER than quantizer, it's like a slightly variable quantizer), preset slow, Q = 30.

**Mode = QUALITY, select 30 ("Ultra Low", in x265 it's very good) 
Preset = Slow
Tune = NONE**

Run a quick test. if your cpu is less or around 50%, use CHUNKS = 2.

Good luck with your encodes
