### ISSUE TITLE
AMD's HW encoder missing features

### ISSUE THREAD

**Issue by NikosDi** [staxrip/staxrip#551]
Hello Frank.

It seems that a few features/parameters supported by VCEEnc are missing from StaxRip

**Important** (Added 10 bit HEVC encoding for Navi cards onwards):
--output-depth <int>         set output bit depth

**Info:**
--timecode [<string>]        output timecode file.
--ssim                                 calc ssim
--psnr                                 calc psnr

**VPP** (similar to nVidia's NVEnc parameters):
--vpp-colorspace [<param1>=<value>][,<param2>=<value>][...]
--vpp-afs [<param1>=<value>][,<param2>=<value>][...]
--vpp-nnedi [<param1>=<value>][,<param2>=<value>][...]
--vpp-decimate [<param1>=<value>][,<param2>=<value>][...]
--vpp-resize <string>        
--vpp-pad <int>,<int>,<int>,<int>
--vpp-knn [<param1>=<value>][,<param2>=<value>][...]
--vpp-pmd [<param1>=<value>][,<param2>=<value>][...]
--vpp-smooth [<param1>=<value>][,<param2>=<value>][...]
--vpp-subburn [<param1>=<value>][,<param2>=<value>][...]
--vpp-unsharp [<param1>=<value>][,<param2>=<value>][...]
--vpp-edgelevel [<param1>=<value>][,<param2>=<value>][...]
--vpp-warpsharp [<param1>=<value>][,<param2>=<value>][...]
--vpp-tweak [<param1>=<value>][,<param2>=<value>][...]
--vpp-rotate <int>           rotate video (90, 180, 270)
--vpp-transform [<param1>=<value>][,<param2>=<value>][...]
--vpp-deband [<param1>=<value>][,<param2>=<value>][...]

Thank you.

**Comment by JJKylee** [comment]
And AMD is also missing from the _ffmpeg_ encoders list...

![StaxRip_2 1 8 4_hotfix3_ffmpeg-AMD_missing_from_default_video-encoder_profiles_20210227](https://user-images.githubusercontent.com/3157518/109387410-2f6d3800-78b6-11eb-8c74-e7e7524a3144.jpg)

...although I'm doubtful if there are _any_ people who use ffmpeg/AMD encoders at all. 😅

All _ffmpeg_ _HW_ encoders (Intel, Nvidia, AMD) do not seem to have been taken care of for a long time. Their options are way incomplete and outdated. But I think it's OK since we already have excellent alternatives - QSVEnc, NVEnc, and VCEEnc. 😄

It's gonna be another big task if we are to touch them. I'm doubtful if they're worth investing time for, but some options seem to have room for update. Let's see if @stax76 or @Dendraspis is willing to do it. 😅

**Comment by Dendraspis** [comment]
Okay, I've updated a lot of params.
But it was a pretty quick implementation without double-checking. So it's up to you test and report - and create PRs if you can/want.
