### ISSUE TITLE
Latest BETA seems to index first and ask to demux second

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#576]
I didn't know if this change was intended or if it was a bug. As the demux menu has always came up first before it indexed. 

I'm fine with it either way.

**Comment by Dendraspis** [comment]
As far as I remember nothing has changed in the demux procedure.
It could be related to different file extensions or codecs, so that the preprocessor can't do it's work. 🤔

**Comment by 44vince44** [comment]
But there is no problem with that, the indexing is done, and the demuxing is done. As those are not cross dependent, it is ok !
There is no advantage or disadvantage to have one triggered before the other...

**Comment by stax76** [comment]
I think there was a bug where the main dialog did not show the output resolution when the resolution was changed in the target width/height text box. The fix for that by Dendraspis did probably cause this. It probably analyzes the script earlier and analyzing is what probably triggers the demuxing. But I cannot reproduce it, could also be something else.

1. The demux option 'Show Dialog' is not the default and probably not popular among staxrip users.
2. The fix that probably caused it did simplify complex code.

For me, it's also fine.

**Comment by jlw4049** [comment]
I don't mind it either way. I was just wondering if it wad intentional. 

It happens to me on the manual workflow template.

**Comment by stax76** [comment]
@Dendraspis The demux dialog used here isn't themed yet.

**Comment by Dendraspis** [comment]
@stax76 
This is something I mentioned earlier.  There are many of these dialogs, for example the `$select` things used for filters. They are `TaskDialog`s and therefore almost completely system made. 😥  The only solution (in my eyes) would be creating a custom form for that purpose.  🙄   But I have not that much UI experiance compared to you. If you know how to make it...
I've fought enough battles with the UI to say be willed to do that, at least at the moment.  😞 

> The fix for that by Dendraspis did probably cause this.

🤔  It was just a `Synchronize()` call at the beginning of `Assistent()`, that should not be called before all streams are ready.  🤔 

I could also not reproduce it.  🥴

**Comment by stax76** [comment]
TaskDialog and TabControl are the only remaining issues.

I don't know how to say it in English, Checkbox hat eine Stufe, ein Versatz:

![Untitled](https://user-images.githubusercontent.com/11410540/110891681-cd1f2900-82f2-11eb-97e9-2089f2473bbf.png)

It's not like this in the default WinForms and WPF rendering, which I prefer.

For the TaskDialog we can search for open source code, could also be WPF (I'm also mixing WinForms and WPF in mpv.net), maybe we can find something decent and not bloated.

Otherwise, I can build something, but that would take 2-3 weeks, I need to relax a bit first and then take it slow.

Either way I think we can't just replace the TaskDialog in one go, but rather step by step starting with the most common use cases.
