### ISSUE TITLE
Possibility to change font

### ISSUE THREAD

**Issue by tormento** [staxrip/staxrip#583]
I'd like to have the possibility to change the font in the "Processing..." window.

**Comment by 44vince44** [comment]
What's wrong with current font, too small ?

**Comment by tormento** [comment]
I have sight problems. Want to completely change it.

**Comment by Dendraspis** [comment]
I don't think we are going to implement it.
Currently `Consolas` is used, the default Windows terminal font. Another non-fixed-size-font won't make sense and would destory the output. Also the size suits great to the rest of the UI.

What you can do is increasing ***UI Scale*** in the settings for the whole app if you want/need it to be bigger.

**Comment by 44vince44** [comment]
Apparently and surprisingly that seems to have been done in latest commits 😮 
Maybe this should be closed...

**Comment by Dendraspis** [comment]
...but it's not really done. He wanted to "completely change it", meaning a free selection of all installed fonts, its style and size.  🤔

**Comment by tormento** [comment]
I promise not to use Comic 😜

**Comment by stax76** [comment]
Changing the font everywhere (except where currently a fixed width font is used) could be done I guess, but it should only be the font name and not the font size, allowing to change the font size could lead to a major maintenance problem. People that want to increase the font size should use the Scale Factor setting. Segoe UI is fine in my opinion.

**Comment by 44vince44** [comment]
Ok but I don't understand, you already did that in latest commits, so isn't this done ?

**Comment by stax76** [comment]
The new settings is only used in places where Consolas was used, code editor, code preview, command line preview, info in preview and few other places.

**Comment by 44vince44** [comment]
OK I understand!

**Comment by JJKylee** [comment]
> Changing the font everywhere (except where currently a fixed width font is used) could be done...

As far as I understand, it is the fixed-width font (_Console Font_) that @tormento wants to change. And personally, I agree with @tormento.

There are some excellent _locale specific_ fixed-width fonts that improve many typographical features - identification, kerning, tracking, ligature, harmonious baseline location/height alignment, etc. - for included glyphs(letters).

For example, [D2 Coding](https://github.com/naver/d2codingfont) is a good example. It fills in the missing _Korean_ letters from popular fixed-width fonts like `Consolas` and fixes identification/inharmonious-alignment issues between Korean and non-Korean letters. [NanumGothicCoding](https://github.com/naver/nanumfont) is another similar fixed-width font for the Korean language.

(To be frank, I would like to use `D2 Coding` as the default console font.)

It seems like Windows fills in the missing letters in the designated console font with the system's default locale aware fixed-width font. For example, in the Korean language, `Gulimche` is used in place of `Cascadia Code` (the console font of my choice) for the Korean letters. (But since `Gulimche` is very old and too ugly, I'm using a modified version of `Gulimche` instead.)

![StaxRip_2 1 8 5_hotfix_fixed-width-font_in_Progress-Window_Korean_letter_20210316](https://user-images.githubusercontent.com/3157518/111346492-7f305b00-863b-11eb-8869-68ca149af64b.jpg)

(The Korean font in the screenshot is my mod `Gulimche`.)

But still there are remaining issues like identification and inharmonious alignment, etc. This is why I want to use the locale specific fixed-width font.


Having said that, I'm wondering if it's possible to list _only_ fixed-width fonts in the system for _Console Font_ candidates. If it is not too difficult, I'd like to see it in StaxRip as @tormento would. 😄

**Comment by stax76** [comment]
I can try to list system installed fixed width fonts, I have it in MediaInfo.NET but there the code is tied to WPF unfortunately.

**Comment by stax76** [comment]
I wrote code that works, but its way too slow, and I don't want to spend a lot more time for it, so I just made it a text box. Hotfix is online.

**Comment by JJKylee** [comment]
Works great! 👍👍👍👍👍

![StaxRip_2 1 8 5_hotfix_D2Coding_as_Console-Font_20210316](https://user-images.githubusercontent.com/3157518/111358302-6b8af180-8647-11eb-9444-274962a507b9.jpg)

![StaxRip_2 1 8 5_hotfix_D2Coding_in_Processing-Window_20210316](https://user-images.githubusercontent.com/3157518/111358327-7180d280-8647-11eb-9ef5-fa9cbdfc5855.jpg)

Thanks a million. 😊💕

**Comment by Dendraspis** [comment]
I made a tiny addition to the DropDown menu, which now includes all monospaced fonts - hopefully.
First call of settings is <200ms slower, afterwards negligible. Should be okay?!

[StaxRip v2.1.8.5D_Font.zip](https://github.com/staxrip/staxrip/files/6152796/StaxRip.v2.1.8.5D_Font.zip)

**Comment by JJKylee** [comment]
Never did I know that I have **_52_** fixed-width fonts in my system. 😝

![StaxRip_2 1 8 5_hotfix_Console-Font_setting_drop-down-menu_20210316](https://user-images.githubusercontent.com/3157518/111395806-f33e2380-867a-11eb-8859-1bf5363ef189.jpg)

This is truly cool. Good job, @Dendraspis! 👍👍👍👍👍

The loading time is slightly slower when I call the `Settings` menu after a fresh launch, but it gets back to normal while the main window is open.

I think the loading lag at the first launch will become noticeably less when you have less monospace fonts.
It is already pretty much negligible in my case (52 fonts 😅) as well.

**Comment by tormento** [comment]
@Dendraspis thanks!

Now what is missing is size ;) Pay attention to variable fonts too!

**Comment by 44vince44** [comment]
Size will not be changed due to interface geometry. if you want bigger size : INCREASE SCALING FACTOR IN STAXRIP's SETTINGS > User Interface !!!

**Comment by tormento** [comment]
@44vince44 not all monospace fonts are created equal. Usually they have same width but different height.

**Comment by JJKylee** [comment]
Personally, I'm with @44vince44 regarding the size issue. I don't think your argument is critical, @tormento.

And about the variable-width font, I also don't think we need its customization considering that StaxRip is not internationalized yet and that there's no roadmap for i18n in the near future. The current UI font seems more than enough, IMHO.

**Comment by stax76** [comment]
Is the font selection text box still needed, or should it be changed to a menu without text box?

**Comment by tormento** [comment]
> Is the font selection text box still needed, or should it be changed to a menu without text box?

IMHO no need for a text box. Almost nobody remembers the right font name 😁

**Comment by Dendraspis** [comment]
@stax76 
To be honest the text box is fun!  I tried some crazy fonts like `Comic Sans MS` and it looks nice.  😁 
I would leave it.

**Comment by JJKylee** [comment]
Ditto. 😄

**Comment by Dendraspis** [comment]
Btw, I'm currently testing this:   🤣 

<img src="https://user-images.githubusercontent.com/50659978/111453858-5039e800-8714-11eb-8468-e336396c5b09.PNG">

<img src="https://user-images.githubusercontent.com/50659978/111454322-cfc7b700-8714-11eb-8bc0-659c53488d35.PNG">

**Comment by JJKylee** [comment]
Seems like @tormento's wish is going to be fulfilled. 😆

**Comment by 44vince44** [comment]
OMG is the scaling feature so hard to find ???

**Comment by Dendraspis** [comment]
Nope, but I admit that it can be nice to enlarge the text a bit.
*UI Scale* is global for all windows and controls, which is not pleased in my case.

**Comment by Dendraspis** [comment]
> Seems like @tormento's wish is going to be fulfilled. 😆

Sadly it won't, too many issues with that.  😞

**Comment by tormento** [comment]
> > Seems like @tormento's wish is going to be fulfilled. 😆
> 
> Sadly it won't, too many issues with that. 😞

?

I had what I needed...

**Comment by JJKylee** [comment]
> @Dendraspis thanks!
> 
> Now what is missing is size ;) Pay attention to variable fonts too!

⇦ 🙄❓

**Comment by JJKylee** [comment]
> > > Seems like @tormento's wish is going to be fulfilled. 😆
> > 
> > 
> > Sadly it won't, too many issues with that. 😞
> 
> ?
> 
> I had what I needed...

If this is true, maybe we can close this issue thread. 🤔

**Comment by Dendraspis** [comment]
> > I had what I needed...
> 
> If this is true, maybe we can close this issue thread. 🤔

Why should he lie?!  😉
