### ISSUE TITLE
Failed to demuxing video.ts  when opening

### ISSUE THREAD

**Issue by Bandid0** [staxrip/staxrip#585]
**Describe the bug**
Failed to demuxing video.ts  when opening
[video_staxrip.log](https://github.com/staxrip/staxrip/files/6132241/video_staxrip.log)

**Provide information**
StaxRip    : 2.1.8.5
Windows    : Windows 10 Pro 2009
Language   : Spanish (Spain, International Sort)
CPU        : AMD Ryzen 5 2600X Six-Core Processor
GPU        : NVIDIA GeForce RTX 2060
Resolution : 2560 x 1440
DPI        : 106
Code Page  : 1252

**Comment by stax76** [comment]
I think ffmpeg fails because it cannot handle the subtitles. You can try running the command line in the command prompt and add `-sn`, it means no subtitles, not sure if you have to put this before or after `-i`.

http://www.ffmpeg.org/ffmpeg-all.html#Subtitle-options

**Comment by Dendraspis** [comment]
This seems to be similar to an issue we had. `-sn` is already set as well as `-probesize`, but I don't remember why `Analyzeduration` was not applied, because that is what should be needed here. The error message tells us to add it, too.

**Comment by Bandid0** [comment]
![image](https://user-images.githubusercontent.com/79402382/111023318-9d4a5100-83d8-11eb-9d02-5d0d79601542.png)

the commands are already added

**Comment by 44vince44** [comment]
I read somewhere that the values for probesize and analyzeduration must be 50MB and 100MB:

-analyzeduration 100M -probesize 50M

But I'm no expert in ffmpeg and TS...

**Comment by Bandid0** [comment]
[video_staxrip.log](https://github.com/staxrip/staxrip/files/6134731/video_staxrip.log)

**Comment by 44vince44** [comment]
Maybe it has to do with dolbyvision....

Can you try to use mkvtoolnix to remux it to mkv, then use the mkv in staxrip (you'll need to delete the temp folder of the project first)

**Comment by 44vince44** [comment]
@Bandid0 Maybe it is an m2ts. I need you, please, do a final test: change extension to m2ts and try again (after deleting the temp folder of the project)...
video.ts => rename to video.m2ts

@stax76 @Dendraspis This probably does not require anything to do, but it seems some file are better converted with ffmpeg and some other with eac3to. Changing extensions between ts and m2ts make the switch between ffmpeg and eac3to.

**Comment by Bandid0** [comment]
> @Bandid0 Maybe it is an m2ts. I need you, please, do a final test: change extension to m2ts and try again (after deleting the temp folder of the project)...
> video.ts => rename to video.m2ts
[video_staxrip.log](https://github.com/staxrip/staxrip/files/6135726/video_staxrip.log)

It seems it worked

**Comment by 44vince44** [comment]
@Bandid0 can yo please send me the working log !! it's important

**Comment by 44vince44** [comment]
Thanks for doing the test @Bandid0 now we know what we wave to discuss. I'll put a summary shorty here.

**Comment by 44vince44** [comment]
SUMMARY

First, let's remind that this is not an issue with probesize and analyzeduration since this has no effect `-analyzeduration 100M -probesize 50M`

Second, let's acknowledge that when a file is a .ts, it triggers ffmpeg for the remux. But when it is .m2ts it triggers eac3to:
- .ts => remux with ffmpeg
- .m2ts => remux with eac3to

Now, here is a summary of what happens according to file content:

## Case 1: basic content ts files from the internet = basic ts native
Container format: **MPEG-TS**
Video codec: **AVC**
Audio codec: **AAC**
Subtitles: NO

.ts (native) => ffmpeg remux PASS 🆗 
.m2ts (renamed) => eac3to remux PASS 🆗 

## Case 2: hdr/DVision content, file used by @Bandid0 = "not basic" ts native
Container format: **MPEG-TS**
Video codec: **HEVC**
HDR Format: **Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU**
Audio codecs: **E-AC-3** ; **E-AC-3 JOC**
Subtitles : YES

.ts (native) => ffmpeg remux FAIL 🚫 LOG [bandid0 Failed (ts native, ffmpeg).log](https://github.com/staxrip/staxrip/files/6136265/bandid0.Failed.ts.native.ffmpeg.log)
.m2ts (renamed) => eac3to PASS 🆗 LOG [bandid0 Pass (m2ts renamed, eac3to).log](https://github.com/staxrip/staxrip/files/6136267/bandid0.Pass.m2ts.renamed.eac3to.log)

NOTE: failure reason in ffmpeg:
[matroska @ 000001a89496b4c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 000001a89496b4c0] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument


## Case 3: hdr/Dvision content, trailer file used by me = "not basic" m2ts native
Container format: **BDAV**
Video codec: **HEVC**
HDR Format: **SMPTE ST 2086, HDR10 compatible**
Audio codecs: **AC-3 MLP FBA 16-ch** ;  **E-AC-3 JOC** ; "AC3"
Subtitles: NO

.ts (renamed) => ffmpeg remux PASS 🆗 LOG [chameleon Pass (ts renamed, ffmpeg.log](https://github.com/staxrip/staxrip/files/6136289/chameleon.Pass.ts.renamed.ffmpeg.log)
.m2ts (native) => eac3to remux FAIL 🚫 LOG [chameleon Failed (m2ts native, eac3to).log](https://github.com/staxrip/staxrip/files/6136290/chameleon.Failed.m2ts.native.eac3to.log)


# Conclusion

Some internal properties of the files make it better to remux with ffmpeg or eac3to.
With basic files, it doesn't matter because ffmpeg and eac3po work.

With complex files, it seems that IF YOU FIX THIS in ffmpeg:
```
[matroska @ 000001a89496b4c0] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[matroska @ 000001a89496b4c0] Can't write packet with unknown timestamp
av_interleaved_write_frame(): Invalid argument
```
THEN once it's fixed, both ts and m2ts should be opened with ffmpeg.

**Comment by JJKylee** [comment]
Just FYI, @Bandid0's `ts` file remuxes _**successfully**_ with this _modified Arguments_ in `ffmpeg: Re-mux TS to MKV`.

```
-probesize 10M -i "%source_file%" -map 0 -c copy -ignore_unknown -hide_banner -y "%temp_file%.mkv"
```

`-map 0` is added and `-sn` is deleted.

### Main window

![StaxRip_2 1 8 5_hotfix_Dolby-Vision-sample-1 ts_main-window_20210317](https://user-images.githubusercontent.com/3157518/111456432-3973a100-86d4-11eb-84f4-56eb096059db.jpg)

### Temp folder file list

![StaxRip_2 1 8 5_hotfix_Dolby-Vision-sample-1 ts_temp-folder_file-list_20210317](https://user-images.githubusercontent.com/3157518/111456452-40021880-86d4-11eb-8a8b-adf971b3f459.jpg)

So it is a fixable issue after all.

I couldn't participate in this discussion properly earlier because I wasn't feeling good. My apologies. 😅

**Comment by stax76** [comment]
-map 0 means all streams?

-sn was probably added because it fixed another issue reported by somebody. 😟

**Comment by JJKylee** [comment]
Without `-map 0`, ffmpeg selects only one stream per type based on some criteria. See [this](https://ffmpeg.org/ffmpeg-all.html#Automatic-stream-selection).

And I guess the issue was raised because `-map 0` was not included back then.

Combined with the `Show dialog to choose subtitles to be included` option, this new argument yields nice subtitle tracks.

**Comment by stax76** [comment]
OK, I've changed it.
