### ISSUE TITLE
logs containing very old incorrect info

### ISSUE THREAD

**Issue by Statick** [staxrip/staxrip#609]
I've updated Staxrip many times over the years, currently using 2.1.8.0
My current update process is : 

- unzip staxrip to new folder
- copy "settings" folder from old folder to new folder

I've been doing this for a long time, but at some point in the past I did also used to unzip directly over older versions (didn't know at the time this was a bad idea)

I've just encountered an issue and opened the log, and found that it starts with some very old information - the "system environment" shows v1.7.0.0 and my system specs from around 3 years ago, and then there's some encoding information for some BR discs I was ripping around 3 years ago, before it then shows the processes used in my most recent encode

I've also found that going to the menu "tools > log file" produces a "system cannot find the file specified" error for "staxrip_folder\settings\log files". I've found the most recent log myself by going to the last encode's temp folder, I'm not sure what the difference is between that log file and whatever should be in the settings folder, but there's clearly something not right if I'm getting error messages when clicking "log file"

Most recent log attached, it doesn't complete because I encountered an issue during the encode, everything from "media info source file" is current but the stuff above that point is years old and incorrect

[The Hitchhiker's Guide to the Galaxy 1x01_staxrip.log](https://github.com/staxrip/staxrip/files/6175437/The.Hitchhiker.s.Guide.to.the.Galaxy.1x01_staxrip.log)

**Comment by JJKylee** [comment]
> ...at some point in the past I did also used to unzip directly over older versions...

That's why it's not recommended to overwrite the old files.
Do _not_ do this _unless_ you know what you're doing. Period.

**Comment by Statick** [comment]
which is why I don't do that anymore, and haven't for a long time

**Comment by JJKylee** [comment]
> I included that info as I thought it might help figure out how to fix the problem I'm having.

The attached log file doesn't help in this matter since `...copy "settings" folder from old folder to new folder` is also _not_ recommended. _Resetting to the default settings_ is always recommended in such cases as yours. That is, remove your old settings folder and start afresh when you encounter an unknown problem, even if it's annoying.

**Comment by 44vince44** [comment]
@Statick due to many changes happening, it is preferable to re-create your settings from scratch from time to time.
And time has passed since 1.7.0.0 till now.
There has been also changes among the coders (Stax76 then Revan654 then Stax76, and now Stax76 and Dendraspis)
Just do your settings and templates from scratch.
You'll probably not be required to do them once again in next release.
Please get latest beta (2.1.8.5), do not use 2.1.8.0.

**Comment by Statick** [comment]
okay thanks! I didn't know that copying the settings folder was also bad - this is what I was told to do when I previously commented about unzipping new versions over old versions!

**Comment by JJKylee** [comment]
Here's what I do in order to avoid this kind of situation and preserve my old settings.

In addition your two steps, I do this following step _every time_ I update StaxRip.

> Edit all menus/profiles, reset them if necessary, referring to the new version launched from a separate folder.

But it's _not recommended_, since it's very cumbersome and time consuming esp. when there's a big change between the versions.
You can save time if you are well informed about the changes (`Changelog`), but even in that case, it's annoying. 😅

**Comment by Dendraspis** [comment]
> okay thanks! I didn't know that copying the settings folder was also bad - this is what I was told to do when I previously commented about unzipping new versions over old versions!

This is possible in many cases. But it depends on the changes that were made to StaxRip. To prevent unwanted side effects, it is highly recommended to **not** copy settings, templates and/or jobs between StaxRip versions. If you want to be save: start from scratch. 
Yes, sometimes it's a pain in the ass, but on the other side it also has some advantages. 😞 

We'll try to note a possible break in the changelog for future releases.

**Comment by JJKylee** [comment]
> To prevent unwanted side effects, it is highly recommended to **not** copy settings,...

This is not only true with StaxRip but with _all other_ software programs as well.

"If any mysterious problem occurs, reset the settings."

**Comment by Statick** [comment]
okay I've done a clean install with clean settings, and rebooted
I've done a test encode using the default "automatic workflow" template 

still getting this old info at the top of the log
