### ISSUE TITLE
Delete all profiles and restore the new ones?

### ISSUE THREAD

**Issue by stax76** [staxrip/staxrip#620]
**Is your feature request related to a problem? Please describe.**

@Dendraspis 
There is a message box 'Delete all profiles and restore the new ones?', I'm not really understanding it exactly, but it doesn't have to mean that it's not explained well. Maybe it could be more intuitive if you use the task dialog and use named buttons instead of standard buttons. Or use command buttons, I usually prefer command buttons. I suggest using command buttons with both text and description. If you are not sure how to use the task dialog I can help. Or maybe you think it's fine or okay like it is, then it's okay or fine for me too.

**Comment by 44vince44** [comment]
How can this be reproduced, I never got that message box ?

**Comment by stax76** [comment]
Sorry I've forgotten to describe it. It's the 'Restore' feature in the profiles editor, like audio profiles.

**Comment by Dendraspis** [comment]
😂   I almost forgot this one.  It was one of my early "features". It was the time were many encoders were outdated and the video profile menus changed. In order so see those changes, you had to reset the menu.

When clicking on "Yes", the current menu was not flushed before the new default menu was written, it just overwrote everything. This gave you the possibility to get the new menus without deleting you own presets.

I don't know if we need it anymore. I used it when the menu was re-ordered a lot and there were many changes to encoders like aomenc, that I never used. 
But meanwhile it seems to be less necessary, so we could get rid of it. Otherwise it can be changed to the new TaskDialog, of course - no question about it.

**Comment by stax76** [comment]
I understand it now, it could still be useful, but it's a bit difficult to explain  
and understand, maybe the following commands could be used:

```
Clean Restore

Overwrite current profiles with default profiles
    Current profiles will be overwritten by the
    defaults, profiles with different name remain.

                                           Cancel
```

**Comment by Dendraspis** [comment]
It is, indeed.  😁 

👍   You could have changed it directly with your new TaskDialog. Or do you want me to do this?

**Comment by stax76** [comment]
Change it if you like. I try to quit coding for today.
