### ISSUE TITLE
Add hardcoded subtitles does not work in "Demux preferred subtitles but do not include them"

### ISSUE THREAD

**Issue by 44vince44** [staxrip/staxrip#643]
**Describe the bug**

`Add hardcoded subtitles` does not work in `Demux preferred subtitles but do not include them` mode.
But it works in MODES: `Demux and include(..)` and `show dialog`
Read below to know how it must work

**Expected behavior**
here is a table of how "Add Hardcoded Subtitles" works currently / must work

- `Demux and include preferred subtitles`: it adds the Textsub(mod) filter / must add the filter Textsub(mod) ✔️ 
- `Demux preferred languages but don't include them`: it does not add Texsub(mod) filter / MUST ADD THE FILTER TEXTSUB(mod) ❌ 
- `Show Dialog to choose`: it adds the Textsub(mod) filter / must add the filter Textsub(mod) ✔️ 
- `Include preferred subtitles directly without demuxing`: it does it does not add Texsub(mod) filter / must not add TextSub(mod) ✔️ 
- `Don't include subtitles`: it does it does not add Texsub(mod) filter / must not add TextSub(mod) ✔️ 

**Conclusion**
The only mode that needs fixing is `Demux preferred languages but don't include them`.
Please make the option `Add hardcoded subtitles` add the proper TextSub filter (AVS) or TextSubMod (VPY)

Thanks !

**Comment by Dendraspis** [comment]
Fixed, but there seems to be a misunderstanding:  `Include = Mux`, so the given behavior was wrong, as well as the expected one. 
Here is the expected and correct behavior:

- ✔️ ✔️ `Demux and include preferred subtitles`
- ✔️ ❌ `Demux preferred languages but don't include them`
-   ❔  ❔  `Show Dialog to choose`
- ❌ ✔️ `Include preferred subtitles directly without demuxing`
- ❌ ❌ `Don't include subtitles`

Whenever the `Add hardcoded subtitle` Checkbox is checked, it looks for the first valid subtitle file and uses it to create the `Textsub(path)` filter.

This way you can have 
- `Video.mkv`
- `Video.English.srt`
..., don't demux or somethimg like that and still be able to create a hardcoded sub out of `Video.English.srt`.

**Comment by stax76** [comment]
I think the problem of Atlantis is due to a change I made here:

https://github.com/staxrip/staxrip/blob/master/Source/General/Demux.vb#L265

https://github.com/staxrip/staxrip/blob/master/Source/General/Demux.vb#L466

https://github.com/staxrip/staxrip/blob/master/Source/General/Demux.vb#L732

It's replacing the preferred languages instead of expanding them.

**Comment by Dendraspis** [comment]
Do you remember why this replacement was made? Seems to be sort of special because of the condition. 🤔

**Comment by stax76** [comment]
Before that change the preferred subtitles were not modified, so apparently there was an issue before, but it was never noticed.

https://github.com/staxrip/staxrip/blob/55e9f80c12000cbd6a22f84bf3a4d857ad6493e7/General/Demux.vb#L673

**Comment by 44vince44** [comment]
@stax76 the issue of Atlantis has been fixed in latest commits that @Dendraspis did. I have just tested them.

However, the REAL problem of Atlantis is his attitude: he wants a bug fixed, he doesn't want to open an issue here, then he wants a hotfix, and he doesn't want to request it here. And he obviously consider that he is the owner of staxrip and of the coders.

**Comment by stax76** [comment]
When I worked on the subtitle improvement, I did the following:

When the demux dialog closes, the preferred languages get replaced with the languages selected in the dialog, so staxrip will afterwards only find languages that were selected in the dialog. That is the problem of Atlantis I think. He didn't say anything about hard-coded subtitles I believe.

Before my change the preferred languages were not modified, and that is also not correct I think because when the user selects a language in the dialog that is not defined as preferred language then staxrip didn't find it afterwards even though it was selected in the dialog. I didn't verify it with a test because I visit my mom and sister, before I worked on a very hard mpv.net feature (very hard pinvoke problem).

The solution would be to keep the preferred languages and expand them with the languages that were selected in the dialog.

At doom9 I've good experience with saying 'please do' or 'you can do' or 'you can try' or 'you could try'. I can see why the word 'should' can be problematic. Here are some info links:

https://www.positivelypresent.com/2015/10/should.html

https://drsoph.com/blog/2018/8/27/should-the-one-word-you-need-to-stop-sayingnow

https://www.inc.com/ken-sterling/dont-tell-your-team-you-should-use-this-phrase-instead.html

https://tinybuddha.com/blog/why-the-word-should-can-be-harmful-3-empowering-alternatives

I've never noticed anybody with an attitude problem here or at the doom9 support thread except the guy that registered with a couple of different names and my special shareware friend.

**Comment by 44vince44** [comment]
I'm reading your links now, and i really promise to take them into consideration. I didn't know that `should` was that problematic.

However, my reaction was also due to the fact that you already asked him recently, several times and for several bugs, to post here on github, and he simply didn't answer, so I sincerely found this was rude... But I agree I `should` have been maybe more careful with my words...

**Comment by 44vince44** [comment]
@stax76 and regarding the auto-loading of subtitles, I confirm (again) it works:
- file myvideo.mp4  or .mkv
- file(s) myvideo*.srt or .ass 

the .srt and .ass are loaded
