### ISSUE TITLE
Batch processing ignores resize settings

### ISSUE THREAD

**Issue by Inirdin** [staxrip/staxrip#644]
StaxRip usage questions can be asked here in the Issues section or in the [Discussions section](https://github.com/staxrip/staxrip/discussions).
Hi, I'm trying to restore videos from an old camera. I'm having really bad time trying to batch process those videos. They have resolution 704x576, but they are actually 16:9. So I set up resize to 704x396, then load all the videos and when I hit start it renders again in 704x576. It works when I do single file, but it ignores my setting when batch processing. I have PAR set to 1:1 and output mod set to 2.
![image](https://user-images.githubusercontent.com/36412360/113156795-9de94100-923a-11eb-9bde-bf8ae0f46e15.png)
![image](https://user-images.githubusercontent.com/36412360/113156899-b3f70180-923a-11eb-9544-25758a4c638f.png)
![image](https://user-images.githubusercontent.com/36412360/113157680-6929b980-923b-11eb-9559-9a0f881b9549.png)

What is the issue? How do I propagate the changes to all files which are in Jobs list?

**Comment by 44vince44** [comment]
@Inirdin your template is done correctly, however can you try using x264 and not VCEEnc, maybe it is related to VCEEnc

**Comment by 44vince44** [comment]
you're right there is a problem !

@Dendraspis there is a problem with resize filter when using BATCH encode with all the x264 codecs (x264, NVenc h264 etc).

How to reproduce:
1. set AVS resize filter to 856x480
2. set encoder to x264 or any one with included h264
3. click on "click here to open source file" select a folder with a few file, run the batch

**Encoder will not use the 856x480 filter**

@Inirdin has stated that other filters seem to work...

**Comment by stax76** [comment]
Width sticks and height is adjusted according to the detected aspect ratio unless disabled in the options:

Options > Aspect Ratio > Adjust height according to target display aspect ratio

**Comment by JJKylee** [comment]
I also think it's more like a matter of setting/usage.
When you do a file batch, you should be extra careful in setting `Options` in your template.
Almost all items there should be double checked.

In may case, I ran into an unexpected error when I batch tonemapped HDR videos to 8-bit SDR videos simply because I didn't uncheck `Import VUI metadata` in the template options.

**Comment by stax76** [comment]
@Inirdin 

If your source file has an incorrect/broken aspect ratio then disabling height adjustment is probably not sufficient because staxrip will encode it anamorphic by signalling a pixel aspect ratio in the video encoder, you might need to go at:

Options > Aspect Ratio

And force a correct aspect ratio. But resizing or upscaling SD video was generally never a good idea, remove the resize filter and encode it anamorphic, for that you also need to fix the aspect ratio if the source aspect ratio is broken.

**Comment by Inirdin** [comment]
@stax76 Toggling off the "Adjust height according to target display aspect ratio" fixed it. I thought that "target display aspect ratio" was the one in resize filter, but that is probably not the case. Thanks for helping everyone! 
I have bad experience with anamorphic video and same goes for interlaced video.

**Comment by 44vince44** [comment]
Hi all I'm sorry for my wrong bug confirmation, it was OBVIOUSLY not a bug. But as @Dendraspis knows, i had to do it very quicky and therefore I messed it due to the rush. My mistake...
