### ISSUE TITLE
DVD handling undesirable/broken

### ISSUE THREAD

**Issue by vonH** [staxrip/staxrip#655]
**Describe the bug**
This may be an external tool issue, but in Staxrip 2.1.x importing a DVD (VOB only) is simple; drag any VOB file from a directory (e.g. VTS_01_3.VOB and the remaining files [in this example, VTS_01_4.VOB,VTS_01_5.VOB,VTS_01_6.VOB] will be imported and joined creating a 'project' comprising of those three VOB files).

In Staxrip 2.4.x, dragging VTS_01_3.VOB only imports VTS_01_3.VOB and does not import the additional files into the project. Both use D2VWitch.

(side question: Was D2VWitch removed by default due to licensing issues?)

**Expected behaviour**
I expect the functionality for DVDs from Staxrip 2.1.x to remain in 2.4.x, but I'm unsure if this is an external tool issue or Staxrip issue.

**How to reproduce the issue**
1. Make sure D2VWitch is enabled and paths added.
2. Open a DVD directory and drag the third of fourth VOB (e.g. VTS_01_3.VOB) file into the 'Automatic' profile in Staxrip.
3. Observe the time in Staxrip. It only lists the time for the single VOB, NOT the time for (in this case) VTS_01_3.VOB and remaining VOBs.

**Provide information**
There is no error log. I am unsure if this behaviour is intentional. If so, why?

**Comment by vonH** [comment]
**Update:** This also impacts audio where only the audio from the first VOB is loaded, even if two VOB files are combined.
**Update2:** Enabling D2VWitch does not change the pre-processing in Staxrip and this causes the issue.

If D2VWitch was removed due to licensing, I suggest prompting the user to change pre-processing options to fix this problem. If it was removed to save space, I suggest adding it back in as its handling of DVD material is superior to DGIndex. 

**Fix:** If use D2VWitch for VOB content, change pre-processing options in Staxrip to: 

![image](https://user-images.githubusercontent.com/10042301/114249488-aa843c80-9992-11eb-8c7a-d53788b812dd.png)

**Question:** Why was D2VWitch removed?

**Comment by 44vince44** [comment]
@vonH 

Some time ago, DGIndex was removed and D2VWitch was introduced in Staxrip. Why? Because there was a misunderstanding about DGIndex's license!

Then more recently, DGIndex was restored, because it was clear that license allowed redistribution, and D2VWitch was removed. **D2VWitch was removed because we had many crash reports of users with mpeg files.** 

So, this is the FIRST report of D2VWitch being better than DGIndex. And it is specific to VOB files, in the case of multiple VOB files.

So this is a **Feature Request**: 
- include app D2VWitch
- make it default pre-processor ONLY for `vob` files

@vonH This is something that you can do manually, and if coders decide not to include it, you'll have to do it every new staxrip version.

**Comment by JJKylee** [comment]
I also think this is more of a usage issue.

**Comment by 44vince44** [comment]
However it could be nice to have a fully working solution. If D2VWitch works better with ALL `vob` files, we should consider it (only for `vob`)

**Comment by vonH** [comment]
1. I went from Staxrip 2.1.3.0 to 2.4.0. (clean install)
2. DVD handling on 2.1.x worked well
3. DVD handling on 2.4.x is broken using DGIndex - DGIndex on its own works fine and is a great tool.
4. I think the issue is due to Staxrip, but can't confirm.
5. This is specific to importing VOB - **not** any other file.

**Comment by 44vince44** [comment]
@vonH So this could be simply a command line argument issue with DGIndex. If it is so, there is no need to consider including D2VWitch again.


@Dendraspis the whole issue can be addressed like this:
- in the command line of DGIndex preprocesor, use parameter -AIF=[file1] (autoload files incrementally), instead of -IF=[file1]

See here: http://rationalqm.us/dgmpgdec/DGIndexManual.html#AppendixB

**Comment by JJKylee** [comment]
> Note: it seems the author has made a copy/paste of the previous descripton, so -ai and -i have the exact same description. CONFUSING!

Yeah... That's why we need to test the command line beforehand. 🙄😁

**Comment by JJKylee** [comment]
But I still don't think it's a matter to be put as the DEFAULT setting.
There may be other people who prefer `DGIndex` over `D2V Witch`. Preference can vary depending on use case. To them, switching to `D2V Witch` by default may seem inconvenient and unfair.
Let's be a little more considerate in a case like this. 🤔

**Comment by 44vince44** [comment]
Yes of course, no hasty decision must be made! But still I was trying to give @Dendraspis a clear summary of this 😄

**Comment by vonH** [comment]
The default command line with DGIndex is as follows 
`
... StaxRip2.4\Apps\Support\DgMpgDec\DGIndex.exe -i "...\VIDEO_TS\VTS_01_1.VOB" "...\VIDEO_TS\VTS_01_2.VOB" -ia 2 -fo 0 -yr 1 -tn 1 -om 2 -drc 2 -dsd 0 -dsa 0 -o "...\VIDEO_TS\VTS_01_1_temp\VTS_01_1" -hide -exit
`

**Comment by 44vince44** [comment]
it's a avi only for audio cutting... so video size is dummy

**Comment by stax76** [comment]
> This may be an external tool issue, but in Staxrip 2.1.x importing a DVD (VOB only) is simple; drag any VOB file from a directory (e.g. VTS_01_3.VOB and the remaining files [in this example, VTS_01_4.VOB,VTS_01_5.VOB,VTS_01_6.VOB] will be imported and joined creating a 'project' comprising of those three VOB files).

I don't remember such file auto-detection, I just tried 2.0.8.0 and the detection you described did not happen in my test!

Regarding audio, I tested with two files:

VTS_01_1.vob
VTS_01_2.vob

Both files are identical because apparently again I deleted my test DVD structures. 🙁

I used the 'Merge Files' option and for some reason I don't understand audio has only half the length of the video, but this happened with both 2.4.0 and 2.0.8.0. 😟

Anyway, merging VOB files was never a good idea because some DVD structures existed where this work flow was broken (asynchronous subtitles). Ripping with MakeMKV was much more reliable, at least for PAL which don't need crazy field processing.

**Comment by 44vince44** [comment]
I'm doing some tests now, to understand what happened.

However, I'm suggesting the use of -ai instead of -i.

It could be a more proper way to use DGIndex.

As for the audio, I'm doing tests right now

**Comment by 44vince44** [comment]
Here is the result of my test:
Special thanks @Dendraspis to provide me with a version where processing with BDsup2sub++ because it was preventing me from continuing with the test.

1. There are 5 vobs, i dropped them ALL FIVE in staxrip
2. DGIndex demuxed them and provided a full length feature 89:09 min
3. the audio tracks (2 tracks) have been demuxed correctly, their length is 89:09 min
 
`

Audio
--
Format : | AC-3
Format/Info : | Audio Coding 3
Commercial name : | Dolby Digital
Duration : | 1 h 29 min
Bit rate mode : | Constant
Bit rate : | 448 kb/s
Channel(s) : | 6 channels
Channel layout : | L R C LFE Ls Rs
Sampling rate : | 48.0 kHz
Frame rate : | 31.250 FPS (1536 SPF)
Compression mode : | Lossy
Stream size : | 286 MiB (100%)
Service kind : | Complete Main

`

So where is the difference between your vobs and mine ?

**Comment by stax76** [comment]
I don't understand how the audio could be too short when it was demuxed correctly?

In my test I played the demuxed audio file with mpv.net to check the length, here it was shown that audio was too short, now I did the same again but this time I opened the audio from file explorer and there the length was OK, this gave me a clue, I checked the command line of mpv.net in task manager and there was it:

"D:/Projekte/VB/StaxRip/Source/bin/Apps/Support/mpv.net/mpvnet.exe" --audio-delay=0 --audio-files="D:/Work/staxrip test video/VTS_01_2_temp/VTS_01_2 T80 3_2ch 384Kbps DELAY 0ms.ac3" "D:/Work/staxrip test video/VTS_01_2.**vob**"

StaxRip added one of the VOB files to play the audio, so staxrip should not add the video file for audio play when the source file is .d2v or .dgi because in that case there could be chained files.

Sorry about the confusion @Dendraspis.

**Comment by 44vince44** [comment]
Here is the problem: in some cases, like when you select audio track manually in the UI, staxrip will demux audio from the FIRST VOB only, although the audio is still there, waiting. 
=> Staxrip does not give you the choice of using one of the correctly demuxed files

Look:

![mpv-shot0001](https://user-images.githubusercontent.com/17828567/114266703-53b54c00-9a00-11eb-9e54-69ad9e7f4c48.jpg)

**Comment by Dendraspis** [comment]
So it is a usage issue.

You've selected the audio stream from the vob file directly, so StaxRip uses *ffmpeg* to extract it. But if you choose `vts_08_1 T80 3_2ch 448kbps DELAY 22ms.ac3` as source for your audio encoding, it should work.

So im my opinion a perfect behavior.  🤔

**Comment by 44vince44** [comment]
Yes the confusion comes from that the tracks that you MUST NOT SELECT are suggested at the top.

**Comment by Dendraspis** [comment]
> Yes the confusion comes from that the tracks that you MUST NOT SELECT are suggested at the top.

Totally depending on what you wanna do.  😜 

Implementing a proper solution wouldn't be very easy.  I think I would stick to the *manual solution*. Otherwise it seems we had to track, if demuxing was done, if it was successful, select an audio file, that was generated outside, ....
I think this is too much and too special.

@stax76 
Are you willed to implement something?  🤔  

> Sorry about the confusion @Dendraspis.

No need to apologize.

**Comment by stax76** [comment]
> Are you willed to implement something?

There are two issues with the audio context menu, one described by me and another one by @44vince44.

Additionally, when a user drops files on the main dialog, it might be possible the order is not as the user intends, if that is really true, staxrip could ask to confirm with a task dialog that lists the files, so the user can check the order, staxrip could check the order and warn if the order is not alphabetically.

I don't want to work on staxrip all the time, we did so much this and last year. We could create a 'Known Problems' wiki page, maybe @JJKylee and @44vince44 want to help with it, then it can be addressed in better times.

I want to work on mpv.net and other small tools, an issue I had recently is the last two libmpv builds of shinchiro are crashing mpv.net, I reported it and did not get help, so I'm currently learning how to build it myself, but I also want a deeper understanding of MSYS2 and WSL2, it's a lot of things to learn.

**Comment by 44vince44** [comment]
Yes I can do a small guide! later today maybe!

**Comment by stax76** [comment]
When you right-click to play the AC3 file, staxrip plays not only the AC3 file, it adds one of the VOB files and mpv.net plays only the length of that VOB file.

**Comment by 44vince44** [comment]
AH ok I got it, this is a feature that I never used :-)
Thanks for explaining.

**Comment by Dendraspis** [comment]
> Additionally, when a user drops files on the main dialog, it might be possible the order is not as the user intends, if that is really true, staxrip could ask to confirm with a task dialog that lists the files, so the user can check the order, staxrip could check the order and warn if the order is not alphabetically.

I've implemented it without any dialogs. If anybody would need a different order, he can still rename the files, even I can't imaging why this should be necessary.

> I don't want to work on staxrip all the time, we did so much this and last year. We could create a 'Known Problems' wiki page, maybe @JJKylee and @44vince44 want to help with it, then it can be addressed in better times.

😁   No problem, just remembered that your half-a-month-interval is almost over.
But I'm with you, after refurbishing the Thumbnailer, I need a StaxRip break, too.  😞 

> I want to work on mpv.net and other small tools, an issue I had recently is the last two libmpv builds of shinchiro are crashing mpv.net, I reported it and did not get help, so I'm currently learning how to build it myself, but I also want a deeper understanding of MSYS2 and WSL2, it's a lot of things to learn.

😒  /  👍

**Comment by 44vince44** [comment]
@stax76 @Dendraspis you both need some sleep 🤣 

The sorting works fine now. And everything works fine, I think this is very usable, I'll do a guide on how to import DVD folders.

**Comment by 44vince44** [comment]
I am including these screenshots in the small guide (Wiki pages require image external links, you cannot drop images as you do here)
![SNAG-0000](https://user-images.githubusercontent.com/17828567/114279666-76665580-9a3e-11eb-8aac-62d6d3d3f0d4.jpg)


![SNAG-0001](https://user-images.githubusercontent.com/17828567/114279674-7c5c3680-9a3e-11eb-93c2-4283e9586b98.jpg)

![SNAG-0002](https://user-images.githubusercontent.com/17828567/114279677-82521780-9a3e-11eb-9147-58a93447d92d.jpg)

**Comment by 44vince44** [comment]
The guide is online here:
https://github.com/staxrip/staxrip/wiki/VOB-%28DVD%29-Processing-Tips

**Comment by JJKylee** [comment]
Sometimes I'm surprised to find how eager people are to do _everything_ in StaxRip alone.
Maybe I don't have as much trust in StaxRip as they do. 😅😁

**Comment by vonH** [comment]
> Here is the result of my test:
> Special thanks @Dendraspis for providing me with a version where processing with BDsup2sub++ is disabled, because it was preventing me from continuing with the test.
> 
> 1. There are 5 vobs, i dropped them ALL FIVE in staxrip at the same time
> 2. DGIndex demuxed them and provided a full length feature 89:09 min
> 3. the audio tracks (2 tracks) have been demuxed correctly, their length is 89:09 min
> 
> ```
> Audio
> Format : | AC-3
> Format/Info : | Audio Coding 3
> Commercial name : | Dolby Digital
> Duration : | 1 h 29 min
> Bit rate mode : | Constant
> Bit rate : | 448 kb/s
> Channel(s) : | 6 channels
> Channel layout : | L R C LFE Ls Rs
> Sampling rate : | 48.0 kHz
> Frame rate : | 31.250 FPS (1536 SPF)
> Compression mode : | Lossy
> Stream size : | 286 MiB (100%)
> Service kind : | Complete Main
> ```
> 
> At this stage, no problem. SO DGIndex works correctly when you drop all VOB files.
> 
> 1. encoding: here **there is a problem**.
>    It confirms @stax76 and @vonH about the AUDIO. (this info has been updated)
>    If you select an audio track manually from the first choices on the top, then Staxrip will extract that track from the first VOB only.
>    If you select an audio track manually from choices below, then staxrip will use the correct demux audio and work correctly.
> 
> So this is a problem with the staxrip process with vobs.
> LOG:
> [vts_08_1_staxrip.log](https://github.com/staxrip/staxrip/files/6289607/vts_08_1_staxrip.log)
> 
> A reminder for all about the "windows selection bug": when multiselecting files, with CTRL, always begin with last file upto first file...

Is that only with the test build? The 2.4.0 app is entirely portable. I have also been able to reproduce the issue (VOBs not merging with DGIndex in 2.4.0) on a separate PC which has never used Staxrip before.

**Comment by 44vince44** [comment]
@vonH 
1) did you drop all files ?
2) did you leave audio as pre-selected for you or change selection of audio streams manually? In case you changed manually, did you select the proper stream in the area shown here :
![114279666-76665580-9a3e-11eb-8aac-62d6d3d3f0d4](https://user-images.githubusercontent.com/17828567/114295372-86694e00-9aad-11eb-86cd-49a8cf7ee95e.jpg)


By respecting those two steps, then Staxrip will work correcly.

**Comment by 44vince44** [comment]
Please close this thread !

**Comment by vonH** [comment]
Thank you for the reply, but why was the behaviour changed for audio?

**Comment by 44vince44** [comment]
I really don't know how and why audio behavior was changed for vob files (many changes have happened).
But the fact is, now, that the list of audio tracks has to be fixed to show proper choices in the upper part of if. This will probably be done one day (i think it will require a different handling for vob files, since vobs are the only files that support appending in staxrip, afaik)
