### ISSUE TITLE
%plugins_dir% macro maps to incorrect folder

### ISSUE THREAD

**Issue by TheMaskedOnion** [staxrip/staxrip#677]
**Describe the bug**
When using the %plugins_dir% macro is seems to map to ..\Staxrip\Settings\plugins\..... which is the old plugins location

**Expected behavior**
When using the %plugins_dir% it should to map to ..\StaxRip\Apps\Plugins\..

**How to reproduce the issue**
Open Staxrip, tools, folder and click plugins.

**Provide information**

<a href="https://ibb.co/gZHZgTZ"><img src="https://i.ibb.co/B2d2sZ2/Staxrip-Macro.png" alt="Staxrip-Macro" border="0"></a>

It seems that the function in staxrip/Source/General/General.vb on line 95 need to be update with the new locations.

**Comment by Dendraspis** [comment]
`..\Apps\Plugins\..` is used for plugins, that are shipped with StaxRip.
`..\Settings\Plugins\..` is not an old location for plugins, it is the location in which the user can (or should) put custom/other plugins in. So this seems to work correctly.

**Comment by 44vince44** [comment]
@TheMaskedOnion 
I confirm, the %plugins_dir% points to settings\plugins, which was introduced a few months ago so user puts his own plugins there instead of tampering the apps\plugins folder. 
So this is no bug, as @Dendraspis said above.


However there are macros who point to tools folders, like %app_dir:x265% ;  %app_dir:jpsdr%   (you can put any tool name there). These are the macros you are looking for.

**Comment by TheMaskedOnion** [comment]
Ahh ok all good then, close this please.
