### ISSUE TITLE
Subtitles filter profiles settings and subtitle UI improvement.

### ISSUE THREAD

**Issue by Komori-AA** [staxrip/staxrip#684]
**Is your feature request related to a problem? Please describe.**
Cannot use TextSubMod in new version staxrip 2.4.0 automatically.

**Describe the solution you'd like**
Add a filter profiles settings for subtitles, so I can choose what code I want to use like `TextSubMod` or `TextSub`

This is another request for subtitle, can you make hardcoded subtitle setting more viewable? New users cannot know they need to use `Ctrl+H` for subtitle and it's hard to find it in tools. 

**Describe alternatives you've considered**
N/A

**Explain why the feature matters to you**
Subtitle default setting is 'TestSub', every time I need to modify substile settings code to use `TextSubMod` instead of `TextSub`

**Additional context**
`TextSubMod` is very important for our subtitles, it includes a lot of effects we need.

**Comment by 44vince44** [comment]
@Komori-AA 

1) The version of TextSub included in Staxrip is pinterf's mod (part of XY-VSFilter). It is different from the original TextSub. Did you try it ? Did you see anything wrong with it ? When we switched to TextSub, we checked with very complex subtitle files, and the subtitles were rendered correctly.

2) AVS filter TextSubMod has been replaced by pinterf's version TextSub because **TextSubMod does not support 10 bit** input, which is becoming the new standard, whereas pinterf's TextSub has support for 10bit. Also pinterf's TextSub for AVS is being updated more recently.

3) As you know, you can change TextSub to textSubMod in the code. I suggest you continue doing that because it is not a big issue. 

4) If you use VapourSynth, Ctrl+H will use TextSubMod because in Vapousynth it has support for 10bit.

**Comment by Komori-AA** [comment]
@44vince44 
Thank you for quick replying.

Replying to:
- Question 1: We tried, but it cannot load the needed effects without using `TextSubMod`.
- Question 2-3: I understand, the feature we want is to provide profile subtitle settings, so you guys don't need to worry about which one is the best for `AVS filter` or `VapourSynth`, maybe it's good for backward supporting.
- Question 4: But yes, this is really good input, we haven't try this, if this is working well, we can switch to `VapourSynth` totally.
- Question 5: Good to know. We mainly upload hardcoding videos on websites, The website users seem like not using muxing, maybe the website is not supporting subtitle muxing. Though it's a good chance for us to try muxing on this website.

UI improvement idea:

I'm asking the functionality itself more visible instead of `Ctrl+H` more visible, here is my thought for UI improvement. 
![$UIQ}4()7OND4VW(}7X~PIU](https://user-images.githubusercontent.com/78115601/116796883-e479c780-aa94-11eb-9db5-b97c0242e596.png)
