### ISSUE TITLE
X264 mod by Patman

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#694]
I see here: https://github.com/Patman86/x264-Mod-by-Patman/releases/tag/0.161.3048%2B25

There is a new release of X264, and I see there was old release from Febreary (it was updated in V1.8.5 beta)

should we update this version on V2.5.0 or not? because is not a critical update and it will be updeted in the new StaxRip update...

Best regards

**Comment by DJATOM** [comment]
Looks like x264 core version bumped 2 times, gotta go update my mod then.

**Comment by 44vince44** [comment]
@papa-pitufo:
we did not update x264 build by Patman, because it has a bug with some resolutions.
This bug was fixed **2 days ago** by @DJATOM in his build, and we are waiting for @Patman86 to also corrects the bug in the same way.
Then we will update it. 

This is the bug: https://github.com/Patman86/x264-Mod-by-Patman/issues/1
Here it was fixed: https://github.com/staxrip/staxrip/issues/692#issuecomment-833618244

**Comment by JonathonSunshine** [comment]
I've found that while it encodes video, it is making the StaxRip GUI lag A LOT or just freeze up completely. https://github.com/staxrip/staxrip/issues/692#issuecomment-836046984
