### ISSUE TITLE
codec audio chance FPS speed

### ISSUE THREAD

**Issue by papa-pitufo** [staxrip/staxrip#698]
I notice only with BD and with 24.000 fps

When stxrip extract it does right.
Encode video to 24.000
But if you chance the audio, convert DTS/DTS MA/AC3 to EAC3, EAC3 changes the speed to 23.976!!!!!  (I only convert to EAC3 I don't know if it happen with other audio codec)

I test to 25, but with 25 doesn't change. it converts to EAC3 25 fps right

Is it a bug from ffmpeg????  Because I don't do anything, only change the bitrate of EAC3 preset

**Comment by 44vince44** [comment]
you should send us the log so we can analyze what happens...

**Comment by papa-pitufo** [comment]
Let's go

[2021-05-08 - 19.40.43 - El secreto de Thomas Crown 1999_staxrip.log](https://github.com/staxrip/staxrip/files/6446617/2021-05-08.-.19.40.43.-.El.secreto.de.Thomas.Crown.1999_staxrip.log)

Here you are (I think)

**Comment by JJKylee** [comment]
Your log doesn't have anything to do with audio encoding.

It's just that the video stream frame rate becomes different from the source fps (23.976) to the output fps (24) since the source filter `LWLibavVideoSource` doesn't catch the source frame rate correctly.

[Mediainfo]

```
----------------------- Media Info Source File -----------------------

C:\Users\JAVIG\Documents\Trabajos MKV\Temp_StaxRip\El secreto de Thomas Crown 1999_temp\El secreto de Thomas Crown 1999.h264

...
Video
...
Frame rate               : 23.976 (24000/1001) FPS
...
```

[AVS Script (source filter `LWLibavVideoSource`)]

```
------------------------- Source Script Info -------------------------

Width     : 1920
Height    : 1080
Frames    : 162969
Time      : 01:53:10.375
Framerate : 24 (24/1)
Format    : YUV420P8
```

Try an alternative source filter, or read [this wiki guide](https://github.com/staxrip/staxrip/wiki/How-to-edit-a-VFR(Variable-Frame-Rate)-video-(from-smartphones,-etc)-avoiding-audio-sync-issues-in-StaxRip) closely to learn how to set the (constant) frame rate for a source filter.

**Comment by Dendraspis** [comment]
`FFVideoSource` is what I would recommend.

**Comment by papa-pitufo** [comment]
> `FFVideoSource` / `FFMS2` is what I would recommend.

Ok, thanks, but StaxRip have selec LWLibavvideosource by defect in H264 and h265.  Curiosity.

I change to FFVideoSource.

But notice, it happens sometimes not always and only with BD 1080 never with 4k.

Best regards

**Comment by JJKylee** [comment]
> StaxRip have selec LWLibavvideosource by defect in H264 and h265. Curiosity.

The _default_ source filters for specific file types(extensions) are **_not_** something _hard-wired_ in StaxRip.
You can _always_ change them in `Settings` > `Source Filters` > `AviSynth` or `VapourSynth`.

Besides, you can also switch the source filters in the `AVS Filters`/`VS Filters` pane of the main window by right-clicking on the source filter.

Source filters can have bugs/peculiarities in dealing with specific sources. But you are not stuck there in StaxRip. You can always choose an easy alternative source filter, or going forward, participate in improving the particular source filters if you will.

IMO, this is a matter of settings/usage, not something to blame on StaxRip or source filters.

**Comment by 44vince44** [comment]
> Ok, thanks, but StaxRip have selec LWLibavvideosource by defect in H264 and h265. Curiosity.

@papa-pitufo that is because LWLibavvideosource is a very good source for h264 and h265. But some newer 4K sources load better with FFVideoSource. I noticed that also.

However, LWLibavVideoSource will be updated one day, and hopefully this will be fixed !

Note: there are other h265 videos that cause problems, and where LWLibavVideoSource behaves better.
This is why StaxRip offers a choice of several sources...

**Comment by papa-pitufo** [comment]
thanks friends

It is wonderful that in this community there are people as kind as you and people who are as beginners in this, you teach them, you explain it so well and you help me learn a little more every day.

Thanks a lot

**Comment by JJKylee** [comment]
If you see in _Preview_ that the frames decoded/served by `LWLibavVideoSource` have no problems like pixelation, blocking, etc., then another approach I can think of is applying `AssumeFPS` with fps `23.976` instead of replacing the source filter. It's under the `Frame Rate` category.

@papa-pitufo, plz close this thread if you think this 'issue' is resolved.

**Comment by papa-pitufo** [comment]
Ohh, sorry.

Thank you for your suggestions.

I close it.

**Comment by 44vince44** [comment]
If you send the complete log, maybe we'll see what is making this so slow...

**Comment by papa-pitufo** [comment]
> @papa-pitufo,
> 
> ## A) when you say "save project" do you mean:
> 1. Menu File > Save Project , same as Ctrl+S
>    or
> 2. create JOB with the NEXT button
> 
> ???
> 
> ## B) DEMUXING process is taking too long.
> Maybe your C: and G: are on the same physical drive. ARE C: and G: on the same physical drive ? They should be separate physical drives if you want speed in demuxing process (or SSD).
> 
> ## C) Why don't you use MakeMKV or MKVToolNix
> to MUX YOU BLURAY TO MKV, then you can use it in Staxrip, and it will be very fast.

Hi @44vince44 

A) Menu file/save project
B) Yes, buy in old version StaxRip doesn't spend so time
C) Yes, you are right, but sometimes the BD has 2 version or make a mkv duplicate (more or less) space into a hard disk

**Comment by 44vince44** [comment]
A) use Create JOB, with the "NEXT" button.
Once the job is in the joblist, the project is saved in your temp folder.
You can LOAD the project by opening the job list (F6), then click on the job and press LOAD.

B) StaxRip uses eac3to to handle BD folder. This needs to be changed one day, because eac3to is very old and is no more updated. When eac3to was last updated, there was no HDR10+, no Dolby Vision, etc... So the BD folder processing method must be completely changed (and the DVD also must, be improved). When the coders will have time, they will probably work on it...
I don't think any of them would spend any time on it currently...

C) yes I understand. Well then be patient, and use the saving method I explained to you in A)..

**Comment by papa-pitufo** [comment]
Sorry @44vince44 I don't find "create a job"

![image](https://user-images.githubusercontent.com/47916118/117655314-31495680-b197-11eb-8e7d-7e60dcb61451.png)

And in Files menu
![image](https://user-images.githubusercontent.com/47916118/117655471-6b1a5d00-b197-11eb-8a9f-995aefdcb333.png)

I don't find "create a job"

Thanks in advantage

**Comment by 44vince44** [comment]
@papa-pitufo 
![117655471-6b1a5d00-b197-11eb-8a9f-995aefdcb333](https://user-images.githubusercontent.com/17828567/117656142-a40aff80-b1a0-11eb-9032-bdae5928b086.png)

**Comment by papa-pitufo** [comment]
Yes, I do it, but I push and shown me the first screen "select a method..." don't show me "create new job"

**Comment by 44vince44** [comment]
OMG @papa-pitufo try to understand.
I asked you : 


-  1)  Menu File > Save Project , same as Ctrl+S
    or
-   2) create JOB with the NEXT button

you said that you use 1)

I replied: NO USE 2) instead of 1)

YOU USE THAT AFTER OPENING THE file. NOT BEFORE.

SO:

step 1) open the file
step 2) set the options for encoding, set the filters
step 3) you want to save ? DON'T USE SAVE. use "NEXT" instead. The NEXT button creates a job, and saves the project in the temp folder. Now the Job appears in the job list
step 4) if you want to process now, Press START. You don't want to process now ? then you can leave because the project is saved.

If you leave, then LATER you come back to StaxRip. How to load the saved project ? In staxrip, press F6. This opens the JOb list. Click on the job, and press button LOAD.

**Comment by JJKylee** [comment]
@papa-pitufo,

When I started using StaxRip about two and a half years ago, I first spent a week or so to understand how it works. I did it by reading _almost all_ related documents and then learning by doing myself. I was able to save time because I had some level of knowledge about FFmpeg at that time, but still I had to spend some amount of time.

What you are asking is the _bare minimum_ you are supposed to know. Like I said in the other thread, I'd like to recommend that you _invest some time_ to understand the basics about StaxRip. There are tons of resources around.

The Issue Tracker is not a tutoring tool. Plz understand that you need to invest something albeit not monetary on your side in order to make good use of this free and versatile tool. Take time to read the documents, first.

**Comment by papa-pitufo** [comment]
> OMG @papa-pitufo try to understand.
> I asked you :
> 
> 1. Menu File > Save Project , same as Ctrl+S
>    or
> 2. create JOB with the NEXT button
> 
> you said that you use 1)
> 
> I replied: NO! you should USE 2) instead of 1)
> 
> You are supposed to use it AFTER OPENING THE file. NOT BEFORE.
> 
> **SO:**
> 
> step 1) open the file
> step 2) set the options for encoding, set the filters
> step 3) you want to save ? DON'T USE SAVE. use "NEXT" instead. The NEXT button creates a job, and saves the project in the temp folder. Now the Job appears in the job list
> step 4) if you want to process now, Press START. You don't want to process now ? then you can leave because the project is saved.
> 
> If you leave, then LATER you come back to StaxRip. How to load the saved project ? In staxrip, press F6. This opens the JOb list. Click on the job, and press button LOAD.

Ok, thank you very much, I understand now right.

**Comment by papa-pitufo** [comment]
Yes, I think I have understood perfectly.

I have to read 214 pages in Dooms'9 or VideoHelp before I can ask here, which is where this GUI is made.

I understood that as you answered the other questions, this was a good forum to ask, but I understood perfectly, that for this type of questions THIS IS NOT THE FORUM.

But unfortunately, I have not been able to find anywhere that instead of using the GUI menu, I should use the Next button. (Thanks you @44vince44 for your patient)

I am sorry that my mental clumsiness could have angered you, I really understand, explaining something that you consider basic to people who ask because they do not consider it so basic, in the end it tires and I understand your anger.

That said, I'm so sorry @JJKylee I asked these stupid questions.

So sorry

**Comment by JJKylee** [comment]
@papa-pitufo,

Don't get me wrong. I'm not angry at all. On the contrary, I was kind of interested because I able to see what I couldn't from my perspective. But I recommend you to use _Discussions_ module, not this Issue Tracker for questions you may have.

In case you didn't find it in the wiki, plz visit [this site](https://encodingwissen.de/praxis/staxrip/) for basics. It's in German, but Google Translate will do a good job. It's kind of old, but maybe it will help you understand the basics of encoding and start using StaxRip.

**Comment by papa-pitufo** [comment]
> @papa-pitufo,
> 
> Don't get me wrong. I'm not angry at all. On the contrary, I was kind of interested because I able to see what I couldn't from my perspective. But I recommend you to use _Discussions_ module, not this Issue Tracker for questions you may have.
> 
> In case you didn't find it in the wiki, plz visit [this site](https://encodingwissen.de/praxis/staxrip/) for basics. It's in German, but Google Translate will do a good job. It's kind of old, but maybe it will help you understand the basics of encoding and start using StaxRip.

Ok, I use Discussion module for my question and take a look a German site,

Thanks a lot
