### ISSUE TITLE
Need a feature where users can select up to how many dB they want to normalize the audio

### ISSUE THREAD

**Issue by broprosam** [staxrip/staxrip#719]
on StaxRip, while encoding an Audio, if we choose the normalize option, the gain output always becomes **0 dB**. But sometimes normalize an audio up to 0 dB makes the audio distorted. So, I am requesting for a feature, where there will be an option, where users can select up to how many dB they want to normalize the audio. Like, normalize the audio up to **-3 dB** or **-2 dB** or **-1 dB** or up to whatever dB they want.

**Comment by Dendraspis** [comment]
What's the problem using **Gain** ?

![image](https://user-images.githubusercontent.com/50659978/119704314-cdda4c80-be57-11eb-8869-b3f1fdf01259.png)

**Comment by broprosam** [comment]
> What's the problem using **Gain** ?

"Normalize" & "increase/decrease Grain" two are different.

**Comment by JJKylee** [comment]
> "Normalize" & "increase/decrease Grain" two are different.

No. They are related, like @Dendraspis pointed out. I was wrong too in this regard. 😓

I tried `normalize` and `gain to -1` at the same time as follows.

![StaxRip_2 6 0_audio_normalize_gain_to_-1_20210526](https://user-images.githubusercontent.com/3157518/119733781-dbc7a780-be2e-11eb-99ff-7a94e9a752a9.png)

Here's the log:
[MBAFF interlaced 422 10bit VFR sample_new_staxrip.log](https://github.com/staxrip/staxrip/files/6549713/MBAFF.interlaced.422.10bit.VFR.sample_new_staxrip.log)

The source audio _max volume_ is `-1.5 dB` (line 383).
But `-af volume=0.5dB` is applied (instead of `1.5dB`) in the course of conversion to flac _following the **gain** setting `-1`_ (line 405).
And when the audio is encoded to aac, no more gain (or normalize) is applied, as expected (line 456).

Therefore, you can _**set the gain value**_ if you want the audio to normalize to that specific value.

**Comment by 44vince44** [comment]
@broprosam the feature you are asking for exists and works, as @JJKylee explained above (at least tested with qAAC):

input -> Normalize YES/NO -> Gain -> Output.

So if you want to normalize at -3dB, the ckeck `Normalize` box, then set `gain` to -3db.


Here is the output of StaxRip, on an example with VERY LOW audio, so you see the effect:

![SNAG-0000](https://user-images.githubusercontent.com/17828567/119767556-b59e1800-bebf-11eb-9c49-936f6cddf5b8.jpg)

Note 1: if this doesn't work for you, maybe you should use fresh settings and templates. @JJKylee has recently had problems with audio due to old settings

Note 2: if it still doesn't work, please tell us the encoder you are using (or send log)

Note 3: if you are concluding from the log's command line that this is not working, you should know that although StaxRip suggests the encoder is doing the audio processing, it's not true. The processing is done in an intermediate file by ffpmeg. The final encoder only encodes.

Note 4: If you set Normalize, gain -3, then you'll maybe get Normalize at -2.2, or -3.4. Why ? this is due to the 24+ bit conversions. The intermediate file is sometimes 24b, sometimes 64b. On those files, the peak can be interpreted differently, therefore, you can slight differences (unlike 16bit, where a peak's value is strict)

**Comment by JJKylee** [comment]
I think we can close this thread.
