### ISSUE TITLE
Need project option for whether to include timestamps of source file in mkvmerge

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#729]
StaxRip version 2.6.9.

Currently, when the user chooses to extract timestamps from VFR MKV files in project option, these timestamps of the source file are _automatically_ included in `mkvmerge`. This results in critical desync issues of the output files by forcing _wrong timestamps_ on them, esp. in the following situations.

1. When the user cuts the source file.
2. When the user changes the frame rate.

These situations were pointed out in my reply posts in issue #727.

We can avoid this problem by introducing a new project option that enables the user to decide whether or not the timestamps of the source file will be applied to the target files in `mkvmerge`.

**Comment by 44vince44** [comment]
Just to complete @JJKylee 's request, and for the record, i suggested we remove the current option `Extract Timestamps from VFR MKV files` and put in its place `Use Extracted Timestamps from VFR MKV files`.

So, Staxrip would ALWAYS extract the timestamps file when it finds it in the source, and user will be able to switch on or off the option to use it.

Also for the record, there is one additional situation not mentioned above, that justify not using the timestamp file:

1. When user cuts the source file.
2. When user changes the frame rate
3. When user uses fpsnum,fpsden in the source filter (this is additional, not included in 2, since user can have a VFR source file with fps=13.258999 and use in the source filter  fpsnum=13.258999 which should convert the stream to a CFR of 13.258999 fps)

**Comment by Dendraspis** [comment]
> We can avoid this problem by introducing a new project option that enables the user to decide whether or not the timestamps of the source file will be applied to the target files in `mkvmerge`.

Personally I don't like this solution. We already have an option to demux and mux the timestamps. If you change the filters and you come to the conclusion, that the timestamps are wrong or/and you don't want to include them, you can always delete the Timestamp entry in the muxer configuration.

Will take a few days until I start working on it, but I prefer just an Assistant warning in case of a VFR source and changed FPS.  🤔

**Comment by JJKylee** [comment]
> I prefer just an Assistant warning in case of a VFR source and changed FPS. 🤔

Oh, that's a better idea!!!!! 😲👍
Actually, this more elegant approach didn't occur to me when I was thinking about this issue. 😅

**Comment by Dendraspis** [comment]
Finally I extended the timestamp options. Now we can choose to extract timestamps for all MKV files or for VFR sources only.
Additionally there is an Assistant warning in case of an MKV container, a given timestamps file and a changed frame rate or frame count.

So I think this and its related problems should be handled now. 
It will be distributed with the next release....

**Comment by JJKylee** [comment]
I tested [`ExactDedup`](https://github.com/staxrip/staxrip/discussions/741) with `test.mkv`(CFR) [here](https://forum.videohelp.com/threads/402416-repair-Videos-with-duplicates-and-dropped-frames#post2624799) on VideoHelp in v2.6.33, and it seems like the _Assistant_ is working correctly.

![StaxRip_2 6 33_timestamps-file_Assistant_warning_20210711](https://user-images.githubusercontent.com/3157518/125212518-d7324380-e262-11eb-845a-c00c43308742.png)

Will report back when I run into a bug.
