### ISSUE TITLE
Unable to Denoise

### ISSUE THREAD

**Issue by SnorreSelmer** [staxrip/staxrip#73]
Every time I try to check the "Noise" option, I get "dfttest: unable to load libfftw3f-3.dll" as a Script Error.

The file can be found in Apps/Support/FFTW and Apps/Plugins/VS/BM3D, but I don't know what's trying to use it, so I can't diagnose where I might need to put the file to get this to work.

**Comment by Patman86** [comment]
Hi,

the path for BM3D file is "Apps\Plugins\VS\BM3D" anmd the path for libfftw3f-3.dll is "Apps\Support\FFTW".

**Comment by stax76** [comment]
Did you install FFTW in the apps management dialog?

Next build will ask to install it when dfttest is used.

**Comment by 44vince44** [comment]
Sorry, my mistake, there are three libfft*.dll in my System32 folder. So something has been installed but I just don't remember. But then why are these files provided in staxrip, and why staxrip doesn't use them directly, instead of looking for them in System32:

File  :                             System32                        Staxrip folder
libfftw3-3.dll                 crc 4350cdcb                    crc 4350cdcb
libfftw3f-3.dll                crc 9e84c888                    crc 9e84c888
libfftw3l-3.dll                crc 1f96e697                     missing

So shouldn't staxrip use the files provided in its own folders (and just add to them the missing file?)
