### ISSUE TITLE
Can we please get a new "stable" version of StaxRip?

### ISSUE THREAD

**Issue by pwacooijmans** [staxrip/staxrip#75]
I have seen tons of changes since the last stable version, I wonder when we will get the next stable version.

Many Thanks in advance.

Kind Regards,

Pieter Cooijmans

**Comment by Revan654** [comment]
I'm a bit backlogged, to do a Fully packaged Release. Since I have to build all the Files included with StaxRip. Which takes awhile to do. You can just grab the release from Pipeline and replace the exe file.

I did Push a new Build to the Pipeline : https://ci.appveyor.com/project/Revan654/staxrip/build/artifacts

When I get a chance I need to Re-Build the Pipeline to copy and build all the external files as well.

**Comment by expanse191** [comment]
Are the beta builds found here https://staxrip.readthedocs.io/intro.html#download  stable enough to use??

**Comment by stax76** [comment]
The latest beta should be fine.

**Comment by 44vince44** [comment]
To confirm what Stax76 said, I am using latest beta 2.0.4.10 for several days and it's running smooth! and thanks again for the good work!

**Comment by stax76** [comment]
Maybe good to wait for VapourSynth R48, R47.2 is buggy I heard.

**Comment by Patman86** [comment]
R48 RC1 is out.
