### ISSUE TITLE
VSFilterMod doesn't work with HEVC input.

### ISSUE THREAD

**Issue by viktorz3008** [staxrip/staxrip#766]
VSFilterMod works perfectly with H.264 input videos, but it doesn't work with H.265 input videos. The output + preview has the same issue. VSFilterMod isn't applied for H.265 videos based on my test no matter what. MeGUI is still be able to encode VSFilterMod + H.265 normally.

**Comment by JJKylee** [comment]
_VSFIlterMod_ works only with 8-bit input in AviSynth. See if your source is HBD. And it's recommended to always use _xy-VSFilter_ (the default hardburning filter called with `Ctrl+H`). See the [_xy-VSFilter_ manual](http://avisynth.nl/index.php/Xy-VSFilter) for how to use it.

**Comment by viktorz3008** [comment]
> _VSFIlterMod_ works only with 8-bit input in AviSynth. See if your source is HBD. And it's recommended to always use _xy-VSFilter_ (the default hardburning filter called with `Ctrl+H`). See the [_xy-VSFilter_ manual](http://avisynth.nl/index.php/Xy-VSFilter) for how to use it.

But MeGUI can encode it with vsfiltermod, then why Staxrip can't?

**Comment by JJKylee** [comment]
Just check if _VSFilterMod_ works on the _**same source**_ in MeGUI first.

**Comment by viktorz3008** [comment]
> Just check if _VSFilterMod_ works on the _**same source**_ in MeGUI first.

Yes. I had to switch to MeGUI because Staxrip cannot use vsfiltermod with that source. I tested so many times and I'm sure something wrong with Staxrip. And maybe 10 bit source won't work with vsfiltermod, but it does work on MeGUI.

**Comment by JJKylee** [comment]
The _VSFIlterMod_ in StaxRip is from this repository: https://github.com/sorayuki/VSFilterMod
It supports HBD in VapourSynth, but not in AviSynth. That's why StaxRip uses _xy-VSFilter_ by default.

If the _VSFilterMod_ in MeGUI works on the same high bit depth source, then maybe it's a customized version modded by the MeGUI dev team. Like you said, if you do want to use _VSFilterMod_ on HBD sources, go with MeGUI.

**Comment by viktorz3008** [comment]
I used the same vsfiltermod.dll from the same developers too. I even copied it to Staxrip. Still, Staxrip refused to work with it.

**Comment by JJKylee** [comment]
Plz be more specific. 'Refused to work' like what? Supporting materials like logs or error messages or screenshots are needed.

**Comment by viktorz3008** [comment]
> Plz be more specific. 'Refused to work' like what? Supporting materials like logs or error messages or screenshots are needed.

Preview and Final output just didn't have vsfiltermod (subtitle) applied. Just a normal output without hardcoded subtitle.

**Comment by JJKylee** [comment]
Well, you're just repeating your original _anecdotal_ statement. In order to see if this is really an issue with StaxRip itself, concrete materials like _**script source code**_, _**logs**_, etc. are necessary.

I don't have any proper sources to _experiment_ and reproduce the issue on my side. I'll pass it on to someone else.
