### ISSUE TITLE
About option "Add filter to convert chroma to 4:2:0"

### ISSUE THREAD

**Issue by katyurua** [staxrip/staxrip#830]
I just noticed there is a video settings option "Add filter to convert chroma to 4:2:0"

And it's selected by default
I can't find anything about this filter in log file. I'm very confusing about this.

Q1: 
What filter is added by this option? (vs filter? avs filter? staxrip filter?)
Will this filter change color depth? (16bit to 10bit? 10bit to 8bit? )
 

Q2: 
My source is YUV444
I always manually add a filter to convert it to YUV420
``` python
clip = core.resize.Bicubic(clip, format=vs.YUV420P10)
```

In this case, will this option convert it chroma to 4:2:0 again? [ 444(source)->420-(filter)->420(setting) ]
 Or just bypass it ? ( "Add filter to convert chroma to 4:2:0" option not working )

Q3:
YUV420 source with bm3d
My process is 420->444->BM3D->420->X265
In this case, where is this “convert chroma to 4:2:0” filter added ?
In the beginning or the end ? or somewhere in the middle ？

**Comment by Dendraspis** [comment]
#### Q1
Depending on the filter setup `ConvertToYUV420()` or `clip.resize.Bicubic(matrix_s=xxx, format=vs.yyy)` (xxx and yyy depending on the source) is applied to the source filter.

#### Q2
In your case it seems (because no further details are provided) to be like:
` 444(source)->420-(setting)->420(filter)`
After opening your YUV444 video file (with this setting enabled), simply open the Code Editor and check the *Source* filter section.

#### Q3
Always directly after declaring the source in the *Source* filter section.
