### ISSUE TITLE
Audio encoding "Command Line" track mapping option

### ISSUE THREAD

**Issue by jlw4049** [staxrip/staxrip#842]
I currently use the command line option for my first main track, in order to use ffmpeg to pipe to qaac and encode 2.0, however there is no macro for track selection of any sort. 

By default the `%input%` macro, does add just the input, however, this does not include the track selection `-map 0:a:x`. Personally I would like to see the program select the right track depending on the input in the audio selection entry box, like the program works for all of the other codecs. 

I'd like to request some sort of track selection macro, preferably in the `-map 0:a:x` format.

Alternatively, if the normal audio encoding with QAAC is actually piped from ffmpeg to qaac, i'd like to be able to define some custom options to FFMPEG, in order to add some audio filter customizations. Which is ultimately what I'm trying to do, however, using QAAC encoder doesn't allow me to customize the ffmpeg side of things (if it's even piped from ffmpeg)

**Comment by Dendraspis** [comment]
For now, I have added two new macros:  `%streamid0%` and `%streamid1%`  -  the number indicates the number of the first stream overall (not only audio streams). If the track is not a stream the value is empty.

Because it is possible to customize the whole command line and you can load audio files as well as streams from a source file, it would become very problematic doing more than that. So in your example you have to add: `-map 0:%streamid0%` 

...will be available with the next release...
Please test and re-open, if there is a problem...

**Comment by jlw4049** [comment]
Thank you, I will test this out once it's available!
