### ISSUE TITLE
Virus in the lastest release of StaxRip v2.13.0

### ISSUE THREAD

**Issue by armctec** [staxrip/staxrip#879]
The lastest version v2.13.0, fired my Antivirus Symantec, but i had no problem in previous version v2.12.0.

Anyone else had a problem? Or is it a problem here on my machine?

Best Regards
Armctec

**Comment by sheik124** [comment]
Might be a problem with Symantec...

What file in particular did it complain about? Nothing here with Windows Defender and Malwarebytes.

**Comment by armctec** [comment]
The virus that Symantec accused was ws.reputation.1 I found it strange, but it was the company's computer. So there was no way I could disable. Being able to test it at home today, on my kaspersky antivirus, didn't show anything.
Sorry for the trouble, but something strange with the symantec antivirus, because it wasn't just one file that it accused, but several.
From what I could understand this ws.reputation.1 virus is when a user reports to them that the file is suspicious but almost all executable files and dlls were being accused.

I did a complete test on the machine and there was no other sign of a virus.

Sorry for the inconvenience, I wouldn't want to harm your image, I've been using this tool for a long time since I discovered it.

**Comment by Dendraspis** [comment]
You were absolutely right posting this here. You also haven't tried to slender someone, but just reported the problem and asked if there are others with the same problem. Regarding the security potential I don't see any problem with your post. 👍

Because there is nobody else with such an observation, I'll close this issue for now.

@sheik124 
Thanks for the quick help and response.  👍
