### ISSUE TITLE
Can't open VOB file

### ISSUE THREAD

**Issue by ViRb3** [staxrip/staxrip#881]
**System**
- Windows 11 x64
- StaxRip v2.13.0

**Description**
Just downloaded StaxRip for the first time ever. Opening a VOB file from old HI8 camera DVD recording throws the following error and removes the source file from the GUI:

```
Script Error

Cannot load a 32 bit DLL in 64 bit Avisynth: 'C:/Users/User/Desktop/StaxRip-v2.13.0-x64/Apps/Support/DgMpgDec/DGDecode.dll'.

(C:\Users\User\Desktop\VTS_01_1-00.00.00.000-00.00.40.522_temp\VTS_01_1-00.00.00.000-00.00.40.522_source.avs, line 2)
```

Thanks

**Comment by fredlkrue** [comment]
Dendraspis commented on this issue on discord:

05/14/2022
@SAM Todman  It looks like I accidentally took the x86 bit DLL instead of the x64 one.  😓 
I'll use the right one for the next release. If you can't wait, you can replace it with the proper one from here:  https://www.rationalqm.us/dgmpgdec/dgmpgdec2007.zip
Thanks for the report.  🙂
