### ISSUE TITLE
StaxRip - not stable

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#930]
my old CPU i7-6700K + win10x64 = was without problems

my new CPU i7-12700 +win10x64 = problems started - The StaxRip not stable when I choose x264 or x265 codecs

it starts for a long time or immediately goes into freezing, then after a while:

- either frozen at some % of processing
- or processes the file in 5 seconds
- either breaks win10 blue screen comes out

i7-6700k = cores 4 and threads 8 / was without problems

new CPU i7-12700 = cores 8 + low 4 + threads 16 + low 4 / problems started

**Comment by Discograp** [comment]
simply/default (i7-12700) - disabled "weak cores" in UEFI/BIOS settings

in the settings of win10x64 - power consumption of weak cores - disabled

Х264 / Х265 - (important) 1080P and lower resolution - work well (HDD = HDD and SSD)
Х264 / Х265 - (important) 2160P and higher resolution - work with the "Medium" preset (HDD = SSD)

**Comment by Discograp** [comment]
my choice:

264+AV1 = CPU or QSVENC(without AV1)

265+VP9 = CPU or NVENC

**Comment by Dendraspis** [comment]
Sounds like a problem with the CPU itself, drivers, cooling, RAM, overclocking, old Motherboard firmware, wrong Motherboard settings, ....

Maybe try `IntelBurnTest` and see if that leads to similar results. If that works, you might wanna change some CPU optimizations in the encoder settings.

Because it seems to be a pretty new CPU, it is possible, that some drivers or the OS can't handle it properly. There are sooo many possibilities.... Nothing we can really handle here, sorry.
