### ISSUE TITLE
Please, help! all who can

### ISSUE THREAD

**Issue by Discograp** [staxrip/staxrip#979]
Please, help! all who can
need latest version

- x 264/265
- qtgmc(avisynth)
- bicubic
- (all) IVTC - anime + decomb + tivtc

nvenc 720 https://www.videohelp.com/software/NVEnc
qsvenc 735 https://github.com/rigaya/QSVEnc/releases

**Comment by Discograp** [comment]
ab-av1 (v0.7.4) https://github.com/alexheretic/ab-av1/releases/tag/v0.7.4

Is this script compatible with staxrip?
where to insert it?

**Comment by Dendraspis** [comment]
I highly recommend joining out [Discord](https://discord.gg/uz8pVR79Bd) for such questions.
Nevertheless a new release was released meanwhile, maybe it helps.

> ab-av1 (v0.7.4) https://github.com/alexheretic/ab-av1/releases/tag/v0.7.4
> Is this script compatible with staxrip? where to insert it?

Because it's a standalone app and ***not*** a AVS/VS script, it would need to implement it completely, which I won't do at the moment. 
You could run it via PowerShell script, Batch, Events, ... but I don't think that's what you're looking for.

**Comment by Begemotoid** [comment]
> Я настоятельно рекомендую присоединяться к [Discord](https://discord.gg/uz8pVR79Bd) для таких вопросов.

I don't see any discussion on your discord.

**Comment by Dendraspis** [comment]
You have to accept the rules. Read the message in `#rules` where you start after joining.

**Comment by Discograp** [comment]
> I highly recommend joining out [Discord](https://discord.gg/uz8pVR79Bd) for such questions. Nevertheless a new release was released meanwhile, maybe it helps.
> 
> > ab-av1 (v0.7.4) https://github.com/alexheretic/ab-av1/releases/tag/v0.7.4
> > Is this script compatible with staxrip? where to insert it?
> 
> Because it's a standalone app and _**not**_ a AVS/VS script, it would need to implement it completely, which I won't do at the moment. You could run it via PowerShell script, Batch, Events, ... but I don't think that's what you're looking for.

aaa - ok - thanks!
